import "@/lib/api/client";

export {
  v1CustomFieldArchiveMutation,
  v1CustomFieldDeleteMutation,
  v1CustomFieldsCreateMutation,
  v1CustomFieldUpdateMutation,
  v1DocumentDeleteMutation,
  v1DocumentUpdateMutation,
  v1FolderDeleteMutation,
  v1FolderUpdateMutation,
  v1IssueDeleteMutation,
  v1IssueRelationDeleteMutation,
  v1IssueRelationsCreateMutation,
  v1IssueRelationUpdateMutation,
  v1IssueUpdateMutation,
  v1IssuesDocumentsCreateMutation,
  v1IssuesDocumentsRelateMutation,
  v1IssuesDocumentsUnrelateMutation,
  v1NamespaceDeleteMutation,
  v1NamespacesDocumentsCreateMutation,
  v1NamespacesFoldersCreateMutation,
  v1NotificationDeleteMutation,
  v1NotificationUpdateMutation,
  v1OrganizationDeleteMutation,
  v1OrganizationMemberInviteRevokeMutation,
  v1OrganizationMemberRemoveMutation,
  v1OrganizationMembersAcceptMutation,
  v1OrganizationRoleDeleteMutation,
  v1OrganizationTeamDeleteMutation,
  v1OrganizationTeamMemberRemoveMutation,
  v1OrganizationTeamMembersAddMutation,
  v1OrganizationTeamUpdateMutation,
  v1OrganizationTeamsCreateMutation,
  v1PermissionsCreateMutation,
  v1OrganizationsDocumentsCreateMutation,
  v1OrganizationsFoldersCreateMutation,
  v1ProjectDeleteMutation,
  v1ProjectsDocumentsCreateMutation,
  v1ProjectsDocumentsRelateMutation,
  v1ProjectsDocumentsUnrelateMutation,
  v1ResourceCustomFieldValueDeleteMutation,
  v1ResourceCustomFieldValuePutMutation,
  v1TodoDeleteMutation,
  v1TodoUpdateMutation,
  v1UserResetPasswordMutation,
  v1UserUpdateMutation,
} from "@/lib/client/@tanstack/react-query.gen";
