import "@/lib/api/client";

export {
  v1IssueDeleteMutation,
  v1IssueRelationDeleteMutation,
  v1IssueRelationsCreateMutation,
  v1IssueRelationUpdateMutation,
  v1IssueUpdateMutation,
  v1NamespaceDeleteMutation,
  v1NotificationDeleteMutation,
  v1NotificationUpdateMutation,
  v1OrganizationDeleteMutation,
  v1OrganizationMemberInviteRevokeMutation,
  v1OrganizationMemberRemoveMutation,
  v1OrganizationMembersAcceptMutation,
  v1OrganizationRoleDeleteMutation,
  v1OrganizationRoleMemberRemoveMutation,
  v1OrganizationRoleMembersAddMutation,
  v1OrganizationRolePermissionAddMutation,
  v1OrganizationRolePermissionRemoveMutation,
  v1ProjectDeleteMutation,
  v1TodoDeleteMutation,
  v1TodoUpdateMutation,
  v1UserResetPasswordMutation,
  v1UserUpdateMutation,
} from "@/lib/client/@tanstack/react-query.gen";
