version: "2"
checks:
  argument-count:
    config:
      threshold: 6
  complex-logic:
    config:
      threshold: 7
  file-lines:
    config:
      threshold: 750
  method-complexity:
    config:
      threshold: 7
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 75
  nested-control-flow:
    config:
      threshold: 6
  return-statements:
    config:
      threshold: 7
plugins:
  duplication:
    config:
      languages:
        go:
          mass_threshold: 120
exclude_patterns:
  - "**/*.d.ts"
  - "**/*_test.go"
  - "**/dist/"
  - "**/features/"
  - "**/node_modules/"
  - "**/scripts/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "**/vendor/"
  - "cmd/"
  - "configs/"
  - "internal/testutil/"
  - "internal/transport/http/api"
  - "tests/"
  - "tools/"
