version: "2"
checks:
  argument-count:
    config:
      threshold: 5
  # complex-logic:
  #   config:
  #     threshold: 7
  # file-lines:
  #   config:
  #     threshold: 750
  # method-complexity:
  #   config:
  #     threshold: 7
  method-count:
    config:
      threshold: 35
  method-lines:
    config:
      threshold: 75
  # nested-control-flow:
  #   config:
  #     threshold: 6
  return-statements:
    config:
      threshold: 7
  similar-code:
    config:
      threshold: 10
  identical-code:
    config:
      threshold: 8
exclude_patterns:
  - "**/*.d.ts"
  - "**/*_test.go"
  - "**/dist/"
  - "**/features/"
  - "**/node_modules/"
  - "**/scripts/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "**/vendor/"
  - "cmd/"
  - "configs/"
  - "internal/testutil/"
  - "internal/transport/http/gen"
  - "tests/"
  - "tools/"
