---
- - :restrict
  - LGPL-3.0-only
  - :who: gabor@opcotech.com
    :why: License would not allow proprietary use
    :versions: []
    :when: 2022-11-03 06:43:59.933561000 Z
- - :restrict
  - LGPL-2.1-only
  - :who: gabor@opcotech.com
    :why: License would not allow proprietary use
    :versions: []
    :when: 2022-11-03 06:44:48.119923000 Z
- - :restrict
  - GPL-2.0-only
  - :who: gabor@opcotech.com
    :why: License would not allow proprietary use
    :versions: []
    :when: 2022-11-03 06:45:46.764558000 Z
- - :restrict
  - GPL-2.0-or-later
  - :who: gabor@opcotech.com
    :why: License would not allow proprietary use
    :versions: []
    :when: 2022-11-03 06:45:46.764558000 Z
- - :restrict
  - GPL-3.0-only
  - :who: gabor@opcotech.com
    :why: License would not allow proprietary use
    :versions: []
    :when: 2022-11-03 06:45:55.730065000 Z
- - :restrict
  - GPL-3.0-or-later
  - :who: gabor@opcotech.com
    :why: License would not allow proprietary use
    :versions: []
    :when: 2022-11-03 06:45:55.730065000 Z
- - :restrict
  - AGPL-3.0-only
  - :who: gabor@opcotech.com
    :why: License would not allow proprietary use
    :versions: []
    :when: 2022-11-03 06:47:49.497238000 Z
- - :restrict
  - AGPL-3.0-or-later
  - :who: gabor@opcotech.com
    :why: License would not allow proprietary use
    :versions: []
    :when: 2022-11-03 06:47:49.497238000 Z
- - :permit
  - Apache-2.0
  - :who: gabor@opcotech.com
    :why:
    :versions: []
    :when: 2022-11-02 16:33:45.694286000 Z
- - :permit
  - BSD-2-Clause
  - :who: gabor@opcotech.com
    :why:
    :versions: []
    :when: 2022-11-02 21:58:28.606785000 Z
- - :permit
  - BSD-3-Clause
  - :who: gabor@opcotech.com
    :why:
    :versions: []
    :when: 2022-11-02 16:33:51.189389000 Z
- - :permit
  - ISC
  - :who: gabor@opcotech.com
    :why:
    :versions: []
    :when: 2022-11-02 16:34:36.762191000 Z
- - :permit
  - MIT
  - :who: gabor@opcotech.com
    :why:
    :versions: []
    :when: 2022-11-02 16:33:41.785277000 Z
- - :permit
  - MPL-2.0
  - :who: gabor@opcotech.com
    :why:
    :versions: []
    :when: 2022-11-02 21:58:20.530206000 Z
- - :approve
  - github.com/spf13/afero
  - :who: gabor@opcotech.com
    :why: https://github.com/spf13/afero/blob/master/LICENSE.txt
    :versions: []
    :when: 2023-02-06 14:51:57.058823000 Z
- - :approve
  - github.com/spf13/cobra
  - :who: gabor@opcotech.com
    :why: https://github.com/spf13/cobra/blob/master/LICENSE.txt
    :versions: []
    :when: 2023-02-06 14:52:21.045421000 Z
