// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/opcotech/elemo/internal/service (interfaces: EntitlementService)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_entitlement_gen.go -package=mocksvc . EntitlementService
//

// Package mocksvc is a generated GoMock package.
package mocksvc

import (
	context "context"
	reflect "reflect"

	entitlement "github.com/opcotech/elemo/internal/entitlement"
	gomock "go.uber.org/mock/gomock"
)

// MockEntitlementService is a mock of EntitlementService interface.
type MockEntitlementService struct {
	ctrl     *gomock.Controller
	recorder *MockEntitlementServiceMockRecorder
	isgomock struct{}
}

// MockEntitlementServiceMockRecorder is the mock recorder for MockEntitlementService.
type MockEntitlementServiceMockRecorder struct {
	mock *MockEntitlementService
}

// NewMockEntitlementService creates a new mock instance.
func NewMockEntitlementService(ctrl *gomock.Controller) *MockEntitlementService {
	mock := &MockEntitlementService{ctrl: ctrl}
	mock.recorder = &MockEntitlementServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEntitlementService) EXPECT() *MockEntitlementServiceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockEntitlementService) Get(ctx context.Context) (entitlement.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx)
	ret0, _ := ret[0].(entitlement.Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockEntitlementServiceMockRecorder) Get(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockEntitlementService)(nil).Get), ctx)
}
