// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/opcotech/elemo/internal/service (interfaces: PluginService)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_plugin_gen.go -package=mocksvc . PluginService
//

// Package mocksvc is a generated GoMock package.
package mocksvc

import (
	context "context"
	json "encoding/json"
	reflect "reflect"

	model "github.com/opcotech/elemo/internal/model"
	plugin "github.com/opcotech/elemo/internal/plugin"
	repository "github.com/opcotech/elemo/internal/repository"
	service "github.com/opcotech/elemo/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockPluginService is a mock of PluginService interface.
type MockPluginService struct {
	ctrl     *gomock.Controller
	recorder *MockPluginServiceMockRecorder
	isgomock struct{}
}

// MockPluginServiceMockRecorder is the mock recorder for MockPluginService.
type MockPluginServiceMockRecorder struct {
	mock *MockPluginService
}

// NewMockPluginService creates a new mock instance.
func NewMockPluginService(ctrl *gomock.Controller) *MockPluginService {
	mock := &MockPluginService{ctrl: ctrl}
	mock.recorder = &MockPluginServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPluginService) EXPECT() *MockPluginServiceMockRecorder {
	return m.recorder
}

// AssetPath mocks base method.
func (m *MockPluginService) AssetPath(ctx context.Context, pluginID, version, rel string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssetPath", ctx, pluginID, version, rel)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssetPath indicates an expected call of AssetPath.
func (mr *MockPluginServiceMockRecorder) AssetPath(ctx, pluginID, version, rel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssetPath", reflect.TypeOf((*MockPluginService)(nil).AssetPath), ctx, pluginID, version, rel)
}

// CreateNode mocks base method.
func (m *MockPluginService) CreateNode(ctx context.Context, pluginID string, opts service.CreateExtensionNodeOpts) (*model.Extension, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNode", ctx, pluginID, opts)
	ret0, _ := ret[0].(*model.Extension)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNode indicates an expected call of CreateNode.
func (mr *MockPluginServiceMockRecorder) CreateNode(ctx, pluginID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNode", reflect.TypeOf((*MockPluginService)(nil).CreateNode), ctx, pluginID, opts)
}

// CreateRelation mocks base method.
func (m *MockPluginService) CreateRelation(ctx context.Context, pluginID string, opts service.CreateExtensionRelationOpts) (*model.ExtensionRelation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRelation", ctx, pluginID, opts)
	ret0, _ := ret[0].(*model.ExtensionRelation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRelation indicates an expected call of CreateRelation.
func (mr *MockPluginServiceMockRecorder) CreateRelation(ctx, pluginID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRelation", reflect.TypeOf((*MockPluginService)(nil).CreateRelation), ctx, pluginID, opts)
}

// DeleteNode mocks base method.
func (m *MockPluginService) DeleteNode(ctx context.Context, pluginID string, id model.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNode", ctx, pluginID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNode indicates an expected call of DeleteNode.
func (mr *MockPluginServiceMockRecorder) DeleteNode(ctx, pluginID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNode", reflect.TypeOf((*MockPluginService)(nil).DeleteNode), ctx, pluginID, id)
}

// DeleteRelation mocks base method.
func (m *MockPluginService) DeleteRelation(ctx context.Context, pluginID, relID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRelation", ctx, pluginID, relID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRelation indicates an expected call of DeleteRelation.
func (mr *MockPluginServiceMockRecorder) DeleteRelation(ctx, pluginID, relID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRelation", reflect.TypeOf((*MockPluginService)(nil).DeleteRelation), ctx, pluginID, relID)
}

// Disable mocks base method.
func (m *MockPluginService) Disable(ctx context.Context, pluginID string, scope model.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disable", ctx, pluginID, scope)
	ret0, _ := ret[0].(error)
	return ret0
}

// Disable indicates an expected call of Disable.
func (mr *MockPluginServiceMockRecorder) Disable(ctx, pluginID, scope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disable", reflect.TypeOf((*MockPluginService)(nil).Disable), ctx, pluginID, scope)
}

// Enable mocks base method.
func (m *MockPluginService) Enable(ctx context.Context, pluginID string, scope model.ID, config json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enable", ctx, pluginID, scope, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enable indicates an expected call of Enable.
func (mr *MockPluginServiceMockRecorder) Enable(ctx, pluginID, scope, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enable", reflect.TypeOf((*MockPluginService)(nil).Enable), ctx, pluginID, scope, config)
}

// Get mocks base method.
func (m *MockPluginService) Get(ctx context.Context, pluginID string) (*model.PluginInstallation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, pluginID)
	ret0, _ := ret[0].(*model.PluginInstallation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPluginServiceMockRecorder) Get(ctx, pluginID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPluginService)(nil).Get), ctx, pluginID)
}

// GetConfig mocks base method.
func (m *MockPluginService) GetConfig(ctx context.Context, pluginID string, scope model.ID) (json.RawMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig", ctx, pluginID, scope)
	ret0, _ := ret[0].(json.RawMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockPluginServiceMockRecorder) GetConfig(ctx, pluginID, scope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockPluginService)(nil).GetConfig), ctx, pluginID, scope)
}

// GetManagedConfig mocks base method.
func (m *MockPluginService) GetManagedConfig(ctx context.Context, pluginID string, scope model.ID) (json.RawMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetManagedConfig", ctx, pluginID, scope)
	ret0, _ := ret[0].(json.RawMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetManagedConfig indicates an expected call of GetManagedConfig.
func (mr *MockPluginServiceMockRecorder) GetManagedConfig(ctx, pluginID, scope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetManagedConfig", reflect.TypeOf((*MockPluginService)(nil).GetManagedConfig), ctx, pluginID, scope)
}

// GetNode mocks base method.
func (m *MockPluginService) GetNode(ctx context.Context, pluginID string, id model.ID, ownerPluginID string) (*model.Extension, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNode", ctx, pluginID, id, ownerPluginID)
	ret0, _ := ret[0].(*model.Extension)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNode indicates an expected call of GetNode.
func (mr *MockPluginServiceMockRecorder) GetNode(ctx, pluginID, id, ownerPluginID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNode", reflect.TypeOf((*MockPluginService)(nil).GetNode), ctx, pluginID, id, ownerPluginID)
}

// Install mocks base method.
func (m *MockPluginService) Install(ctx context.Context, zip []byte) (*model.PluginInstallation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Install", ctx, zip)
	ret0, _ := ret[0].(*model.PluginInstallation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Install indicates an expected call of Install.
func (mr *MockPluginServiceMockRecorder) Install(ctx, zip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Install", reflect.TypeOf((*MockPluginService)(nil).Install), ctx, zip)
}

// Invoke mocks base method.
func (m *MockPluginService) Invoke(ctx context.Context, pluginID string, req plugin.InvokeRequest) (plugin.InvokeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Invoke", ctx, pluginID, req)
	ret0, _ := ret[0].(plugin.InvokeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Invoke indicates an expected call of Invoke.
func (mr *MockPluginServiceMockRecorder) Invoke(ctx, pluginID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invoke", reflect.TypeOf((*MockPluginService)(nil).Invoke), ctx, pluginID, req)
}

// List mocks base method.
func (m *MockPluginService) List(ctx context.Context) ([]*model.PluginInstallation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*model.PluginInstallation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPluginServiceMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPluginService)(nil).List), ctx)
}

// ListFrontend mocks base method.
func (m *MockPluginService) ListFrontend(ctx context.Context, scope model.ID) ([]service.FrontendPlugin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFrontend", ctx, scope)
	ret0, _ := ret[0].([]service.FrontendPlugin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFrontend indicates an expected call of ListFrontend.
func (mr *MockPluginServiceMockRecorder) ListFrontend(ctx, scope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFrontend", reflect.TypeOf((*MockPluginService)(nil).ListFrontend), ctx, scope)
}

// ListManaged mocks base method.
func (m *MockPluginService) ListManaged(ctx context.Context, scope model.ID) ([]service.PluginListItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListManaged", ctx, scope)
	ret0, _ := ret[0].([]service.PluginListItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListManaged indicates an expected call of ListManaged.
func (mr *MockPluginServiceMockRecorder) ListManaged(ctx, scope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListManaged", reflect.TypeOf((*MockPluginService)(nil).ListManaged), ctx, scope)
}

// ListNodes mocks base method.
func (m *MockPluginService) ListNodes(ctx context.Context, pluginID string, opts service.ListExtensionNodeOpts) (repository.Page[*model.Extension], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNodes", ctx, pluginID, opts)
	ret0, _ := ret[0].(repository.Page[*model.Extension])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNodes indicates an expected call of ListNodes.
func (mr *MockPluginServiceMockRecorder) ListNodes(ctx, pluginID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNodes", reflect.TypeOf((*MockPluginService)(nil).ListNodes), ctx, pluginID, opts)
}

// ListRelations mocks base method.
func (m *MockPluginService) ListRelations(ctx context.Context, pluginID string, opts service.ListExtensionRelationOpts) (repository.Page[*model.ExtensionRelation], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRelations", ctx, pluginID, opts)
	ret0, _ := ret[0].(repository.Page[*model.ExtensionRelation])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRelations indicates an expected call of ListRelations.
func (mr *MockPluginServiceMockRecorder) ListRelations(ctx, pluginID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRelations", reflect.TypeOf((*MockPluginService)(nil).ListRelations), ctx, pluginID, opts)
}

// MoveNode mocks base method.
func (m *MockPluginService) MoveNode(ctx context.Context, pluginID string, id, parent model.ID) (*model.Extension, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveNode", ctx, pluginID, id, parent)
	ret0, _ := ret[0].(*model.Extension)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MoveNode indicates an expected call of MoveNode.
func (mr *MockPluginServiceMockRecorder) MoveNode(ctx, pluginID, id, parent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveNode", reflect.TypeOf((*MockPluginService)(nil).MoveNode), ctx, pluginID, id, parent)
}

// Restore mocks base method.
func (m *MockPluginService) Restore(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restore", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Restore indicates an expected call of Restore.
func (mr *MockPluginServiceMockRecorder) Restore(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockPluginService)(nil).Restore), ctx)
}

// SetConfig mocks base method.
func (m *MockPluginService) SetConfig(ctx context.Context, pluginID string, scope model.ID, config json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetConfig", ctx, pluginID, scope, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetConfig indicates an expected call of SetConfig.
func (mr *MockPluginServiceMockRecorder) SetConfig(ctx, pluginID, scope, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetConfig", reflect.TypeOf((*MockPluginService)(nil).SetConfig), ctx, pluginID, scope, config)
}

// Uninstall mocks base method.
func (m *MockPluginService) Uninstall(ctx context.Context, pluginID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Uninstall", ctx, pluginID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Uninstall indicates an expected call of Uninstall.
func (mr *MockPluginServiceMockRecorder) Uninstall(ctx, pluginID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Uninstall", reflect.TypeOf((*MockPluginService)(nil).Uninstall), ctx, pluginID)
}

// UpdateNode mocks base method.
func (m *MockPluginService) UpdateNode(ctx context.Context, pluginID string, id model.ID, properties map[string]any) (*model.Extension, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNode", ctx, pluginID, id, properties)
	ret0, _ := ret[0].(*model.Extension)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNode indicates an expected call of UpdateNode.
func (mr *MockPluginServiceMockRecorder) UpdateNode(ctx, pluginID, id, properties any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNode", reflect.TypeOf((*MockPluginService)(nil).UpdateNode), ctx, pluginID, id, properties)
}

// Upgrade mocks base method.
func (m *MockPluginService) Upgrade(ctx context.Context, pluginID string, zip []byte) (*model.PluginInstallation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upgrade", ctx, pluginID, zip)
	ret0, _ := ret[0].(*model.PluginInstallation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upgrade indicates an expected call of Upgrade.
func (mr *MockPluginServiceMockRecorder) Upgrade(ctx, pluginID, zip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upgrade", reflect.TypeOf((*MockPluginService)(nil).Upgrade), ctx, pluginID, zip)
}
