// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/opcotech/elemo/internal/service (interfaces: IssueService)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_issue_gen.go -package=mocksvc . IssueService
//

// Package mocksvc is a generated GoMock package.
package mocksvc

import (
	context "context"
	reflect "reflect"

	model "github.com/opcotech/elemo/internal/model"
	service "github.com/opcotech/elemo/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockIssueService is a mock of IssueService interface.
type MockIssueService struct {
	ctrl     *gomock.Controller
	recorder *MockIssueServiceMockRecorder
	isgomock struct{}
}

// MockIssueServiceMockRecorder is the mock recorder for MockIssueService.
type MockIssueServiceMockRecorder struct {
	mock *MockIssueService
}

// NewMockIssueService creates a new mock instance.
func NewMockIssueService(ctrl *gomock.Controller) *MockIssueService {
	mock := &MockIssueService{ctrl: ctrl}
	mock.recorder = &MockIssueServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIssueService) EXPECT() *MockIssueServiceMockRecorder {
	return m.recorder
}

// AddRelation mocks base method.
func (m *MockIssueService) AddRelation(ctx context.Context, issueID, relatedID model.ID, kind model.IssueRelationKind) (*service.IssueRelation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRelation", ctx, issueID, relatedID, kind)
	ret0, _ := ret[0].(*service.IssueRelation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddRelation indicates an expected call of AddRelation.
func (mr *MockIssueServiceMockRecorder) AddRelation(ctx, issueID, relatedID, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRelation", reflect.TypeOf((*MockIssueService)(nil).AddRelation), ctx, issueID, relatedID, kind)
}

// Create mocks base method.
func (m *MockIssueService) Create(ctx context.Context, projectID model.ID, opts service.CreateIssueOpts) (*service.Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, projectID, opts)
	ret0, _ := ret[0].(*service.Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIssueServiceMockRecorder) Create(ctx, projectID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIssueService)(nil).Create), ctx, projectID, opts)
}

// Delete mocks base method.
func (m *MockIssueService) Delete(ctx context.Context, id model.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIssueServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIssueService)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockIssueService) Get(ctx context.Context, id model.ID) (*service.Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*service.Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIssueServiceMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIssueService)(nil).Get), ctx, id)
}

// GetByKey mocks base method.
func (m *MockIssueService) GetByKey(ctx context.Context, namespaceID model.ID, key string) (*service.Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByKey", ctx, namespaceID, key)
	ret0, _ := ret[0].(*service.Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByKey indicates an expected call of GetByKey.
func (mr *MockIssueServiceMockRecorder) GetByKey(ctx, namespaceID, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByKey", reflect.TypeOf((*MockIssueService)(nil).GetByKey), ctx, namespaceID, key)
}

// List mocks base method.
func (m *MockIssueService) List(ctx context.Context, projectID model.ID, page service.CursorPage, opts service.IssueListOptions) (service.Page[*service.PartialIssue], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, projectID, page, opts)
	ret0, _ := ret[0].(service.Page[*service.PartialIssue])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIssueServiceMockRecorder) List(ctx, projectID, page, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIssueService)(nil).List), ctx, projectID, page, opts)
}

// ListByNamespace mocks base method.
func (m *MockIssueService) ListByNamespace(ctx context.Context, namespaceID model.ID, page service.CursorPage, opts service.IssueListOptions) (service.Page[*service.PartialIssue], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByNamespace", ctx, namespaceID, page, opts)
	ret0, _ := ret[0].(service.Page[*service.PartialIssue])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByNamespace indicates an expected call of ListByNamespace.
func (mr *MockIssueServiceMockRecorder) ListByNamespace(ctx, namespaceID, page, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByNamespace", reflect.TypeOf((*MockIssueService)(nil).ListByNamespace), ctx, namespaceID, page, opts)
}

// ListByUser mocks base method.
func (m *MockIssueService) ListByUser(ctx context.Context, userID model.ID, page service.CursorPage, opts service.IssueListOptions) (service.Page[*service.PartialIssue], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID, page, opts)
	ret0, _ := ret[0].(service.Page[*service.PartialIssue])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockIssueServiceMockRecorder) ListByUser(ctx, userID, page, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockIssueService)(nil).ListByUser), ctx, userID, page, opts)
}

// ListRelations mocks base method.
func (m *MockIssueService) ListRelations(ctx context.Context, issueID model.ID, page service.CursorPage) (service.Page[*service.IssueRelation], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRelations", ctx, issueID, page)
	ret0, _ := ret[0].(service.Page[*service.IssueRelation])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRelations indicates an expected call of ListRelations.
func (mr *MockIssueServiceMockRecorder) ListRelations(ctx, issueID, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRelations", reflect.TypeOf((*MockIssueService)(nil).ListRelations), ctx, issueID, page)
}

// RemoveRelation mocks base method.
func (m *MockIssueService) RemoveRelation(ctx context.Context, issueID, relationID model.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveRelation", ctx, issueID, relationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveRelation indicates an expected call of RemoveRelation.
func (mr *MockIssueServiceMockRecorder) RemoveRelation(ctx, issueID, relationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRelation", reflect.TypeOf((*MockIssueService)(nil).RemoveRelation), ctx, issueID, relationID)
}

// Update mocks base method.
func (m *MockIssueService) Update(ctx context.Context, id model.ID, opts service.UpdateIssueOpts) (*service.Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, opts)
	ret0, _ := ret[0].(*service.Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIssueServiceMockRecorder) Update(ctx, id, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIssueService)(nil).Update), ctx, id, opts)
}

// UpdateRelation mocks base method.
func (m *MockIssueService) UpdateRelation(ctx context.Context, issueID, relationID model.ID, kind model.IssueRelationKind) (*service.IssueRelation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRelation", ctx, issueID, relationID, kind)
	ret0, _ := ret[0].(*service.IssueRelation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRelation indicates an expected call of UpdateRelation.
func (mr *MockIssueServiceMockRecorder) UpdateRelation(ctx, issueID, relationID, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRelation", reflect.TypeOf((*MockIssueService)(nil).UpdateRelation), ctx, issueID, relationID, kind)
}
