// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/opcotech/elemo/internal/service (interfaces: PermissionService)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_permission_gen.go -package=mocksvc . PermissionService
//

// Package mocksvc is a generated GoMock package.
package mocksvc

import (
	context "context"
	reflect "reflect"

	model "github.com/opcotech/elemo/internal/model"
	repository "github.com/opcotech/elemo/internal/repository"
	service "github.com/opcotech/elemo/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockPermissionService is a mock of PermissionService interface.
type MockPermissionService struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionServiceMockRecorder
	isgomock struct{}
}

// MockPermissionServiceMockRecorder is the mock recorder for MockPermissionService.
type MockPermissionServiceMockRecorder struct {
	mock *MockPermissionService
}

// NewMockPermissionService creates a new mock instance.
func NewMockPermissionService(ctrl *gomock.Controller) *MockPermissionService {
	mock := &MockPermissionService{ctrl: ctrl}
	mock.recorder = &MockPermissionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionService) EXPECT() *MockPermissionServiceMockRecorder {
	return m.recorder
}

// BootstrapCreator mocks base method.
func (m *MockPermissionService) BootstrapCreator(ctx context.Context, creator, resource model.ID, actions []model.Action) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BootstrapCreator", ctx, creator, resource, actions)
	ret0, _ := ret[0].(error)
	return ret0
}

// BootstrapCreator indicates an expected call of BootstrapCreator.
func (mr *MockPermissionServiceMockRecorder) BootstrapCreator(ctx, creator, resource, actions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BootstrapCreator", reflect.TypeOf((*MockPermissionService)(nil).BootstrapCreator), ctx, creator, resource, actions)
}

// BumpGeneration mocks base method.
func (m *MockPermissionService) BumpGeneration(ctx context.Context, principal model.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BumpGeneration", ctx, principal)
	ret0, _ := ret[0].(error)
	return ret0
}

// BumpGeneration indicates an expected call of BumpGeneration.
func (mr *MockPermissionServiceMockRecorder) BumpGeneration(ctx, principal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BumpGeneration", reflect.TypeOf((*MockPermissionService)(nil).BumpGeneration), ctx, principal)
}

// Create mocks base method.
func (m *MockPermissionService) Create(ctx context.Context, opts service.CreateGrantOpts) (*service.Grant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, opts)
	ret0, _ := ret[0].(*service.Grant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPermissionServiceMockRecorder) Create(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPermissionService)(nil).Create), ctx, opts)
}

// CtxUserCreate mocks base method.
func (m *MockPermissionService) CtxUserCreate(ctx context.Context, opts service.CreateGrantOpts) (*service.Grant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CtxUserCreate", ctx, opts)
	ret0, _ := ret[0].(*service.Grant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CtxUserCreate indicates an expected call of CtxUserCreate.
func (mr *MockPermissionServiceMockRecorder) CtxUserCreate(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CtxUserCreate", reflect.TypeOf((*MockPermissionService)(nil).CtxUserCreate), ctx, opts)
}

// CtxUserDelete mocks base method.
func (m *MockPermissionService) CtxUserDelete(ctx context.Context, id model.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CtxUserDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// CtxUserDelete indicates an expected call of CtxUserDelete.
func (mr *MockPermissionServiceMockRecorder) CtxUserDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CtxUserDelete", reflect.TypeOf((*MockPermissionService)(nil).CtxUserDelete), ctx, id)
}

// CtxUserEffectiveActions mocks base method.
func (m *MockPermissionService) CtxUserEffectiveActions(ctx context.Context, resource model.ID) ([]model.Action, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CtxUserEffectiveActions", ctx, resource)
	ret0, _ := ret[0].([]model.Action)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CtxUserEffectiveActions indicates an expected call of CtxUserEffectiveActions.
func (mr *MockPermissionServiceMockRecorder) CtxUserEffectiveActions(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CtxUserEffectiveActions", reflect.TypeOf((*MockPermissionService)(nil).CtxUserEffectiveActions), ctx, resource)
}

// CtxUserHas mocks base method.
func (m *MockPermissionService) CtxUserHas(ctx context.Context, resource model.ID, action model.Action) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CtxUserHas", ctx, resource, action)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CtxUserHas indicates an expected call of CtxUserHas.
func (mr *MockPermissionServiceMockRecorder) CtxUserHas(ctx, resource, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CtxUserHas", reflect.TypeOf((*MockPermissionService)(nil).CtxUserHas), ctx, resource, action)
}

// CtxUserListGrantScopes mocks base method.
func (m *MockPermissionService) CtxUserListGrantScopes(ctx context.Context, action model.Action) ([]model.ID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CtxUserListGrantScopes", ctx, action)
	ret0, _ := ret[0].([]model.ID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CtxUserListGrantScopes indicates an expected call of CtxUserListGrantScopes.
func (mr *MockPermissionServiceMockRecorder) CtxUserListGrantScopes(ctx, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CtxUserListGrantScopes", reflect.TypeOf((*MockPermissionService)(nil).CtxUserListGrantScopes), ctx, action)
}

// Delete mocks base method.
func (m *MockPermissionService) Delete(ctx context.Context, id model.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPermissionServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPermissionService)(nil).Delete), ctx, id)
}

// EffectiveActions mocks base method.
func (m *MockPermissionService) EffectiveActions(ctx context.Context, actor, resource model.ID) ([]model.Action, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EffectiveActions", ctx, actor, resource)
	ret0, _ := ret[0].([]model.Action)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EffectiveActions indicates an expected call of EffectiveActions.
func (mr *MockPermissionServiceMockRecorder) EffectiveActions(ctx, actor, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EffectiveActions", reflect.TypeOf((*MockPermissionService)(nil).EffectiveActions), ctx, actor, resource)
}

// Explain mocks base method.
func (m *MockPermissionService) Explain(ctx context.Context, actor, resource model.ID, action model.Action) (*repository.Decision, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Explain", ctx, actor, resource, action)
	ret0, _ := ret[0].(*repository.Decision)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Explain indicates an expected call of Explain.
func (mr *MockPermissionServiceMockRecorder) Explain(ctx, actor, resource, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Explain", reflect.TypeOf((*MockPermissionService)(nil).Explain), ctx, actor, resource, action)
}

// Get mocks base method.
func (m *MockPermissionService) Get(ctx context.Context, id model.ID) (*service.Grant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*service.Grant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPermissionServiceMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPermissionService)(nil).Get), ctx, id)
}

// GrantRole mocks base method.
func (m *MockPermissionService) GrantRole(ctx context.Context, principal, scope, roleID model.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GrantRole", ctx, principal, scope, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// GrantRole indicates an expected call of GrantRole.
func (mr *MockPermissionServiceMockRecorder) GrantRole(ctx, principal, scope, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantRole", reflect.TypeOf((*MockPermissionService)(nil).GrantRole), ctx, principal, scope, roleID)
}

// Has mocks base method.
func (m *MockPermissionService) Has(ctx context.Context, actor, resource model.ID, action model.Action) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Has", ctx, actor, resource, action)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Has indicates an expected call of Has.
func (mr *MockPermissionServiceMockRecorder) Has(ctx, actor, resource, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Has", reflect.TypeOf((*MockPermissionService)(nil).Has), ctx, actor, resource, action)
}

// LinkInScopeOf mocks base method.
func (m *MockPermissionService) LinkInScopeOf(ctx context.Context, child, parent model.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkInScopeOf", ctx, child, parent)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkInScopeOf indicates an expected call of LinkInScopeOf.
func (mr *MockPermissionServiceMockRecorder) LinkInScopeOf(ctx, child, parent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkInScopeOf", reflect.TypeOf((*MockPermissionService)(nil).LinkInScopeOf), ctx, child, parent)
}

// ListByPrincipal mocks base method.
func (m *MockPermissionService) ListByPrincipal(ctx context.Context, principal model.ID) ([]*service.Grant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByPrincipal", ctx, principal)
	ret0, _ := ret[0].([]*service.Grant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByPrincipal indicates an expected call of ListByPrincipal.
func (mr *MockPermissionServiceMockRecorder) ListByPrincipal(ctx, principal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByPrincipal", reflect.TypeOf((*MockPermissionService)(nil).ListByPrincipal), ctx, principal)
}

// ListByScope mocks base method.
func (m *MockPermissionService) ListByScope(ctx context.Context, scope model.ID) ([]*service.Grant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByScope", ctx, scope)
	ret0, _ := ret[0].([]*service.Grant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByScope indicates an expected call of ListByScope.
func (mr *MockPermissionServiceMockRecorder) ListByScope(ctx, scope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByScope", reflect.TypeOf((*MockPermissionService)(nil).ListByScope), ctx, scope)
}

// ListGrantScopes mocks base method.
func (m *MockPermissionService) ListGrantScopes(ctx context.Context, actor model.ID, action model.Action) ([]model.ID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGrantScopes", ctx, actor, action)
	ret0, _ := ret[0].([]model.ID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGrantScopes indicates an expected call of ListGrantScopes.
func (mr *MockPermissionServiceMockRecorder) ListGrantScopes(ctx, actor, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGrantScopes", reflect.TypeOf((*MockPermissionService)(nil).ListGrantScopes), ctx, actor, action)
}

// ListScopeAncestry mocks base method.
func (m *MockPermissionService) ListScopeAncestry(ctx context.Context, resource model.ID) ([]model.ID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListScopeAncestry", ctx, resource)
	ret0, _ := ret[0].([]model.ID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListScopeAncestry indicates an expected call of ListScopeAncestry.
func (mr *MockPermissionServiceMockRecorder) ListScopeAncestry(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListScopeAncestry", reflect.TypeOf((*MockPermissionService)(nil).ListScopeAncestry), ctx, resource)
}
