// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/opcotech/elemo/internal/service (interfaces: RoleService)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_role_gen.go -package=mocksvc . RoleService
//

// Package mocksvc is a generated GoMock package.
package mocksvc

import (
	context "context"
	reflect "reflect"

	model "github.com/opcotech/elemo/internal/model"
	service "github.com/opcotech/elemo/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockRoleService is a mock of RoleService interface.
type MockRoleService struct {
	ctrl     *gomock.Controller
	recorder *MockRoleServiceMockRecorder
	isgomock struct{}
}

// MockRoleServiceMockRecorder is the mock recorder for MockRoleService.
type MockRoleServiceMockRecorder struct {
	mock *MockRoleService
}

// NewMockRoleService creates a new mock instance.
func NewMockRoleService(ctrl *gomock.Controller) *MockRoleService {
	mock := &MockRoleService{ctrl: ctrl}
	mock.recorder = &MockRoleServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleService) EXPECT() *MockRoleServiceMockRecorder {
	return m.recorder
}

// AddMember mocks base method.
func (m *MockRoleService) AddMember(ctx context.Context, roleID, memberID, belongsToID model.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMember", ctx, roleID, memberID, belongsToID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMember indicates an expected call of AddMember.
func (mr *MockRoleServiceMockRecorder) AddMember(ctx, roleID, memberID, belongsToID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockRoleService)(nil).AddMember), ctx, roleID, memberID, belongsToID)
}

// Create mocks base method.
func (m *MockRoleService) Create(ctx context.Context, owner, belongsTo model.ID, opts service.CreateRoleOpts) (*service.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, owner, belongsTo, opts)
	ret0, _ := ret[0].(*service.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRoleServiceMockRecorder) Create(ctx, owner, belongsTo, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRoleService)(nil).Create), ctx, owner, belongsTo, opts)
}

// Delete mocks base method.
func (m *MockRoleService) Delete(ctx context.Context, id, belongsTo model.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, belongsTo)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRoleServiceMockRecorder) Delete(ctx, id, belongsTo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRoleService)(nil).Delete), ctx, id, belongsTo)
}

// Get mocks base method.
func (m *MockRoleService) Get(ctx context.Context, id, belongsTo model.ID) (*service.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id, belongsTo)
	ret0, _ := ret[0].(*service.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRoleServiceMockRecorder) Get(ctx, id, belongsTo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRoleService)(nil).Get), ctx, id, belongsTo)
}

// ListBelongsTo mocks base method.
func (m *MockRoleService) ListBelongsTo(ctx context.Context, belongsTo model.ID, page service.CursorPage) (service.Page[*service.Role], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBelongsTo", ctx, belongsTo, page)
	ret0, _ := ret[0].(service.Page[*service.Role])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBelongsTo indicates an expected call of ListBelongsTo.
func (mr *MockRoleServiceMockRecorder) ListBelongsTo(ctx, belongsTo, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBelongsTo", reflect.TypeOf((*MockRoleService)(nil).ListBelongsTo), ctx, belongsTo, page)
}

// ListMembers mocks base method.
func (m *MockRoleService) ListMembers(ctx context.Context, id, belongsTo model.ID, page service.CursorPage) (service.Page[*service.User], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMembers", ctx, id, belongsTo, page)
	ret0, _ := ret[0].(service.Page[*service.User])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMembers indicates an expected call of ListMembers.
func (mr *MockRoleServiceMockRecorder) ListMembers(ctx, id, belongsTo, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMembers", reflect.TypeOf((*MockRoleService)(nil).ListMembers), ctx, id, belongsTo, page)
}

// RemoveMember mocks base method.
func (m *MockRoleService) RemoveMember(ctx context.Context, roleID, memberID, belongsToID model.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", ctx, roleID, memberID, belongsToID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockRoleServiceMockRecorder) RemoveMember(ctx, roleID, memberID, belongsToID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockRoleService)(nil).RemoveMember), ctx, roleID, memberID, belongsToID)
}

// Update mocks base method.
func (m *MockRoleService) Update(ctx context.Context, id, belongsTo model.ID, opts service.UpdateRoleOpts) (*service.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, belongsTo, opts)
	ret0, _ := ret[0].(*service.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRoleServiceMockRecorder) Update(ctx, id, belongsTo, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRoleService)(nil).Update), ctx, id, belongsTo, opts)
}
