// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/opcotech/elemo/internal/service (interfaces: NamespaceService)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_namespace_gen.go -package=mocksvc . NamespaceService
//

// Package mocksvc is a generated GoMock package.
package mocksvc

import (
	context "context"
	reflect "reflect"

	model "github.com/opcotech/elemo/internal/model"
	service "github.com/opcotech/elemo/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockNamespaceService is a mock of NamespaceService interface.
type MockNamespaceService struct {
	ctrl     *gomock.Controller
	recorder *MockNamespaceServiceMockRecorder
	isgomock struct{}
}

// MockNamespaceServiceMockRecorder is the mock recorder for MockNamespaceService.
type MockNamespaceServiceMockRecorder struct {
	mock *MockNamespaceService
}

// NewMockNamespaceService creates a new mock instance.
func NewMockNamespaceService(ctrl *gomock.Controller) *MockNamespaceService {
	mock := &MockNamespaceService{ctrl: ctrl}
	mock.recorder = &MockNamespaceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNamespaceService) EXPECT() *MockNamespaceServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNamespaceService) Create(ctx context.Context, orgID model.ID, opts service.CreateNamespaceOpts) (*service.Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, orgID, opts)
	ret0, _ := ret[0].(*service.Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockNamespaceServiceMockRecorder) Create(ctx, orgID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNamespaceService)(nil).Create), ctx, orgID, opts)
}

// Delete mocks base method.
func (m *MockNamespaceService) Delete(ctx context.Context, id model.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockNamespaceServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNamespaceService)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockNamespaceService) Get(ctx context.Context, id model.ID) (*service.Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*service.Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockNamespaceServiceMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockNamespaceService)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockNamespaceService) List(ctx context.Context, orgID model.ID, page service.CursorPage) (service.Page[*service.Namespace], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, orgID, page)
	ret0, _ := ret[0].(service.Page[*service.Namespace])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockNamespaceServiceMockRecorder) List(ctx, orgID, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockNamespaceService)(nil).List), ctx, orgID, page)
}

// ListAccessible mocks base method.
func (m *MockNamespaceService) ListAccessible(ctx context.Context, page service.CursorPage) (service.Page[*service.AccessibleNamespace], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccessible", ctx, page)
	ret0, _ := ret[0].(service.Page[*service.AccessibleNamespace])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccessible indicates an expected call of ListAccessible.
func (mr *MockNamespaceServiceMockRecorder) ListAccessible(ctx, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccessible", reflect.TypeOf((*MockNamespaceService)(nil).ListAccessible), ctx, page)
}

// Update mocks base method.
func (m *MockNamespaceService) Update(ctx context.Context, id model.ID, opts service.UpdateNamespaceOpts) (*service.Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, opts)
	ret0, _ := ret[0].(*service.Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockNamespaceServiceMockRecorder) Update(ctx, id, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockNamespaceService)(nil).Update), ctx, id, opts)
}
