name: elemo

volumes:
  neo4j_data: { }
  pg_data: { }
  localstack_data: { }

networks:
  default:
    name: elemo-network

services:
  redis:
    image: redis:8.0
    container_name: elemo-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 3

  neo4j:
    image: neo4j:5.26
    container_name: elemo-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
      - "2004:2004"
    volumes:
      - neo4j_data:/data
      - ./neo4j:/conf
    environment:
      - NEO4J_AUTH=neo4j/neo4jsecret
    healthcheck:
      test:
        [ "CMD", "cypher-shell", "-u", "neo4j", "-p", "neo4jsecret", "match (n) return count(n)" ]
      interval: 10s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:17.5
    container_name: elemo-postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=elemo
      - POSTGRES_PASSWORD=pgsecret
      - POSTGRES_DB=elemo
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "elemo" ]
      interval: 5s
      timeout: 5s
      retries: 3

  smtp:
    image: axllent/mailpit:latest
    container_name: elemo-smtp
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  localstack:
    image: localstack/localstack:latest
    container_name: elemo-localstack
    volumes:
      - localstack_data:/store
      - /var/run/docker.sock:/var/run/docker.sock
      - ./localstack/boot.sh:/etc/localstack/init/boot.d/boot.sh
      - ./localstack/ready.sh:/etc/localstack/init/ready.d/ready.sh
      - ./localstack/shutdown.sh:/etc/localstack/init/shutdown.d/shutdown.sh
    environment:
      - DOCKER_SOCK=/var/run/docker.sock
      - PERSISTENCE=1
      - DEBUG=1
      - SERVICES=s3:4566
      - EXTRA_CORS_ALLOWED_ORIGINS=*
      - EXTRA_CORS_ALLOWED_HEADERS=*
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=aws-access-key
      - AWS_SECRET_ACCESS_KEY=aws-secret-key
    healthcheck:
      test: [ "CMD", "bash", "-c", "awslocal s3api head-bucket --bucket elemo" ]
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - "4566:4566"
    labels:
      - "traefik.enable=false"

  elemo-server:
    image: elemo-server
    container_name: elemo-server
    build:
      context: ../../
      dockerfile: build/package/Dockerfile
    entrypoint:
      - bin/elemo
      - start
      - server
    security_opt:
      - seccomp:unconfined
    depends_on:
      redis:
        condition: service_healthy
      neo4j:
        condition: service_healthy
      postgres:
        condition: service_healthy
      smtp:
        condition: service_started
    environment:
      ELEMO_CONFIG: configs/development/config.gen.yml
    ports:
      - "35478:35478"
      - "35479:35479"

  elemo-worker:
    image: elemo-server
    container_name: elemo-worker
    build:
      context: ../../
      dockerfile: build/package/Dockerfile
    entrypoint:
      - bin/elemo
      - start
      - worker
    security_opt:
      - seccomp:unconfined
    depends_on:
      redis:
        condition: service_healthy
      neo4j:
        condition: service_healthy
      postgres:
        condition: service_healthy
      elemo-server:
        condition: service_started
      smtp:
        condition: service_started
    environment:
      ELEMO_CONFIG: configs/development/config.gen.yml
    ports:
      - "35480:35480"
