// Code generated by MockGen. DO NOT EDIT.
// Source: io (interfaces: WriteCloser)
//
// Generated by this command:
//
//	mockgen -destination=../../testutil/mock/io_gen.go -package=mock -mock_names WriteCloser=WriteCloser io WriteCloser
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// WriteCloser is a mock of WriteCloser interface.
type WriteCloser struct {
	ctrl     *gomock.Controller
	recorder *WriteCloserMockRecorder
	isgomock struct{}
}

// WriteCloserMockRecorder is the mock recorder for WriteCloser.
type WriteCloserMockRecorder struct {
	mock *WriteCloser
}

// NewWriteCloser creates a new mock instance.
func NewWriteCloser(ctrl *gomock.Controller) *WriteCloser {
	mock := &WriteCloser{ctrl: ctrl}
	mock.recorder = &WriteCloserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *WriteCloser) EXPECT() *WriteCloserMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *WriteCloser) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *WriteCloserMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*WriteCloser)(nil).Close))
}

// Write mocks base method.
func (m *WriteCloser) Write(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write.
func (mr *WriteCloserMockRecorder) Write(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*WriteCloser)(nil).Write), p)
}
