// Code generated by MockGen. DO NOT EDIT.
// Source: smtp.go
//
// Generated by this command:
//
//	mockgen -source=smtp.go -destination=../../testutil/mock/smtp_gen.go -package=mock -mock_names WrappedClient=WrappedClient
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomail "github.com/Shopify/gomail"
	gomock "go.uber.org/mock/gomock"
)

// WrappedClient is a mock of WrappedClient interface.
type WrappedClient struct {
	ctrl     *gomock.Controller
	recorder *WrappedClientMockRecorder
	isgomock struct{}
}

// WrappedClientMockRecorder is the mock recorder for WrappedClient.
type WrappedClientMockRecorder struct {
	mock *WrappedClient
}

// NewWrappedClient creates a new mock instance.
func NewWrappedClient(ctrl *gomock.Controller) *WrappedClient {
	mock := &WrappedClient{ctrl: ctrl}
	mock.recorder = &WrappedClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *WrappedClient) EXPECT() *WrappedClientMockRecorder {
	return m.recorder
}

// DialAndSend mocks base method.
func (m *WrappedClient) DialAndSend(messages ...*gomail.Message) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range messages {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DialAndSend", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DialAndSend indicates an expected call of DialAndSend.
func (mr *WrappedClientMockRecorder) DialAndSend(messages ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DialAndSend", reflect.TypeOf((*WrappedClient)(nil).DialAndSend), messages...)
}
