// Code generated by "enumer -type=State -text -transform=noop -linecomment -output=lifecycle_state_gen.go"; DO NOT EDIT.

package license

import (
	"fmt"
	"strings"
)

const _StateName = "validgraceexpirednot_yet_validinvalidmissing"

var _StateIndex = [...]uint8{0, 5, 10, 17, 30, 37, 44}

const _StateLowerName = "validgraceexpirednot_yet_validinvalidmissing"

func (i State) String() string {
	i -= 1
	if i >= State(len(_StateIndex)-1) {
		return fmt.Sprintf("State(%d)", i+1)
	}
	return _StateName[_StateIndex[i]:_StateIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _StateNoOp() {
	var x [1]struct{}
	_ = x[StateValid-(1)]
	_ = x[StateGrace-(2)]
	_ = x[StateExpired-(3)]
	_ = x[StateNotYetValid-(4)]
	_ = x[StateInvalid-(5)]
	_ = x[StateMissing-(6)]
}

var _StateValues = []State{StateValid, StateGrace, StateExpired, StateNotYetValid, StateInvalid, StateMissing}

var _StateNameToValueMap = map[string]State{
	_StateName[0:5]:        StateValid,
	_StateLowerName[0:5]:   StateValid,
	_StateName[5:10]:       StateGrace,
	_StateLowerName[5:10]:  StateGrace,
	_StateName[10:17]:      StateExpired,
	_StateLowerName[10:17]: StateExpired,
	_StateName[17:30]:      StateNotYetValid,
	_StateLowerName[17:30]: StateNotYetValid,
	_StateName[30:37]:      StateInvalid,
	_StateLowerName[30:37]: StateInvalid,
	_StateName[37:44]:      StateMissing,
	_StateLowerName[37:44]: StateMissing,
}

var _StateNames = []string{
	_StateName[0:5],
	_StateName[5:10],
	_StateName[10:17],
	_StateName[17:30],
	_StateName[30:37],
	_StateName[37:44],
}

// StateString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func StateString(s string) (State, error) {
	if val, ok := _StateNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _StateNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to State values", s)
}

// StateValues returns all values of the enum
func StateValues() []State {
	return _StateValues
}

// StateStrings returns a slice of all String values of the enum
func StateStrings() []string {
	strs := make([]string, len(_StateNames))
	copy(strs, _StateNames)
	return strs
}

// IsAState returns "true" if the value is listed in the enum definition. "false" otherwise
func (i State) IsAState() bool {
	for _, v := range _StateValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for State
func (i State) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for State
func (i *State) UnmarshalText(text []byte) error {
	var err error
	*i, err = StateString(string(text))
	return err
}
