// Code generated by MockGen. DO NOT EDIT.
// Source: assignment.go
//
// Generated by this command:
//
//	mockgen -source=assignment.go -destination=assignment_mock_gen.go -package=repository -mock_names AssignmentRepository=MockAssignmentRepository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	model "github.com/opcotech/elemo/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAssignmentRepository is a mock of AssignmentRepository interface.
type MockAssignmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAssignmentRepositoryMockRecorder
	isgomock struct{}
}

// MockAssignmentRepositoryMockRecorder is the mock recorder for MockAssignmentRepository.
type MockAssignmentRepositoryMockRecorder struct {
	mock *MockAssignmentRepository
}

// NewMockAssignmentRepository creates a new mock instance.
func NewMockAssignmentRepository(ctrl *gomock.Controller) *MockAssignmentRepository {
	mock := &MockAssignmentRepository{ctrl: ctrl}
	mock.recorder = &MockAssignmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAssignmentRepository) EXPECT() *MockAssignmentRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAssignmentRepository) Create(ctx context.Context, opts CreateAssignmentOpts) (*Assignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, opts)
	ret0, _ := ret[0].(*Assignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAssignmentRepositoryMockRecorder) Create(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAssignmentRepository)(nil).Create), ctx, opts)
}

// Delete mocks base method.
func (m *MockAssignmentRepository) Delete(ctx context.Context, id model.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAssignmentRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAssignmentRepository)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockAssignmentRepository) Get(ctx context.Context, id model.ID) (*Assignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*Assignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAssignmentRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAssignmentRepository)(nil).Get), ctx, id)
}

// GetByResource mocks base method.
func (m *MockAssignmentRepository) GetByResource(ctx context.Context, resourceID model.ID, offset, limit int) ([]*Assignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByResource", ctx, resourceID, offset, limit)
	ret0, _ := ret[0].([]*Assignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByResource indicates an expected call of GetByResource.
func (mr *MockAssignmentRepositoryMockRecorder) GetByResource(ctx, resourceID, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByResource", reflect.TypeOf((*MockAssignmentRepository)(nil).GetByResource), ctx, resourceID, offset, limit)
}

// GetByUser mocks base method.
func (m *MockAssignmentRepository) GetByUser(ctx context.Context, userID model.ID, offset, limit int) ([]*Assignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUser", ctx, userID, offset, limit)
	ret0, _ := ret[0].([]*Assignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUser indicates an expected call of GetByUser.
func (mr *MockAssignmentRepositoryMockRecorder) GetByUser(ctx, userID, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUser", reflect.TypeOf((*MockAssignmentRepository)(nil).GetByUser), ctx, userID, offset, limit)
}
