package repository

import "errors"

var (
	ErrAssignmentCreate         = errors.New("failed to create assignment")               // the assignment could not be created
	ErrAssignmentDelete         = errors.New("failed to delete assignment")               // the assignment could not be deleted
	ErrAssignmentRead           = errors.New("failed to read assignment")                 // the assignment could not be retrieved
	ErrAttachmentCreate         = errors.New("failed to create attachment")               // the attachment could not be created
	ErrAttachmentDelete         = errors.New("failed to delete attachment")               // the attachment could not be deleted
	ErrAttachmentRead           = errors.New("failed to read attachment")                 // the attachment could not be retrieved
	ErrAttachmentUpdate         = errors.New("failed to update attachment")               // the attachment could not be updated
	ErrCacheDelete              = errors.New("failed to delete cache")                    // cache cannot be deleted
	ErrCacheRead                = errors.New("failed to read cache")                      // cache cannot be read
	ErrCacheWrite               = errors.New("failed to write cache")                     // cache cannot be written
	ErrCommentCreate            = errors.New("failed to create comment")                  // the comment could not be created
	ErrCommentDelete            = errors.New("failed to delete comment")                  // the comment could not be deleted
	ErrCommentRead              = errors.New("failed to read comment")                    // the comment could not be retrieved
	ErrCommentUpdate            = errors.New("failed to update comment")                  // the comment could not be updated
	ErrDocumentCreate           = errors.New("failed to create document")                 // the document could not be created
	ErrDocumentDelete           = errors.New("failed to delete document")                 // the document could not be deleted
	ErrDocumentRead             = errors.New("failed to read document")                   // the document could not be retrieved
	ErrDocumentUpdate           = errors.New("failed to update document")                 // the document could not be updated
	ErrInvalidDatabase          = errors.New("invalid database")                          // the database is invalid
	ErrInvalidDriver            = errors.New("invalid driver")                            // the driver is invalid
	ErrInvalidPool              = errors.New("invalid pool")                              // the pool is invalid
	ErrInvalidRepository        = errors.New("invalid repository")                        // the repository is invalid
	ErrIssueAddRelation         = errors.New("failed to add relation to issue")           // the relation could not be added to the issue
	ErrIssueAddWatcher          = errors.New("failed to add watcher to issue")            // the watcher could not be added to the issue
	ErrIssueCreate              = errors.New("failed to create issue")                    // the issue could not be created
	ErrIssueDelete              = errors.New("failed to delete issue")                    // the issue could not be deleted
	ErrIssueGetRelations        = errors.New("failed to get relations for issue")         // the relations could not be retrieved for the issue
	ErrIssueGetWatchers         = errors.New("failed to get watchers for issue")          // the watchers could not be retrieved for the issue
	ErrIssueRead                = errors.New("failed to read issue")                      // the issue could not be retrieved
	ErrIssueRemoveRelation      = errors.New("failed to remove relation from issue")      // the relation could not be removed from the issue
	ErrIssueRemoveWatcher       = errors.New("failed to remove watcher from issue")       // the watcher could not be removed from the issue
	ErrIssueUpdate              = errors.New("failed to update issue")                    // the issue could not be updated
	ErrLabelAttach              = errors.New("failed to attach label")                    // the label could not be attached
	ErrLabelCreate              = errors.New("failed to create label")                    // the label could not be created
	ErrLabelDelete              = errors.New("failed to delete label")                    // the label could not be deleted
	ErrLabelDetach              = errors.New("failed to detach label")                    // the label could not be detached
	ErrLabelRead                = errors.New("failed to read label")                      // the label could not be retrieved
	ErrLabelUpdate              = errors.New("failed to update label")                    // the label could not be updated
	ErrMalformedResult          = errors.New("malformed result")                          // the result is malformed
	ErrNamespaceCreate          = errors.New("failed to create namespace")                // the namespace could not be created
	ErrNamespaceDelete          = errors.New("failed to delete namespace")                // the namespace could not be deleted
	ErrNamespaceRead            = errors.New("failed to read namespace")                  // the namespace could not be retrieved
	ErrNamespaceUpdate          = errors.New("failed to update namespace")                // the namespace could not be updated
	ErrNoClient                 = errors.New("no client")                                 // the client is missing
	ErrNoDriver                 = errors.New("no driver")                                 // the driver is missing
	ErrNoLicenseRepository      = errors.New("no license repository provided")            // no license repository provided
	ErrNoPool                   = errors.New("no pool")                                   // the pool is nil
	ErrNotFound                 = errors.New("resource not found")                        // the resource was not found
	ErrOrganizationAddMember    = errors.New("failed to add member to organization")      // member cannot be added to organization
	ErrOrganizationCreate       = errors.New("failed to create organization")             // organization cannot be created
	ErrOrganizationDelete       = errors.New("failed to delete organization")             // organization cannot be deleted
	ErrOrganizationRead         = errors.New("failed to read organization")               // organization cannot be read
	ErrOrganizationRemoveMember = errors.New("failed to remove member from organization") // member cannot be removed from organization
	ErrOrganizationUpdate       = errors.New("failed to update organization")             // organization cannot be updated
	ErrPermissionCreate         = errors.New("failed to create permission")               // permission cannot be created
	ErrPermissionDelete         = errors.New("failed to delete permission")               // permission cannot be deleted
	ErrPermissionRead           = errors.New("failed to read permission")                 // permission cannot be read
	ErrPermissionUpdate         = errors.New("failed to update permission")               // permission cannot be updated
	ErrProjectCreate            = errors.New("failed to create project")                  // project cannot be created
	ErrProjectDelete            = errors.New("failed to delete project")                  // project cannot be deleted
	ErrProjectRead              = errors.New("failed to read project")                    // project cannot be read
	ErrProjectUpdate            = errors.New("failed to update project")                  // project cannot be updated
	ErrReadResourceCount        = errors.New("failed to read resource count")             // the resource count could not be retrieved
	ErrRelationRead             = errors.New("failed to read relation")                   // relation cannot be read
	ErrRoleAddMember            = errors.New("failed to add member to role")              // member cannot be added to role
	ErrRoleCreate               = errors.New("failed to create role")                     // role cannot be created
	ErrRoleDelete               = errors.New("failed to delete role")                     // role cannot be deleted
	ErrRoleRead                 = errors.New("failed to read role")                       // role cannot be read
	ErrRoleRemoveMember         = errors.New("failed to remove member from role")         // member cannot be removed from role
	ErrRoleUpdate               = errors.New("failed to update role")                     // role cannot be updated
	ErrSystemRoleRead           = errors.New("failed to read system role")                // the system role could not be retrieved
	ErrTodoCreate               = errors.New("failed to create todo")                     // todo cannot be created
	ErrTodoDelete               = errors.New("failed to delete todo")                     // todo cannot be deleted
	ErrTodoRead                 = errors.New("failed to read todo")                       // todo cannot be read
	ErrTodoUpdate               = errors.New("failed to update todo")                     // todo cannot be updated
	ErrUserCreate               = errors.New("failed to create user")                     // user cannot be created
	ErrUserDelete               = errors.New("failed to delete user")                     // user cannot be deleted
	ErrUserRead                 = errors.New("failed to read user")                       // user cannot be read
	ErrUserUpdate               = errors.New("failed to update user")                     // user cannot be updated
)
