// Code generated by MockGen. DO NOT EDIT.
// Source: issue.go
//
// Generated by this command:
//
//	mockgen -source=issue.go -destination=issue_mock_gen.go -package=repository -mock_names IssueRepository=MockIssueRepository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	model "github.com/opcotech/elemo/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockIssueRepository is a mock of IssueRepository interface.
type MockIssueRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIssueRepositoryMockRecorder
	isgomock struct{}
}

// MockIssueRepositoryMockRecorder is the mock recorder for MockIssueRepository.
type MockIssueRepositoryMockRecorder struct {
	mock *MockIssueRepository
}

// NewMockIssueRepository creates a new mock instance.
func NewMockIssueRepository(ctrl *gomock.Controller) *MockIssueRepository {
	mock := &MockIssueRepository{ctrl: ctrl}
	mock.recorder = &MockIssueRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIssueRepository) EXPECT() *MockIssueRepositoryMockRecorder {
	return m.recorder
}

// AddRelation mocks base method.
func (m *MockIssueRepository) AddRelation(ctx context.Context, opts CreateIssueRelationOpts) (*IssueRelation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRelation", ctx, opts)
	ret0, _ := ret[0].(*IssueRelation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddRelation indicates an expected call of AddRelation.
func (mr *MockIssueRepositoryMockRecorder) AddRelation(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRelation", reflect.TypeOf((*MockIssueRepository)(nil).AddRelation), ctx, opts)
}

// AddWatcher mocks base method.
func (m *MockIssueRepository) AddWatcher(ctx context.Context, issue, user model.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddWatcher", ctx, issue, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddWatcher indicates an expected call of AddWatcher.
func (mr *MockIssueRepositoryMockRecorder) AddWatcher(ctx, issue, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddWatcher", reflect.TypeOf((*MockIssueRepository)(nil).AddWatcher), ctx, issue, user)
}

// Create mocks base method.
func (m *MockIssueRepository) Create(ctx context.Context, opts CreateIssueOpts) (*Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, opts)
	ret0, _ := ret[0].(*Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIssueRepositoryMockRecorder) Create(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIssueRepository)(nil).Create), ctx, opts)
}

// Delete mocks base method.
func (m *MockIssueRepository) Delete(ctx context.Context, id model.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIssueRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIssueRepository)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockIssueRepository) Get(ctx context.Context, id model.ID) (*Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIssueRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIssueRepository)(nil).Get), ctx, id)
}

// GetAllForIssue mocks base method.
func (m *MockIssueRepository) GetAllForIssue(ctx context.Context, issueID model.ID, offset, limit int) ([]*Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllForIssue", ctx, issueID, offset, limit)
	ret0, _ := ret[0].([]*Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllForIssue indicates an expected call of GetAllForIssue.
func (mr *MockIssueRepositoryMockRecorder) GetAllForIssue(ctx, issueID, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllForIssue", reflect.TypeOf((*MockIssueRepository)(nil).GetAllForIssue), ctx, issueID, offset, limit)
}

// GetAllForProject mocks base method.
func (m *MockIssueRepository) GetAllForProject(ctx context.Context, projectID model.ID, offset, limit int) ([]*Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllForProject", ctx, projectID, offset, limit)
	ret0, _ := ret[0].([]*Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllForProject indicates an expected call of GetAllForProject.
func (mr *MockIssueRepositoryMockRecorder) GetAllForProject(ctx, projectID, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllForProject", reflect.TypeOf((*MockIssueRepository)(nil).GetAllForProject), ctx, projectID, offset, limit)
}

// GetRelations mocks base method.
func (m *MockIssueRepository) GetRelations(ctx context.Context, issue model.ID) ([]*IssueRelation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRelations", ctx, issue)
	ret0, _ := ret[0].([]*IssueRelation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRelations indicates an expected call of GetRelations.
func (mr *MockIssueRepositoryMockRecorder) GetRelations(ctx, issue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRelations", reflect.TypeOf((*MockIssueRepository)(nil).GetRelations), ctx, issue)
}

// GetWatchers mocks base method.
func (m *MockIssueRepository) GetWatchers(ctx context.Context, issue model.ID) ([]*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWatchers", ctx, issue)
	ret0, _ := ret[0].([]*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWatchers indicates an expected call of GetWatchers.
func (mr *MockIssueRepositoryMockRecorder) GetWatchers(ctx, issue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWatchers", reflect.TypeOf((*MockIssueRepository)(nil).GetWatchers), ctx, issue)
}

// RemoveRelation mocks base method.
func (m *MockIssueRepository) RemoveRelation(ctx context.Context, source, target model.ID, kind model.IssueRelationKind) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveRelation", ctx, source, target, kind)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveRelation indicates an expected call of RemoveRelation.
func (mr *MockIssueRepositoryMockRecorder) RemoveRelation(ctx, source, target, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRelation", reflect.TypeOf((*MockIssueRepository)(nil).RemoveRelation), ctx, source, target, kind)
}

// RemoveWatcher mocks base method.
func (m *MockIssueRepository) RemoveWatcher(ctx context.Context, issue, user model.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveWatcher", ctx, issue, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveWatcher indicates an expected call of RemoveWatcher.
func (mr *MockIssueRepositoryMockRecorder) RemoveWatcher(ctx, issue, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveWatcher", reflect.TypeOf((*MockIssueRepository)(nil).RemoveWatcher), ctx, issue, user)
}

// Update mocks base method.
func (m *MockIssueRepository) Update(ctx context.Context, id model.ID, opts UpdateIssueOpts) (*Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, opts)
	ret0, _ := ret[0].(*Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIssueRepositoryMockRecorder) Update(ctx, id, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIssueRepository)(nil).Update), ctx, id, opts)
}
