// Code generated by MockGen. DO NOT EDIT.
// Source: label.go
//
// Generated by this command:
//
//	mockgen -source=label.go -destination=label_mock_gen.go -package=repository -mock_names LabelRepository=MockLabelRepository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	model "github.com/opcotech/elemo/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockLabelRepository is a mock of LabelRepository interface.
type MockLabelRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLabelRepositoryMockRecorder
	isgomock struct{}
}

// MockLabelRepositoryMockRecorder is the mock recorder for MockLabelRepository.
type MockLabelRepositoryMockRecorder struct {
	mock *MockLabelRepository
}

// NewMockLabelRepository creates a new mock instance.
func NewMockLabelRepository(ctrl *gomock.Controller) *MockLabelRepository {
	mock := &MockLabelRepository{ctrl: ctrl}
	mock.recorder = &MockLabelRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLabelRepository) EXPECT() *MockLabelRepositoryMockRecorder {
	return m.recorder
}

// AttachTo mocks base method.
func (m *MockLabelRepository) AttachTo(ctx context.Context, labelID, attachTo model.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachTo", ctx, labelID, attachTo)
	ret0, _ := ret[0].(error)
	return ret0
}

// AttachTo indicates an expected call of AttachTo.
func (mr *MockLabelRepositoryMockRecorder) AttachTo(ctx, labelID, attachTo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachTo", reflect.TypeOf((*MockLabelRepository)(nil).AttachTo), ctx, labelID, attachTo)
}

// Create mocks base method.
func (m *MockLabelRepository) Create(ctx context.Context, opts CreateLabelOpts) (*Label, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, opts)
	ret0, _ := ret[0].(*Label)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockLabelRepositoryMockRecorder) Create(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLabelRepository)(nil).Create), ctx, opts)
}

// Delete mocks base method.
func (m *MockLabelRepository) Delete(ctx context.Context, id model.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockLabelRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLabelRepository)(nil).Delete), ctx, id)
}

// DetachFrom mocks base method.
func (m *MockLabelRepository) DetachFrom(ctx context.Context, labelID, detachFrom model.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetachFrom", ctx, labelID, detachFrom)
	ret0, _ := ret[0].(error)
	return ret0
}

// DetachFrom indicates an expected call of DetachFrom.
func (mr *MockLabelRepositoryMockRecorder) DetachFrom(ctx, labelID, detachFrom any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetachFrom", reflect.TypeOf((*MockLabelRepository)(nil).DetachFrom), ctx, labelID, detachFrom)
}

// Get mocks base method.
func (m *MockLabelRepository) Get(ctx context.Context, id model.ID) (*Label, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*Label)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockLabelRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockLabelRepository)(nil).Get), ctx, id)
}

// GetAll mocks base method.
func (m *MockLabelRepository) GetAll(ctx context.Context, offset, limit int) ([]*Label, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, offset, limit)
	ret0, _ := ret[0].([]*Label)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockLabelRepositoryMockRecorder) GetAll(ctx, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockLabelRepository)(nil).GetAll), ctx, offset, limit)
}

// Update mocks base method.
func (m *MockLabelRepository) Update(ctx context.Context, id model.ID, opts UpdateLabelOpts) (*Label, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, opts)
	ret0, _ := ret[0].(*Label)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockLabelRepositoryMockRecorder) Update(ctx, id, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLabelRepository)(nil).Update), ctx, id, opts)
}
