// Code generated by MockGen. DO NOT EDIT.
// Source: namespace.go
//
// Generated by this command:
//
//	mockgen -source=namespace.go -destination=namespace_mock_gen.go -package=repository -mock_names NamespaceRepository=MockNamespaceRepository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	model "github.com/opcotech/elemo/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockNamespaceRepository is a mock of NamespaceRepository interface.
type MockNamespaceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNamespaceRepositoryMockRecorder
	isgomock struct{}
}

// MockNamespaceRepositoryMockRecorder is the mock recorder for MockNamespaceRepository.
type MockNamespaceRepositoryMockRecorder struct {
	mock *MockNamespaceRepository
}

// NewMockNamespaceRepository creates a new mock instance.
func NewMockNamespaceRepository(ctrl *gomock.Controller) *MockNamespaceRepository {
	mock := &MockNamespaceRepository{ctrl: ctrl}
	mock.recorder = &MockNamespaceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNamespaceRepository) EXPECT() *MockNamespaceRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNamespaceRepository) Create(ctx context.Context, opts CreateNamespaceOpts) (*Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, opts)
	ret0, _ := ret[0].(*Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockNamespaceRepositoryMockRecorder) Create(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNamespaceRepository)(nil).Create), ctx, opts)
}

// Delete mocks base method.
func (m *MockNamespaceRepository) Delete(ctx context.Context, id model.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockNamespaceRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNamespaceRepository)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockNamespaceRepository) Get(ctx context.Context, id model.ID) (*Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockNamespaceRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockNamespaceRepository)(nil).Get), ctx, id)
}

// GetAll mocks base method.
func (m *MockNamespaceRepository) GetAll(ctx context.Context, orgID model.ID, offset, limit int) ([]*Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, orgID, offset, limit)
	ret0, _ := ret[0].([]*Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockNamespaceRepositoryMockRecorder) GetAll(ctx, orgID, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockNamespaceRepository)(nil).GetAll), ctx, orgID, offset, limit)
}

// Update mocks base method.
func (m *MockNamespaceRepository) Update(ctx context.Context, id model.ID, opts UpdateNamespaceOpts) (*Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, opts)
	ret0, _ := ret[0].(*Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockNamespaceRepositoryMockRecorder) Update(ctx, id, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockNamespaceRepository)(nil).Update), ctx, id, opts)
}
