// Code generated by MockGen. DO NOT EDIT.
// Source: organization.go
//
// Generated by this command:
//
//	mockgen -source=organization.go -destination=organization_mock_gen.go -package=repository -mock_names OrganizationRepository=MockOrganizationRepository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	model "github.com/opcotech/elemo/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockOrganizationRepository is a mock of OrganizationRepository interface.
type MockOrganizationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrganizationRepositoryMockRecorder
	isgomock struct{}
}

// MockOrganizationRepositoryMockRecorder is the mock recorder for MockOrganizationRepository.
type MockOrganizationRepositoryMockRecorder struct {
	mock *MockOrganizationRepository
}

// NewMockOrganizationRepository creates a new mock instance.
func NewMockOrganizationRepository(ctrl *gomock.Controller) *MockOrganizationRepository {
	mock := &MockOrganizationRepository{ctrl: ctrl}
	mock.recorder = &MockOrganizationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganizationRepository) EXPECT() *MockOrganizationRepositoryMockRecorder {
	return m.recorder
}

// AddInvitation mocks base method.
func (m *MockOrganizationRepository) AddInvitation(ctx context.Context, orgID, userID model.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddInvitation", ctx, orgID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddInvitation indicates an expected call of AddInvitation.
func (mr *MockOrganizationRepositoryMockRecorder) AddInvitation(ctx, orgID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddInvitation", reflect.TypeOf((*MockOrganizationRepository)(nil).AddInvitation), ctx, orgID, userID)
}

// AddMember mocks base method.
func (m *MockOrganizationRepository) AddMember(ctx context.Context, orgID, memberID model.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMember", ctx, orgID, memberID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMember indicates an expected call of AddMember.
func (mr *MockOrganizationRepositoryMockRecorder) AddMember(ctx, orgID, memberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockOrganizationRepository)(nil).AddMember), ctx, orgID, memberID)
}

// Create mocks base method.
func (m *MockOrganizationRepository) Create(ctx context.Context, opts CreateOrganizationOpts) (*Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, opts)
	ret0, _ := ret[0].(*Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockOrganizationRepositoryMockRecorder) Create(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrganizationRepository)(nil).Create), ctx, opts)
}

// Delete mocks base method.
func (m *MockOrganizationRepository) Delete(ctx context.Context, id model.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockOrganizationRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOrganizationRepository)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockOrganizationRepository) Get(ctx context.Context, id model.ID) (*Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockOrganizationRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockOrganizationRepository)(nil).Get), ctx, id)
}

// GetAll mocks base method.
func (m *MockOrganizationRepository) GetAll(ctx context.Context, userID model.ID, offset, limit int) ([]*Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, userID, offset, limit)
	ret0, _ := ret[0].([]*Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockOrganizationRepositoryMockRecorder) GetAll(ctx, userID, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockOrganizationRepository)(nil).GetAll), ctx, userID, offset, limit)
}

// GetInvitations mocks base method.
func (m *MockOrganizationRepository) GetInvitations(ctx context.Context, orgID model.ID) ([]*OrganizationMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvitations", ctx, orgID)
	ret0, _ := ret[0].([]*OrganizationMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvitations indicates an expected call of GetInvitations.
func (mr *MockOrganizationRepositoryMockRecorder) GetInvitations(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvitations", reflect.TypeOf((*MockOrganizationRepository)(nil).GetInvitations), ctx, orgID)
}

// GetMembers mocks base method.
func (m *MockOrganizationRepository) GetMembers(ctx context.Context, orgID model.ID) ([]*OrganizationMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMembers", ctx, orgID)
	ret0, _ := ret[0].([]*OrganizationMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMembers indicates an expected call of GetMembers.
func (mr *MockOrganizationRepositoryMockRecorder) GetMembers(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMembers", reflect.TypeOf((*MockOrganizationRepository)(nil).GetMembers), ctx, orgID)
}

// RemoveInvitation mocks base method.
func (m *MockOrganizationRepository) RemoveInvitation(ctx context.Context, orgID, userID model.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveInvitation", ctx, orgID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveInvitation indicates an expected call of RemoveInvitation.
func (mr *MockOrganizationRepositoryMockRecorder) RemoveInvitation(ctx, orgID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveInvitation", reflect.TypeOf((*MockOrganizationRepository)(nil).RemoveInvitation), ctx, orgID, userID)
}

// RemoveMember mocks base method.
func (m *MockOrganizationRepository) RemoveMember(ctx context.Context, orgID, memberID model.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", ctx, orgID, memberID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockOrganizationRepositoryMockRecorder) RemoveMember(ctx, orgID, memberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockOrganizationRepository)(nil).RemoveMember), ctx, orgID, memberID)
}

// Update mocks base method.
func (m *MockOrganizationRepository) Update(ctx context.Context, id model.ID, opts UpdateOrganizationOpts) (*Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, opts)
	ret0, _ := ret[0].(*Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockOrganizationRepositoryMockRecorder) Update(ctx, id, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockOrganizationRepository)(nil).Update), ctx, id, opts)
}
