// Code generated by "enumer -type=EdgeKind -trimprefix=EdgeKind -transform=snake-upper -output=repository_edge_kind_gen.go"; DO NOT EDIT.

package repository

import (
	"fmt"
	"strings"
)

const _EdgeKindName = "ASSIGNED_TOBELONGS_TOCOMMENTEDCREATEDHAS_ATTACHMENTHAS_COMMENTHAS_LABELHAS_NAMESPACEHAS_PERMISSIONHAS_PROJECTHAS_TEAMINVITEDINVITED_TOKIND_OFMEMBER_OFRELATED_TOSPEAKSWATCHES"

var _EdgeKindIndex = [...]uint8{0, 11, 21, 30, 37, 51, 62, 71, 84, 98, 109, 117, 124, 134, 141, 150, 160, 166, 173}

const _EdgeKindLowerName = "assigned_tobelongs_tocommentedcreatedhas_attachmenthas_commenthas_labelhas_namespacehas_permissionhas_projecthas_teaminvitedinvited_tokind_ofmember_ofrelated_tospeakswatches"

func (i EdgeKind) String() string {
	i -= 1
	if i >= EdgeKind(len(_EdgeKindIndex)-1) {
		return fmt.Sprintf("EdgeKind(%d)", i+1)
	}
	return _EdgeKindName[_EdgeKindIndex[i]:_EdgeKindIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _EdgeKindNoOp() {
	var x [1]struct{}
	_ = x[EdgeKindAssignedTo-(1)]
	_ = x[EdgeKindBelongsTo-(2)]
	_ = x[EdgeKindCommented-(3)]
	_ = x[EdgeKindCreated-(4)]
	_ = x[EdgeKindHasAttachment-(5)]
	_ = x[EdgeKindHasComment-(6)]
	_ = x[EdgeKindHasLabel-(7)]
	_ = x[EdgeKindHasNamespace-(8)]
	_ = x[EdgeKindHasPermission-(9)]
	_ = x[EdgeKindHasProject-(10)]
	_ = x[EdgeKindHasTeam-(11)]
	_ = x[EdgeKindInvited-(12)]
	_ = x[EdgeKindInvitedTo-(13)]
	_ = x[EdgeKindKindOf-(14)]
	_ = x[EdgeKindMemberOf-(15)]
	_ = x[EdgeKindRelatedTo-(16)]
	_ = x[EdgeKindSpeaks-(17)]
	_ = x[EdgeKindWatches-(18)]
}

var _EdgeKindValues = []EdgeKind{EdgeKindAssignedTo, EdgeKindBelongsTo, EdgeKindCommented, EdgeKindCreated, EdgeKindHasAttachment, EdgeKindHasComment, EdgeKindHasLabel, EdgeKindHasNamespace, EdgeKindHasPermission, EdgeKindHasProject, EdgeKindHasTeam, EdgeKindInvited, EdgeKindInvitedTo, EdgeKindKindOf, EdgeKindMemberOf, EdgeKindRelatedTo, EdgeKindSpeaks, EdgeKindWatches}

var _EdgeKindNameToValueMap = map[string]EdgeKind{
	_EdgeKindName[0:11]:         EdgeKindAssignedTo,
	_EdgeKindLowerName[0:11]:    EdgeKindAssignedTo,
	_EdgeKindName[11:21]:        EdgeKindBelongsTo,
	_EdgeKindLowerName[11:21]:   EdgeKindBelongsTo,
	_EdgeKindName[21:30]:        EdgeKindCommented,
	_EdgeKindLowerName[21:30]:   EdgeKindCommented,
	_EdgeKindName[30:37]:        EdgeKindCreated,
	_EdgeKindLowerName[30:37]:   EdgeKindCreated,
	_EdgeKindName[37:51]:        EdgeKindHasAttachment,
	_EdgeKindLowerName[37:51]:   EdgeKindHasAttachment,
	_EdgeKindName[51:62]:        EdgeKindHasComment,
	_EdgeKindLowerName[51:62]:   EdgeKindHasComment,
	_EdgeKindName[62:71]:        EdgeKindHasLabel,
	_EdgeKindLowerName[62:71]:   EdgeKindHasLabel,
	_EdgeKindName[71:84]:        EdgeKindHasNamespace,
	_EdgeKindLowerName[71:84]:   EdgeKindHasNamespace,
	_EdgeKindName[84:98]:        EdgeKindHasPermission,
	_EdgeKindLowerName[84:98]:   EdgeKindHasPermission,
	_EdgeKindName[98:109]:       EdgeKindHasProject,
	_EdgeKindLowerName[98:109]:  EdgeKindHasProject,
	_EdgeKindName[109:117]:      EdgeKindHasTeam,
	_EdgeKindLowerName[109:117]: EdgeKindHasTeam,
	_EdgeKindName[117:124]:      EdgeKindInvited,
	_EdgeKindLowerName[117:124]: EdgeKindInvited,
	_EdgeKindName[124:134]:      EdgeKindInvitedTo,
	_EdgeKindLowerName[124:134]: EdgeKindInvitedTo,
	_EdgeKindName[134:141]:      EdgeKindKindOf,
	_EdgeKindLowerName[134:141]: EdgeKindKindOf,
	_EdgeKindName[141:150]:      EdgeKindMemberOf,
	_EdgeKindLowerName[141:150]: EdgeKindMemberOf,
	_EdgeKindName[150:160]:      EdgeKindRelatedTo,
	_EdgeKindLowerName[150:160]: EdgeKindRelatedTo,
	_EdgeKindName[160:166]:      EdgeKindSpeaks,
	_EdgeKindLowerName[160:166]: EdgeKindSpeaks,
	_EdgeKindName[166:173]:      EdgeKindWatches,
	_EdgeKindLowerName[166:173]: EdgeKindWatches,
}

var _EdgeKindNames = []string{
	_EdgeKindName[0:11],
	_EdgeKindName[11:21],
	_EdgeKindName[21:30],
	_EdgeKindName[30:37],
	_EdgeKindName[37:51],
	_EdgeKindName[51:62],
	_EdgeKindName[62:71],
	_EdgeKindName[71:84],
	_EdgeKindName[84:98],
	_EdgeKindName[98:109],
	_EdgeKindName[109:117],
	_EdgeKindName[117:124],
	_EdgeKindName[124:134],
	_EdgeKindName[134:141],
	_EdgeKindName[141:150],
	_EdgeKindName[150:160],
	_EdgeKindName[160:166],
	_EdgeKindName[166:173],
}

// EdgeKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func EdgeKindString(s string) (EdgeKind, error) {
	if val, ok := _EdgeKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _EdgeKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to EdgeKind values", s)
}

// EdgeKindValues returns all values of the enum
func EdgeKindValues() []EdgeKind {
	return _EdgeKindValues
}

// EdgeKindStrings returns a slice of all String values of the enum
func EdgeKindStrings() []string {
	strs := make([]string, len(_EdgeKindNames))
	copy(strs, _EdgeKindNames)
	return strs
}

// IsAEdgeKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i EdgeKind) IsAEdgeKind() bool {
	for _, v := range _EdgeKindValues {
		if i == v {
			return true
		}
	}
	return false
}
