// Code generated by MockGen. DO NOT EDIT.
// Source: role.go
//
// Generated by this command:
//
//	mockgen -source=role.go -destination=role_mock_gen.go -package=repository -mock_names RoleRepository=MockRoleRepository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	model "github.com/opcotech/elemo/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockRoleRepository is a mock of RoleRepository interface.
type MockRoleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoleRepositoryMockRecorder
	isgomock struct{}
}

// MockRoleRepositoryMockRecorder is the mock recorder for MockRoleRepository.
type MockRoleRepositoryMockRecorder struct {
	mock *MockRoleRepository
}

// NewMockRoleRepository creates a new mock instance.
func NewMockRoleRepository(ctrl *gomock.Controller) *MockRoleRepository {
	mock := &MockRoleRepository{ctrl: ctrl}
	mock.recorder = &MockRoleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleRepository) EXPECT() *MockRoleRepositoryMockRecorder {
	return m.recorder
}

// AddMember mocks base method.
func (m *MockRoleRepository) AddMember(ctx context.Context, roleID, memberID, belongsToID model.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMember", ctx, roleID, memberID, belongsToID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMember indicates an expected call of AddMember.
func (mr *MockRoleRepositoryMockRecorder) AddMember(ctx, roleID, memberID, belongsToID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockRoleRepository)(nil).AddMember), ctx, roleID, memberID, belongsToID)
}

// Create mocks base method.
func (m *MockRoleRepository) Create(ctx context.Context, opts CreateRoleOpts) (*Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, opts)
	ret0, _ := ret[0].(*Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRoleRepositoryMockRecorder) Create(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRoleRepository)(nil).Create), ctx, opts)
}

// Delete mocks base method.
func (m *MockRoleRepository) Delete(ctx context.Context, id, belongsTo model.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, belongsTo)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRoleRepositoryMockRecorder) Delete(ctx, id, belongsTo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRoleRepository)(nil).Delete), ctx, id, belongsTo)
}

// Get mocks base method.
func (m *MockRoleRepository) Get(ctx context.Context, id, belongsTo model.ID, proj RoleProjection) (*Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id, belongsTo, proj)
	ret0, _ := ret[0].(*Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRoleRepositoryMockRecorder) Get(ctx, id, belongsTo, proj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRoleRepository)(nil).Get), ctx, id, belongsTo, proj)
}

// ListBelongsTo mocks base method.
func (m *MockRoleRepository) ListBelongsTo(ctx context.Context, belongsTo model.ID, page CursorPage, proj RoleProjection) (Page[*Role], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBelongsTo", ctx, belongsTo, page, proj)
	ret0, _ := ret[0].(Page[*Role])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBelongsTo indicates an expected call of ListBelongsTo.
func (mr *MockRoleRepositoryMockRecorder) ListBelongsTo(ctx, belongsTo, page, proj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBelongsTo", reflect.TypeOf((*MockRoleRepository)(nil).ListBelongsTo), ctx, belongsTo, page, proj)
}

// ListMembers mocks base method.
func (m *MockRoleRepository) ListMembers(ctx context.Context, roleID, belongsTo model.ID, page CursorPage) (Page[*User], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMembers", ctx, roleID, belongsTo, page)
	ret0, _ := ret[0].(Page[*User])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMembers indicates an expected call of ListMembers.
func (mr *MockRoleRepositoryMockRecorder) ListMembers(ctx, roleID, belongsTo, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMembers", reflect.TypeOf((*MockRoleRepository)(nil).ListMembers), ctx, roleID, belongsTo, page)
}

// RemoveMember mocks base method.
func (m *MockRoleRepository) RemoveMember(ctx context.Context, roleID, memberID, belongsToID model.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", ctx, roleID, memberID, belongsToID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockRoleRepositoryMockRecorder) RemoveMember(ctx, roleID, memberID, belongsToID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockRoleRepository)(nil).RemoveMember), ctx, roleID, memberID, belongsToID)
}

// Update mocks base method.
func (m *MockRoleRepository) Update(ctx context.Context, id, belongsTo model.ID, opts UpdateRoleOpts) (*Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, belongsTo, opts)
	ret0, _ := ret[0].(*Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRoleRepositoryMockRecorder) Update(ctx, id, belongsTo, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRoleRepository)(nil).Update), ctx, id, belongsTo, opts)
}
