// Code generated by MockGen. DO NOT EDIT.
// Source: search.go
//
// Generated by this command:
//
//	mockgen -source=search.go -destination=search_mock_gen.go -package=repository -mock_names SearchRepository=MockSearchRepository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSearchRepository is a mock of SearchRepository interface.
type MockSearchRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSearchRepositoryMockRecorder
	isgomock struct{}
}

// MockSearchRepositoryMockRecorder is the mock recorder for MockSearchRepository.
type MockSearchRepositoryMockRecorder struct {
	mock *MockSearchRepository
}

// NewMockSearchRepository creates a new mock instance.
func NewMockSearchRepository(ctrl *gomock.Controller) *MockSearchRepository {
	mock := &MockSearchRepository{ctrl: ctrl}
	mock.recorder = &MockSearchRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchRepository) EXPECT() *MockSearchRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockSearchRepository) Delete(ctx context.Context, ids ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range ids {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSearchRepositoryMockRecorder) Delete(ctx any, ids ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, ids...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSearchRepository)(nil).Delete), varargs...)
}

// DeleteAll mocks base method.
func (m *MockSearchRepository) DeleteAll(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAll", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAll indicates an expected call of DeleteAll.
func (mr *MockSearchRepositoryMockRecorder) DeleteAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAll", reflect.TypeOf((*MockSearchRepository)(nil).DeleteAll), ctx)
}

// DeleteByScope mocks base method.
func (m *MockSearchRepository) DeleteByScope(ctx context.Context, scopeID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByScope", ctx, scopeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByScope indicates an expected call of DeleteByScope.
func (mr *MockSearchRepositoryMockRecorder) DeleteByScope(ctx, scopeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByScope", reflect.TypeOf((*MockSearchRepository)(nil).DeleteByScope), ctx, scopeID)
}

// EnsureIndex mocks base method.
func (m *MockSearchRepository) EnsureIndex(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureIndex", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureIndex indicates an expected call of EnsureIndex.
func (mr *MockSearchRepositoryMockRecorder) EnsureIndex(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureIndex", reflect.TypeOf((*MockSearchRepository)(nil).EnsureIndex), ctx)
}

// Ping mocks base method.
func (m *MockSearchRepository) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockSearchRepositoryMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockSearchRepository)(nil).Ping), ctx)
}

// Search mocks base method.
func (m *MockSearchRepository) Search(ctx context.Context, q SearchQuery) (*SearchHits, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, q)
	ret0, _ := ret[0].(*SearchHits)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockSearchRepositoryMockRecorder) Search(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockSearchRepository)(nil).Search), ctx, q)
}

// Upsert mocks base method.
func (m *MockSearchRepository) Upsert(ctx context.Context, docs ...SearchDocument) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range docs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Upsert", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockSearchRepositoryMockRecorder) Upsert(ctx any, docs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, docs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockSearchRepository)(nil).Upsert), varargs...)
}
