{
 "title": "Service metrics",
 "description": "Elemo service metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "slow",
    "label": "slow query",
    "query": "5ms,10ms,25ms,50ms,100ms,150ms,200ms,250ms,500ms,1s,2s,5s,10s"
   },
   {
    "name": "handler",
    "query": {
     "query": "http_request_duration_seconds_count{service=\"elemo\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Response time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(http_request_duration_seconds_bucket{service=\"elemo\", handler=~\"$handler\"}[$__rate_interval]))) * 1000",
     "legendFormat": "p25"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_request_duration_seconds_bucket{service=\"elemo\", handler=~\"$handler\"}[$__rate_interval]))) * 1000",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(http_request_duration_seconds_bucket{service=\"elemo\", handler=~\"$handler\"}[$__rate_interval]))) * 1000",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(http_request_duration_seconds_bucket{service=\"elemo\", handler=~\"$handler\"}[$__rate_interval]))) * 1000",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_request_duration_seconds_bucket{service=\"elemo\", handler=~\"$handler\"}[$__rate_interval]))) * 1000",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum by(le) (rate(http_request_duration_seconds_bucket{service=\"elemo\", handler=~\"$handler\"}[$__rate_interval]))) * 1000",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Request error rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(code) (rate(http_request_duration_seconds_count{service=\"elemo\", handler=~\"$handler\", code=~\"4..\"}[$__rate_interval]))",
     "legendFormat": "{{code}}"
    },
    {
     "expr": "sum by(code) (rate(http_request_duration_seconds_count{service=\"elemo\", handler=~\"$handler\", code=~\"5..\"}[$__rate_interval]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Request rate per status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by(code) (rate(http_request_duration_seconds_count{service=\"elemo\", handler=~\"$handler\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "In-flight requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum by(handler) (http_requests_inflight{service=\"elemo\", handler=~\"$handler\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slow queries for handler (max. 10)",
   "type": "table",
   "description": "You must select a handler first to show details",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    { "limit": 10, "minDuration": "$slow", "operation": "$handler", "service": "elemo" }
   ]
  }
 ]
}