name: "Feature Request"
description: Create a new issue for a new feature request.
title: "<title>"
labels:
  - question
  - enhancement
body:
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: Provide a brief explanation of the feature.
      placeholder: Describe in a few lines your feature request...
    validations:
      required: true
  - type: textarea
    id: example_use_cases
    attributes:
      label: "Example Use-cases"
      description: List some basic use-cases for the feature.
      placeholder: A few specific words about your feature request.
    validations:
      required: true
  - type: textarea
    id: drawbacks
    attributes:
      label: "Drawbacks"
      description: What are the drawbacks/impacts of your feature request?
      placeholder: Identify the drawbacks and impacts while being neutral on your feature request...
    validations:
      required: true
