package model

import "errors"

var (
	ErrInvalidAssignmentDetails         = errors.New("invalid assignment details")              // the assignment details are invalid
	ErrInvalidAssignmentKind            = errors.New("invalid assigned to kind")                // the assigned to kind is invalid
	ErrInvalidAttachmentDetails         = errors.New("invalid attachment details")              // the attachment details are invalid
	ErrInvalidCommentDetails            = errors.New("invalid comment details")                 // the comment details are invalid
	ErrInvalidCustomFieldDetails        = errors.New("invalid custom field details")            // the custom field details are invalid
	ErrInvalidCustomFieldKind           = errors.New("invalid custom field kind")               // the custom field kind is invalid
	ErrInvalidCustomFieldValue          = errors.New("invalid custom field value")              // the custom field value is invalid
	ErrCustomFieldArchived              = errors.New("custom field is archived")                // archived fields reject writes
	ErrCustomFieldInUse                 = errors.New("custom field has stored values")          // hard delete is blocked while values exist
	ErrCustomFieldIdentityImmutable     = errors.New("custom field identity is immutable")      // key, kind, scope, owner, or target cannot change
	ErrCustomFieldOptionInUse           = errors.New("custom field option is in use")           // referenced option keys cannot be deleted
	ErrCustomFieldRequired              = errors.New("custom field value is required")          // a required field is missing a value
	ErrInvalidDocumentDetails           = errors.New("invalid document details")                // the document details are invalid
	ErrInvalidFolderDetails             = errors.New("invalid folder details")                  // the folder details are invalid
	ErrInvalidHealthStatus              = errors.New("invalid health status")                   // health status is invalid
	ErrInvalidID                        = errors.New("invalid id")                              // the id is invalid
	ErrInvalidIssueDetails              = errors.New("invalid issue details")                   // the issue details are invalid
	ErrInvalidIssueKind                 = errors.New("invalid issue kind")                      // the issue kind is invalid
	ErrInvalidIssuePriority             = errors.New("invalid issue priority")                  // the issue priority is invalid
	ErrInvalidIssueRelationDetails      = errors.New("invalid issue relation details")          // the issue relation details are invalid
	ErrInvalidIssueRelationKind         = errors.New("invalid issue relation kind")             // the issue relation kind is invalid
	ErrInvalidIssueResolution           = errors.New("invalid issue resolution")                // the issue resolution is invalid
	ErrInvalidIssueStatus               = errors.New("invalid issue status")                    // the issue status is invalid
	ErrInvalidLabelDetails              = errors.New("invalid Type details")                    // the Type details are invalid
	ErrInvalidLanguage                  = errors.New("invalid language code")                   // Language is not valid
	ErrInvalidNamespaceDetails          = errors.New("invalid namespace details")               // the namespace details are invalid
	ErrInvalidNotificationDetails       = errors.New("invalid notification details")            // the notification details are invalid
	ErrInvalidNotificationRecipient     = errors.New("invalid notification recipient")          // the notification recipient is invalid
	ErrInvalidOrganizationDetails       = errors.New("invalid organization details")            // the organization details are invalid
	ErrInvalidOrganizationMemberDetails = errors.New("invalid organization member details")     // the organization member details are invalid
	ErrInvalidOrganizationStatus        = errors.New("invalid organization status")             // the organization status is invalid
	ErrInvalidPartialDocumentDetails    = errors.New("invalid partial document details")        // the partial document details are invalid
	ErrInvalidPartialProjectDetails     = errors.New("invalid partial project details")         // the partial project details are invalid
	ErrInvalidAction                    = errors.New("invalid action")                          // the action is not in the registry
	ErrInvalidGrant                     = errors.New("invalid grant")                           // the grant details are invalid
	ErrInvalidPermissionDetails         = errors.New("invalid permission details")              // the permission details are invalid
	ErrGrantCycle                       = errors.New("authorization scope cycle")               // IN_SCOPE_OF would create a cycle
	ErrNotAPrincipal                    = errors.New("subject is not a principal")              // grant subject is not a principal
	ErrPrivilegeEscalation              = errors.New("privilege escalation denied")             // caller cannot grant an unheld action
	ErrUnknownRoleKey                   = errors.New("unknown role key")                        // role template key is unknown
	ErrInvalidProjectDetails            = errors.New("invalid project details")                 // the project details are invalid
	ErrInvalidProjectStatus             = errors.New("invalid project status")                  // the project status is invalid
	ErrInvalidResourceType              = errors.New("invalid resource type")                   // the resource type is invalid
	ErrInvalidRoleDetails               = errors.New("invalid role details")                    // the role details are invalid
	ErrInvalidTeamDetails               = errors.New("invalid team details")                    // the team details are invalid
	ErrInvalidTodoDetails               = errors.New("invalid todo details")                    // the todo details are invalid
	ErrInvalidTodoPriority              = errors.New("invalid todo priority")                   // the todo priority is invalid
	ErrInvalidUserDetails               = errors.New("invalid user details")                    // the user details are invalid
	ErrInvalidUserStatus                = errors.New("invalid user status")                     // the user status is invalid
	ErrInvalidUserToken                 = errors.New("invalid user token")                      // the user token is invalid
	ErrInvalidUserTokenContext          = errors.New("invalid user token context")              // the provided user token context is invalid
	ErrPermissionSubjectTargetEqual     = errors.New("permission subject and target are equal") // the permission subject and target are equal
	ErrInvalidPluginManifest            = errors.New("invalid plugin manifest")                 // the plugin manifest is invalid
	ErrInvalidPluginID                  = errors.New("invalid plugin id")                       // the plugin id is invalid
	ErrInvalidPluginCapability          = errors.New("invalid plugin capability")               // the capability is unknown
	ErrInvalidPluginEvent               = errors.New("invalid plugin event")                    // the event topic is unknown
	ErrInvalidPluginSlot                = errors.New("invalid plugin slot")                     // the ui slot is unknown
	ErrPluginSchemaVersion              = errors.New("unsupported plugin schema version")       // schemaVersion is not supported
	ErrPluginAPIIncompatible            = errors.New("incompatible plugin api")                 // requires.pluginApi is not ^1
	ErrInvalidExtensionDetails          = errors.New("invalid extension details")               // the extension node is invalid
	ErrPluginGraphSchema                = errors.New("invalid plugin graph schema")             // declared graph schema is invalid
	ErrPluginNotActive                  = errors.New("plugin is not active")                    // the plugin is disabled or missing
	ErrPluginConfigInvalid              = errors.New("invalid plugin config")                   // activation config failed schema validation
	ErrPluginGraphBinding               = errors.New("invalid plugin graph binding")            // foreign kind binding is missing or incompatible
	ErrPluginRelationCardinality        = errors.New("plugin relation cardinality violated")    // declared cardinality would be exceeded
)
