// Code generated by "enumer -type=IssueStatus -trimprefix=IssueStatus -text -transform=snake -output=issue_status_gen.go"; DO NOT EDIT.

package model

import (
	"fmt"
	"strings"
)

const _IssueStatusName = "openin_progressblockedreviewdoneclosed"

var _IssueStatusIndex = [...]uint8{0, 4, 15, 22, 28, 32, 38}

const _IssueStatusLowerName = "openin_progressblockedreviewdoneclosed"

func (i IssueStatus) String() string {
	i -= 1
	if i >= IssueStatus(len(_IssueStatusIndex)-1) {
		return fmt.Sprintf("IssueStatus(%d)", i+1)
	}
	return _IssueStatusName[_IssueStatusIndex[i]:_IssueStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _IssueStatusNoOp() {
	var x [1]struct{}
	_ = x[IssueStatusOpen-(1)]
	_ = x[IssueStatusInProgress-(2)]
	_ = x[IssueStatusBlocked-(3)]
	_ = x[IssueStatusReview-(4)]
	_ = x[IssueStatusDone-(5)]
	_ = x[IssueStatusClosed-(6)]
}

var _IssueStatusValues = []IssueStatus{IssueStatusOpen, IssueStatusInProgress, IssueStatusBlocked, IssueStatusReview, IssueStatusDone, IssueStatusClosed}

var _IssueStatusNameToValueMap = map[string]IssueStatus{
	_IssueStatusName[0:4]:        IssueStatusOpen,
	_IssueStatusLowerName[0:4]:   IssueStatusOpen,
	_IssueStatusName[4:15]:       IssueStatusInProgress,
	_IssueStatusLowerName[4:15]:  IssueStatusInProgress,
	_IssueStatusName[15:22]:      IssueStatusBlocked,
	_IssueStatusLowerName[15:22]: IssueStatusBlocked,
	_IssueStatusName[22:28]:      IssueStatusReview,
	_IssueStatusLowerName[22:28]: IssueStatusReview,
	_IssueStatusName[28:32]:      IssueStatusDone,
	_IssueStatusLowerName[28:32]: IssueStatusDone,
	_IssueStatusName[32:38]:      IssueStatusClosed,
	_IssueStatusLowerName[32:38]: IssueStatusClosed,
}

var _IssueStatusNames = []string{
	_IssueStatusName[0:4],
	_IssueStatusName[4:15],
	_IssueStatusName[15:22],
	_IssueStatusName[22:28],
	_IssueStatusName[28:32],
	_IssueStatusName[32:38],
}

// IssueStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func IssueStatusString(s string) (IssueStatus, error) {
	if val, ok := _IssueStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _IssueStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to IssueStatus values", s)
}

// IssueStatusValues returns all values of the enum
func IssueStatusValues() []IssueStatus {
	return _IssueStatusValues
}

// IssueStatusStrings returns a slice of all String values of the enum
func IssueStatusStrings() []string {
	strs := make([]string, len(_IssueStatusNames))
	copy(strs, _IssueStatusNames)
	return strs
}

// IsAIssueStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i IssueStatus) IsAIssueStatus() bool {
	for _, v := range _IssueStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for IssueStatus
func (i IssueStatus) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for IssueStatus
func (i *IssueStatus) UnmarshalText(text []byte) error {
	var err error
	*i, err = IssueStatusString(string(text))
	return err
}
