// Code generated by "enumer -type=IssueRelationKind -text -transform=noop -linecomment -output=issue_relation_kind_gen.go"; DO NOT EDIT.

package model

import (
	"fmt"
	"strings"
)

const _IssueRelationKindName = "blocked byblocksdepends onduplicated byduplicatesrelated tosubtask of"

var _IssueRelationKindIndex = [...]uint8{0, 10, 16, 26, 39, 49, 59, 69}

const _IssueRelationKindLowerName = "blocked byblocksdepends onduplicated byduplicatesrelated tosubtask of"

func (i IssueRelationKind) String() string {
	i -= 1
	if i >= IssueRelationKind(len(_IssueRelationKindIndex)-1) {
		return fmt.Sprintf("IssueRelationKind(%d)", i+1)
	}
	return _IssueRelationKindName[_IssueRelationKindIndex[i]:_IssueRelationKindIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _IssueRelationKindNoOp() {
	var x [1]struct{}
	_ = x[IssueRelationKindBlockedBy-(1)]
	_ = x[IssueRelationKindBlocks-(2)]
	_ = x[IssueRelationKindDependsOn-(3)]
	_ = x[IssueRelationKindDuplicatedBy-(4)]
	_ = x[IssueRelationKindDuplicates-(5)]
	_ = x[IssueRelationKindRelatedTo-(6)]
	_ = x[IssueRelationKindSubtaskOf-(7)]
}

var _IssueRelationKindValues = []IssueRelationKind{IssueRelationKindBlockedBy, IssueRelationKindBlocks, IssueRelationKindDependsOn, IssueRelationKindDuplicatedBy, IssueRelationKindDuplicates, IssueRelationKindRelatedTo, IssueRelationKindSubtaskOf}

var _IssueRelationKindNameToValueMap = map[string]IssueRelationKind{
	_IssueRelationKindName[0:10]:       IssueRelationKindBlockedBy,
	_IssueRelationKindLowerName[0:10]:  IssueRelationKindBlockedBy,
	_IssueRelationKindName[10:16]:      IssueRelationKindBlocks,
	_IssueRelationKindLowerName[10:16]: IssueRelationKindBlocks,
	_IssueRelationKindName[16:26]:      IssueRelationKindDependsOn,
	_IssueRelationKindLowerName[16:26]: IssueRelationKindDependsOn,
	_IssueRelationKindName[26:39]:      IssueRelationKindDuplicatedBy,
	_IssueRelationKindLowerName[26:39]: IssueRelationKindDuplicatedBy,
	_IssueRelationKindName[39:49]:      IssueRelationKindDuplicates,
	_IssueRelationKindLowerName[39:49]: IssueRelationKindDuplicates,
	_IssueRelationKindName[49:59]:      IssueRelationKindRelatedTo,
	_IssueRelationKindLowerName[49:59]: IssueRelationKindRelatedTo,
	_IssueRelationKindName[59:69]:      IssueRelationKindSubtaskOf,
	_IssueRelationKindLowerName[59:69]: IssueRelationKindSubtaskOf,
}

var _IssueRelationKindNames = []string{
	_IssueRelationKindName[0:10],
	_IssueRelationKindName[10:16],
	_IssueRelationKindName[16:26],
	_IssueRelationKindName[26:39],
	_IssueRelationKindName[39:49],
	_IssueRelationKindName[49:59],
	_IssueRelationKindName[59:69],
}

// IssueRelationKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func IssueRelationKindString(s string) (IssueRelationKind, error) {
	if val, ok := _IssueRelationKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _IssueRelationKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to IssueRelationKind values", s)
}

// IssueRelationKindValues returns all values of the enum
func IssueRelationKindValues() []IssueRelationKind {
	return _IssueRelationKindValues
}

// IssueRelationKindStrings returns a slice of all String values of the enum
func IssueRelationKindStrings() []string {
	strs := make([]string, len(_IssueRelationKindNames))
	copy(strs, _IssueRelationKindNames)
	return strs
}

// IsAIssueRelationKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i IssueRelationKind) IsAIssueRelationKind() bool {
	for _, v := range _IssueRelationKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for IssueRelationKind
func (i IssueRelationKind) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for IssueRelationKind
func (i *IssueRelationKind) UnmarshalText(text []byte) error {
	var err error
	*i, err = IssueRelationKindString(string(text))
	return err
}
