// Code generated by "enumer -type=IssueResolution -text -transform=noop -linecomment -output=issue_resolution_gen.go"; DO NOT EDIT.

package model

import (
	"fmt"
	"strings"
)

const _IssueResolutionName = "nonefixedduplicatewon't fixinvalidincompletecannot reproduce"

var _IssueResolutionIndex = [...]uint8{0, 4, 9, 18, 27, 34, 44, 60}

const _IssueResolutionLowerName = "nonefixedduplicatewon't fixinvalidincompletecannot reproduce"

func (i IssueResolution) String() string {
	i -= 1
	if i >= IssueResolution(len(_IssueResolutionIndex)-1) {
		return fmt.Sprintf("IssueResolution(%d)", i+1)
	}
	return _IssueResolutionName[_IssueResolutionIndex[i]:_IssueResolutionIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _IssueResolutionNoOp() {
	var x [1]struct{}
	_ = x[IssueResolutionNone-(1)]
	_ = x[IssueResolutionFixed-(2)]
	_ = x[IssueResolutionDuplicate-(3)]
	_ = x[IssueResolutionWontFix-(4)]
	_ = x[IssueResolutionInvalid-(5)]
	_ = x[IssueResolutionIncomplete-(6)]
	_ = x[IssueResolutionCannotReproduce-(7)]
}

var _IssueResolutionValues = []IssueResolution{IssueResolutionNone, IssueResolutionFixed, IssueResolutionDuplicate, IssueResolutionWontFix, IssueResolutionInvalid, IssueResolutionIncomplete, IssueResolutionCannotReproduce}

var _IssueResolutionNameToValueMap = map[string]IssueResolution{
	_IssueResolutionName[0:4]:        IssueResolutionNone,
	_IssueResolutionLowerName[0:4]:   IssueResolutionNone,
	_IssueResolutionName[4:9]:        IssueResolutionFixed,
	_IssueResolutionLowerName[4:9]:   IssueResolutionFixed,
	_IssueResolutionName[9:18]:       IssueResolutionDuplicate,
	_IssueResolutionLowerName[9:18]:  IssueResolutionDuplicate,
	_IssueResolutionName[18:27]:      IssueResolutionWontFix,
	_IssueResolutionLowerName[18:27]: IssueResolutionWontFix,
	_IssueResolutionName[27:34]:      IssueResolutionInvalid,
	_IssueResolutionLowerName[27:34]: IssueResolutionInvalid,
	_IssueResolutionName[34:44]:      IssueResolutionIncomplete,
	_IssueResolutionLowerName[34:44]: IssueResolutionIncomplete,
	_IssueResolutionName[44:60]:      IssueResolutionCannotReproduce,
	_IssueResolutionLowerName[44:60]: IssueResolutionCannotReproduce,
}

var _IssueResolutionNames = []string{
	_IssueResolutionName[0:4],
	_IssueResolutionName[4:9],
	_IssueResolutionName[9:18],
	_IssueResolutionName[18:27],
	_IssueResolutionName[27:34],
	_IssueResolutionName[34:44],
	_IssueResolutionName[44:60],
}

// IssueResolutionString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func IssueResolutionString(s string) (IssueResolution, error) {
	if val, ok := _IssueResolutionNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _IssueResolutionNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to IssueResolution values", s)
}

// IssueResolutionValues returns all values of the enum
func IssueResolutionValues() []IssueResolution {
	return _IssueResolutionValues
}

// IssueResolutionStrings returns a slice of all String values of the enum
func IssueResolutionStrings() []string {
	strs := make([]string, len(_IssueResolutionNames))
	copy(strs, _IssueResolutionNames)
	return strs
}

// IsAIssueResolution returns "true" if the value is listed in the enum definition. "false" otherwise
func (i IssueResolution) IsAIssueResolution() bool {
	for _, v := range _IssueResolutionValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for IssueResolution
func (i IssueResolution) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for IssueResolution
func (i *IssueResolution) UnmarshalText(text []byte) error {
	var err error
	*i, err = IssueResolutionString(string(text))
	return err
}
