package model

const (
	LanguageAA Language = iota + 1 // aa
	LanguageAB                     // ab
	LanguageAE                     // ae
	LanguageAF                     // af
	LanguageAK                     // ak
	LanguageAM                     // am
	LanguageAN                     // an
	LanguageAR                     // ar
	LanguageAS                     // as
	LanguageAV                     // av
	LanguageAY                     // ay
	LanguageAZ                     // az
	LanguageBA                     // ba
	LanguageBE                     // be
	LanguageBG                     // bg
	LanguageBH                     // bh
	LanguageBI                     // bi
	LanguageBM                     // bm
	LanguageBN                     // bn
	LanguageBO                     // bo
	LanguageBR                     // br
	LanguageBS                     // bs
	LanguageCA                     // ca
	LanguageCE                     // ce
	LanguageCH                     // ch
	LanguageCO                     // co
	LanguageCR                     // cr
	LanguageCS                     // cs
	LanguageCU                     // cu
	LanguageCV                     // cv
	LanguageCY                     // cy
	LanguageDA                     // da
	LanguageDE                     // de
	LanguageDV                     // dv
	LanguageDZ                     // dz
	LanguageEE                     // ee
	LanguageEL                     // el
	LanguageEN                     // en
	LanguageEO                     // eo
	LanguageES                     // es
	LanguageET                     // et
	LanguageEU                     // eu
	LanguageFA                     // fa
	LanguageFF                     // ff
	LanguageFI                     // fi
	LanguageFJ                     // fj
	LanguageFO                     // fo
	LanguageFR                     // fr
	LanguageFY                     // fy
	LanguageGA                     // ga
	LanguageGD                     // gd
	LanguageGL                     // gl
	LanguageGN                     // gn
	LanguageGU                     // gu
	LanguageGV                     // gv
	LanguageHA                     // ha
	LanguageHE                     // he
	LanguageHI                     // hi
	LanguageHO                     // ho
	LanguageHR                     // hr
	LanguageHT                     // ht
	LanguageHU                     // hu
	LanguageHY                     // hy
	LanguageHZ                     // hz
	LanguageIA                     // ia
	LanguageID                     // id
	LanguageIE                     // ie
	LanguageIG                     // ig
	LanguageII                     // ii
	LanguageIK                     // ik
	LanguageIO                     // io
	LanguageIS                     // is
	LanguageIT                     // it
	LanguageIU                     // iu
	LanguageJA                     // ja
	LanguageJV                     // jv
	LanguageKA                     // ka
	LanguageKG                     // kg
	LanguageKI                     // ki
	LanguageKJ                     // kj
	LanguageKK                     // kk
	LanguageKL                     // kl
	LanguageKM                     // km
	LanguageKN                     // kn
	LanguageKO                     // ko
	LanguageKR                     // kr
	LanguageKS                     // ks
	LanguageKU                     // ku
	LanguageKV                     // kv
	LanguageKW                     // kw
	LanguageKY                     // ky
	LanguageLA                     // la
	LanguageLB                     // lb
	LanguageLG                     // lg
	LanguageLI                     // li
	LanguageLN                     // ln
	LanguageLO                     // lo
	LanguageLT                     // lt
	LanguageLU                     // lu
	LanguageLV                     // lv
	LanguageMG                     // mg
	LanguageMH                     // mh
	LanguageMI                     // mi
	LanguageMK                     // mk
	LanguageML                     // ml
	LanguageMN                     // mn
	LanguageMR                     // mr
	LanguageMS                     // ms
	LanguageMT                     // mt
	LanguageMY                     // my
	LanguageNA                     // na
	LanguageNB                     // nb
	LanguageND                     // nd
	LanguageNE                     // ne
	LanguageNG                     // ng
	LanguageNL                     // nl
	LanguageNN                     // nn
	LanguageNO                     // no
	LanguageNR                     // nr
	LanguageNV                     // nv
	LanguageNY                     // ny
	LanguageOC                     // oc
	LanguageOJ                     // oj
	LanguageOM                     // om
	LanguageOR                     // or
	LanguageOS                     // os
	LanguagePA                     // pa
	LanguagePI                     // pi
	LanguagePL                     // pl
	LanguagePS                     // ps
	LanguagePT                     // pt
	LanguageQU                     // qu
	LanguageRM                     // rm
	LanguageRN                     // rn
	LanguageRO                     // ro
	LanguageRU                     // ru
	LanguageRW                     // rw
	LanguageSA                     // sa
	LanguageSC                     // sc
	LanguageSD                     // sd
	LanguageSE                     // se
	LanguageSG                     // sg
	LanguageSI                     // si
	LanguageSK                     // sk
	LanguageSL                     // sl
	LanguageSM                     // sm
	LanguageSN                     // sn
	LanguageSO                     // so
	LanguageSQ                     // sq
	LanguageSR                     // sr
	LanguageSS                     // ss
	LanguageST                     // st
	LanguageSU                     // su
	LanguageSV                     // sv
	LanguageSW                     // sw
	LanguageTA                     // ta
	LanguageTE                     // te
	LanguageTG                     // tg
	LanguageTH                     // th
	LanguageTI                     // ti
	LanguageTK                     // tk
	LanguageTL                     // tl
	LanguageTN                     // tn
	LanguageTO                     // to
	LanguageTR                     // tr
	LanguageTS                     // ts
	LanguageTT                     // tt
	LanguageTW                     // tw
	LanguageTY                     // ty
	LanguageUG                     // ug
	LanguageUK                     // uk
	LanguageUR                     // ur
	LanguageUZ                     // uz
	LanguageVE                     // ve
	LanguageVI                     // vi
	LanguageVO                     // vo
	LanguageWA                     // wa
	LanguageWO                     // wo
	LanguageXH                     // xh
	LanguageYI                     // yi
	LanguageYO                     // yo
	LanguageZA                     // za
	LanguageZH                     // zh
	LanguageZU                     // zu
)

// Language represents a Language ISO code.
//
//go:generate go tool enumer -type=Language -text -transform=noop -linecomment -output=language_gen.go
type Language uint8
