// Code generated by "enumer -type=PluginConfigFieldType -text -transform=noop -linecomment -output=plugin_config_field_type_gen.go"; DO NOT EDIT.

package model

import (
	"fmt"
	"strings"
)

const _PluginConfigFieldTypeName = "unknownstringintegerbooleangraph_binding"

var _PluginConfigFieldTypeIndex = [...]uint8{0, 7, 13, 20, 27, 40}

const _PluginConfigFieldTypeLowerName = "unknownstringintegerbooleangraph_binding"

func (i PluginConfigFieldType) String() string {
	if i >= PluginConfigFieldType(len(_PluginConfigFieldTypeIndex)-1) {
		return fmt.Sprintf("PluginConfigFieldType(%d)", i)
	}
	return _PluginConfigFieldTypeName[_PluginConfigFieldTypeIndex[i]:_PluginConfigFieldTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _PluginConfigFieldTypeNoOp() {
	var x [1]struct{}
	_ = x[PluginConfigFieldTypeUnknown-(0)]
	_ = x[PluginConfigFieldTypeStr-(1)]
	_ = x[PluginConfigFieldTypeInteger-(2)]
	_ = x[PluginConfigFieldTypeBoolean-(3)]
	_ = x[PluginConfigFieldTypeGraphBinding-(4)]
}

var _PluginConfigFieldTypeValues = []PluginConfigFieldType{PluginConfigFieldTypeUnknown, PluginConfigFieldTypeStr, PluginConfigFieldTypeInteger, PluginConfigFieldTypeBoolean, PluginConfigFieldTypeGraphBinding}

var _PluginConfigFieldTypeNameToValueMap = map[string]PluginConfigFieldType{
	_PluginConfigFieldTypeName[0:7]:        PluginConfigFieldTypeUnknown,
	_PluginConfigFieldTypeLowerName[0:7]:   PluginConfigFieldTypeUnknown,
	_PluginConfigFieldTypeName[7:13]:       PluginConfigFieldTypeStr,
	_PluginConfigFieldTypeLowerName[7:13]:  PluginConfigFieldTypeStr,
	_PluginConfigFieldTypeName[13:20]:      PluginConfigFieldTypeInteger,
	_PluginConfigFieldTypeLowerName[13:20]: PluginConfigFieldTypeInteger,
	_PluginConfigFieldTypeName[20:27]:      PluginConfigFieldTypeBoolean,
	_PluginConfigFieldTypeLowerName[20:27]: PluginConfigFieldTypeBoolean,
	_PluginConfigFieldTypeName[27:40]:      PluginConfigFieldTypeGraphBinding,
	_PluginConfigFieldTypeLowerName[27:40]: PluginConfigFieldTypeGraphBinding,
}

var _PluginConfigFieldTypeNames = []string{
	_PluginConfigFieldTypeName[0:7],
	_PluginConfigFieldTypeName[7:13],
	_PluginConfigFieldTypeName[13:20],
	_PluginConfigFieldTypeName[20:27],
	_PluginConfigFieldTypeName[27:40],
}

// PluginConfigFieldTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func PluginConfigFieldTypeString(s string) (PluginConfigFieldType, error) {
	if val, ok := _PluginConfigFieldTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _PluginConfigFieldTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to PluginConfigFieldType values", s)
}

// PluginConfigFieldTypeValues returns all values of the enum
func PluginConfigFieldTypeValues() []PluginConfigFieldType {
	return _PluginConfigFieldTypeValues
}

// PluginConfigFieldTypeStrings returns a slice of all String values of the enum
func PluginConfigFieldTypeStrings() []string {
	strs := make([]string, len(_PluginConfigFieldTypeNames))
	copy(strs, _PluginConfigFieldTypeNames)
	return strs
}

// IsAPluginConfigFieldType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i PluginConfigFieldType) IsAPluginConfigFieldType() bool {
	for _, v := range _PluginConfigFieldTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for PluginConfigFieldType
func (i PluginConfigFieldType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for PluginConfigFieldType
func (i *PluginConfigFieldType) UnmarshalText(text []byte) error {
	var err error
	*i, err = PluginConfigFieldTypeString(string(text))
	return err
}
