// Code generated by "enumer -type=PluginGraphPropertyType -text -transform=noop -linecomment -output=plugin_graph_property_type_gen.go"; DO NOT EDIT.

package model

import (
	"fmt"
	"strings"
)

const _PluginGraphPropertyTypeName = "unknownstringintegerdecimalbooleandatedatetime"

var _PluginGraphPropertyTypeIndex = [...]uint8{0, 7, 13, 20, 27, 34, 38, 46}

const _PluginGraphPropertyTypeLowerName = "unknownstringintegerdecimalbooleandatedatetime"

func (i PluginGraphPropertyType) String() string {
	if i >= PluginGraphPropertyType(len(_PluginGraphPropertyTypeIndex)-1) {
		return fmt.Sprintf("PluginGraphPropertyType(%d)", i)
	}
	return _PluginGraphPropertyTypeName[_PluginGraphPropertyTypeIndex[i]:_PluginGraphPropertyTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _PluginGraphPropertyTypeNoOp() {
	var x [1]struct{}
	_ = x[PluginGraphPropertyTypeUnknown-(0)]
	_ = x[PluginGraphPropertyTypeStr-(1)]
	_ = x[PluginGraphPropertyTypeInteger-(2)]
	_ = x[PluginGraphPropertyTypeDecimal-(3)]
	_ = x[PluginGraphPropertyTypeBoolean-(4)]
	_ = x[PluginGraphPropertyTypeDate-(5)]
	_ = x[PluginGraphPropertyTypeDateTime-(6)]
}

var _PluginGraphPropertyTypeValues = []PluginGraphPropertyType{PluginGraphPropertyTypeUnknown, PluginGraphPropertyTypeStr, PluginGraphPropertyTypeInteger, PluginGraphPropertyTypeDecimal, PluginGraphPropertyTypeBoolean, PluginGraphPropertyTypeDate, PluginGraphPropertyTypeDateTime}

var _PluginGraphPropertyTypeNameToValueMap = map[string]PluginGraphPropertyType{
	_PluginGraphPropertyTypeName[0:7]:        PluginGraphPropertyTypeUnknown,
	_PluginGraphPropertyTypeLowerName[0:7]:   PluginGraphPropertyTypeUnknown,
	_PluginGraphPropertyTypeName[7:13]:       PluginGraphPropertyTypeStr,
	_PluginGraphPropertyTypeLowerName[7:13]:  PluginGraphPropertyTypeStr,
	_PluginGraphPropertyTypeName[13:20]:      PluginGraphPropertyTypeInteger,
	_PluginGraphPropertyTypeLowerName[13:20]: PluginGraphPropertyTypeInteger,
	_PluginGraphPropertyTypeName[20:27]:      PluginGraphPropertyTypeDecimal,
	_PluginGraphPropertyTypeLowerName[20:27]: PluginGraphPropertyTypeDecimal,
	_PluginGraphPropertyTypeName[27:34]:      PluginGraphPropertyTypeBoolean,
	_PluginGraphPropertyTypeLowerName[27:34]: PluginGraphPropertyTypeBoolean,
	_PluginGraphPropertyTypeName[34:38]:      PluginGraphPropertyTypeDate,
	_PluginGraphPropertyTypeLowerName[34:38]: PluginGraphPropertyTypeDate,
	_PluginGraphPropertyTypeName[38:46]:      PluginGraphPropertyTypeDateTime,
	_PluginGraphPropertyTypeLowerName[38:46]: PluginGraphPropertyTypeDateTime,
}

var _PluginGraphPropertyTypeNames = []string{
	_PluginGraphPropertyTypeName[0:7],
	_PluginGraphPropertyTypeName[7:13],
	_PluginGraphPropertyTypeName[13:20],
	_PluginGraphPropertyTypeName[20:27],
	_PluginGraphPropertyTypeName[27:34],
	_PluginGraphPropertyTypeName[34:38],
	_PluginGraphPropertyTypeName[38:46],
}

// PluginGraphPropertyTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func PluginGraphPropertyTypeString(s string) (PluginGraphPropertyType, error) {
	if val, ok := _PluginGraphPropertyTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _PluginGraphPropertyTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to PluginGraphPropertyType values", s)
}

// PluginGraphPropertyTypeValues returns all values of the enum
func PluginGraphPropertyTypeValues() []PluginGraphPropertyType {
	return _PluginGraphPropertyTypeValues
}

// PluginGraphPropertyTypeStrings returns a slice of all String values of the enum
func PluginGraphPropertyTypeStrings() []string {
	strs := make([]string, len(_PluginGraphPropertyTypeNames))
	copy(strs, _PluginGraphPropertyTypeNames)
	return strs
}

// IsAPluginGraphPropertyType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i PluginGraphPropertyType) IsAPluginGraphPropertyType() bool {
	for _, v := range _PluginGraphPropertyTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for PluginGraphPropertyType
func (i PluginGraphPropertyType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for PluginGraphPropertyType
func (i *PluginGraphPropertyType) UnmarshalText(text []byte) error {
	var err error
	*i, err = PluginGraphPropertyTypeString(string(text))
	return err
}
