// Code generated by "enumer -type=PluginGraphCardinality -text -transform=noop -linecomment -output=plugin_graph_cardinality_gen.go"; DO NOT EDIT.

package model

import (
	"fmt"
	"strings"
)

const _PluginGraphCardinalityName = "unknownone-to-oneone-to-manymany-to-onemany-to-many"

var _PluginGraphCardinalityIndex = [...]uint8{0, 7, 17, 28, 39, 51}

const _PluginGraphCardinalityLowerName = "unknownone-to-oneone-to-manymany-to-onemany-to-many"

func (i PluginGraphCardinality) String() string {
	if i >= PluginGraphCardinality(len(_PluginGraphCardinalityIndex)-1) {
		return fmt.Sprintf("PluginGraphCardinality(%d)", i)
	}
	return _PluginGraphCardinalityName[_PluginGraphCardinalityIndex[i]:_PluginGraphCardinalityIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _PluginGraphCardinalityNoOp() {
	var x [1]struct{}
	_ = x[PluginGraphCardinalityUnknown-(0)]
	_ = x[PluginGraphCardinalityOneToOne-(1)]
	_ = x[PluginGraphCardinalityOneToMany-(2)]
	_ = x[PluginGraphCardinalityManyToOne-(3)]
	_ = x[PluginGraphCardinalityManyToMany-(4)]
}

var _PluginGraphCardinalityValues = []PluginGraphCardinality{PluginGraphCardinalityUnknown, PluginGraphCardinalityOneToOne, PluginGraphCardinalityOneToMany, PluginGraphCardinalityManyToOne, PluginGraphCardinalityManyToMany}

var _PluginGraphCardinalityNameToValueMap = map[string]PluginGraphCardinality{
	_PluginGraphCardinalityName[0:7]:        PluginGraphCardinalityUnknown,
	_PluginGraphCardinalityLowerName[0:7]:   PluginGraphCardinalityUnknown,
	_PluginGraphCardinalityName[7:17]:       PluginGraphCardinalityOneToOne,
	_PluginGraphCardinalityLowerName[7:17]:  PluginGraphCardinalityOneToOne,
	_PluginGraphCardinalityName[17:28]:      PluginGraphCardinalityOneToMany,
	_PluginGraphCardinalityLowerName[17:28]: PluginGraphCardinalityOneToMany,
	_PluginGraphCardinalityName[28:39]:      PluginGraphCardinalityManyToOne,
	_PluginGraphCardinalityLowerName[28:39]: PluginGraphCardinalityManyToOne,
	_PluginGraphCardinalityName[39:51]:      PluginGraphCardinalityManyToMany,
	_PluginGraphCardinalityLowerName[39:51]: PluginGraphCardinalityManyToMany,
}

var _PluginGraphCardinalityNames = []string{
	_PluginGraphCardinalityName[0:7],
	_PluginGraphCardinalityName[7:17],
	_PluginGraphCardinalityName[17:28],
	_PluginGraphCardinalityName[28:39],
	_PluginGraphCardinalityName[39:51],
}

// PluginGraphCardinalityString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func PluginGraphCardinalityString(s string) (PluginGraphCardinality, error) {
	if val, ok := _PluginGraphCardinalityNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _PluginGraphCardinalityNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to PluginGraphCardinality values", s)
}

// PluginGraphCardinalityValues returns all values of the enum
func PluginGraphCardinalityValues() []PluginGraphCardinality {
	return _PluginGraphCardinalityValues
}

// PluginGraphCardinalityStrings returns a slice of all String values of the enum
func PluginGraphCardinalityStrings() []string {
	strs := make([]string, len(_PluginGraphCardinalityNames))
	copy(strs, _PluginGraphCardinalityNames)
	return strs
}

// IsAPluginGraphCardinality returns "true" if the value is listed in the enum definition. "false" otherwise
func (i PluginGraphCardinality) IsAPluginGraphCardinality() bool {
	for _, v := range _PluginGraphCardinalityValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for PluginGraphCardinality
func (i PluginGraphCardinality) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for PluginGraphCardinality
func (i *PluginGraphCardinality) UnmarshalText(text []byte) error {
	var err error
	*i, err = PluginGraphCardinalityString(string(text))
	return err
}
