// Code generated by "enumer -type=HealthStatus -trimprefix=HealthStatus -text -transform=snake -output=system_health_status_gen.go"; DO NOT EDIT.

package model

import (
	"fmt"
	"strings"
)

const _HealthStatusName = "unknownhealthyunhealthy"

var _HealthStatusIndex = [...]uint8{0, 7, 14, 23}

const _HealthStatusLowerName = "unknownhealthyunhealthy"

func (i HealthStatus) String() string {
	if i >= HealthStatus(len(_HealthStatusIndex)-1) {
		return fmt.Sprintf("HealthStatus(%d)", i)
	}
	return _HealthStatusName[_HealthStatusIndex[i]:_HealthStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _HealthStatusNoOp() {
	var x [1]struct{}
	_ = x[HealthStatusUnknown-(0)]
	_ = x[HealthStatusHealthy-(1)]
	_ = x[HealthStatusUnhealthy-(2)]
}

var _HealthStatusValues = []HealthStatus{HealthStatusUnknown, HealthStatusHealthy, HealthStatusUnhealthy}

var _HealthStatusNameToValueMap = map[string]HealthStatus{
	_HealthStatusName[0:7]:        HealthStatusUnknown,
	_HealthStatusLowerName[0:7]:   HealthStatusUnknown,
	_HealthStatusName[7:14]:       HealthStatusHealthy,
	_HealthStatusLowerName[7:14]:  HealthStatusHealthy,
	_HealthStatusName[14:23]:      HealthStatusUnhealthy,
	_HealthStatusLowerName[14:23]: HealthStatusUnhealthy,
}

var _HealthStatusNames = []string{
	_HealthStatusName[0:7],
	_HealthStatusName[7:14],
	_HealthStatusName[14:23],
}

// HealthStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func HealthStatusString(s string) (HealthStatus, error) {
	if val, ok := _HealthStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _HealthStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to HealthStatus values", s)
}

// HealthStatusValues returns all values of the enum
func HealthStatusValues() []HealthStatus {
	return _HealthStatusValues
}

// HealthStatusStrings returns a slice of all String values of the enum
func HealthStatusStrings() []string {
	strs := make([]string, len(_HealthStatusNames))
	copy(strs, _HealthStatusNames)
	return strs
}

// IsAHealthStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i HealthStatus) IsAHealthStatus() bool {
	for _, v := range _HealthStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for HealthStatus
func (i HealthStatus) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for HealthStatus
func (i *HealthStatus) UnmarshalText(text []byte) error {
	var err error
	*i, err = HealthStatusString(string(text))
	return err
}
