// Code generated by "enumer -type=UserStatus -trimprefix=UserStatus -text -transform=snake -output=user_status_gen.go"; DO NOT EDIT.

package model

import (
	"fmt"
	"strings"
)

const _UserStatusName = "activependinginactivedeleted"

var _UserStatusIndex = [...]uint8{0, 6, 13, 21, 28}

const _UserStatusLowerName = "activependinginactivedeleted"

func (i UserStatus) String() string {
	i -= 1
	if i >= UserStatus(len(_UserStatusIndex)-1) {
		return fmt.Sprintf("UserStatus(%d)", i+1)
	}
	return _UserStatusName[_UserStatusIndex[i]:_UserStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _UserStatusNoOp() {
	var x [1]struct{}
	_ = x[UserStatusActive-(1)]
	_ = x[UserStatusPending-(2)]
	_ = x[UserStatusInactive-(3)]
	_ = x[UserStatusDeleted-(4)]
}

var _UserStatusValues = []UserStatus{UserStatusActive, UserStatusPending, UserStatusInactive, UserStatusDeleted}

var _UserStatusNameToValueMap = map[string]UserStatus{
	_UserStatusName[0:6]:        UserStatusActive,
	_UserStatusLowerName[0:6]:   UserStatusActive,
	_UserStatusName[6:13]:       UserStatusPending,
	_UserStatusLowerName[6:13]:  UserStatusPending,
	_UserStatusName[13:21]:      UserStatusInactive,
	_UserStatusLowerName[13:21]: UserStatusInactive,
	_UserStatusName[21:28]:      UserStatusDeleted,
	_UserStatusLowerName[21:28]: UserStatusDeleted,
}

var _UserStatusNames = []string{
	_UserStatusName[0:6],
	_UserStatusName[6:13],
	_UserStatusName[13:21],
	_UserStatusName[21:28],
}

// UserStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func UserStatusString(s string) (UserStatus, error) {
	if val, ok := _UserStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _UserStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to UserStatus values", s)
}

// UserStatusValues returns all values of the enum
func UserStatusValues() []UserStatus {
	return _UserStatusValues
}

// UserStatusStrings returns a slice of all String values of the enum
func UserStatusStrings() []string {
	strs := make([]string, len(_UserStatusNames))
	copy(strs, _UserStatusNames)
	return strs
}

// IsAUserStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i UserStatus) IsAUserStatus() bool {
	for _, v := range _UserStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for UserStatus
func (i UserStatus) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for UserStatus
func (i *UserStatus) UnmarshalText(text []byte) error {
	var err error
	*i, err = UserStatusString(string(text))
	return err
}
