log:
  level: "info"

license:
  file: "configs/development/license.gen.key"

tls:
  cert_file: "configs/development/cert.gen.pem"
  key_file: "configs/development/key.gen.pem"

server:
  address: "0.0.0.0:35478"
  cors:
    enabled: true
    allowed_origins:
      - "http://127.0.0.1:3000"
    allowed_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    allowed_headers:
      - "*"
    allow_credentials: false
    max_age: 86400
  session:
    cookie_name: "elemo_session"
    max_age: 86400
    secure: false
  read_timeout: 10
  write_timeout: 5

graph_database:
  host: neo4j
  port: 7687
  username: neo4j
  password: neo4jsecret
  name: neo4j
  max_transaction_retry_time: 3
  max_connection_pool_size: 100
  max_connection_lifetime: 300
  connection_acquisition_timeout: 60
  socket_connect_timeout: 5
  socket_keepalive: true
  fetch_size: 250

relational_database:
  host: postgres
  port: 5432
  username: elemo
  password: pgsecret
  name: elemo
  max_connections: 100
  max_connection_lifetime: 300
  max_connection_idle_time: 10
  min_connections: 5

metrics_server:
  address: "0.0.0.0:35479"
  read_timeout: 10
  write_timeout: 5

tracing:
  service_name: 'elemo'
  collector_endpoint: 'otel_collector:4318'
  trace_ratio: 0.75
