log:
  level: "debug"

license:
  file: "configs/development/license.gen.key"

tls:
  cert_file: "configs/development/cert.local.gen.pem"
  key_file: "configs/development/key.local.gen.pem"

metrics_server:
  address: "127.0.0.1:35479"
  read_timeout: 10
  write_timeout: 5

server:
  address: "127.0.0.1:35478"
  cors:
    enabled: true
    allowed_origins:
      - "http://127.0.0.1:3000"
    allowed_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    allowed_headers:
      - "*"
    allow_credentials: false
    max_age: 86400
  read_timeout: 10
  write_timeout: 5

database:
  url: 'neo4j://localhost:7687'
  username: 'neo4j'
  password: 'neo4jsecret'
  name: 'neo4j'
  max_transaction_retry_time: 3
  max_connection_pool_size: 100
  max_connection_lifetime: 300
  connection_acquisition_timeout: 60
  socket_connect_timeout: 5
  socket_keepalive: true
  fetch_size: 250

tracing:
  service_name: 'elemo'
  collector_endpoint: '127.0.0.1:4318'
  trace_ratio: 0.75
