// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  type Options,
  v1DocumentDelete,
  v1DocumentGet,
  v1DocumentUpdate,
  v1FolderDelete,
  v1FolderGet,
  v1FolderUpdate,
  v1IssueDelete,
  v1IssueGet,
  v1IssueRelationDelete,
  v1IssueRelationsCreate,
  v1IssueRelationsGet,
  v1IssueRelationUpdate,
  v1IssuesDocumentsCreate,
  v1IssuesDocumentsGet,
  v1IssuesDocumentsRelate,
  v1IssuesDocumentsUnrelate,
  v1IssueUpdate,
  v1LabelsGet,
  v1NamespaceDelete,
  v1NamespaceGet,
  v1NamespacesDocumentsCreate,
  v1NamespacesDocumentsGet,
  v1NamespacesFoldersCreate,
  v1NamespacesFoldersGet,
  v1NamespacesIssuesGet,
  v1NamespacesIssuesKeyGet,
  v1NamespacesProjectsCreate,
  v1NamespacesProjectsGet,
  v1NamespaceUpdate,
  v1NotificationDelete,
  v1NotificationGet,
  v1NotificationsGet,
  v1NotificationUpdate,
  v1OrganizationDelete,
  v1OrganizationGet,
  v1OrganizationMemberInviteRevoke,
  v1OrganizationMemberRemove,
  v1OrganizationMembersAccept,
  v1OrganizationMembersAdd,
  v1OrganizationMembersGet,
  v1OrganizationMembersInvite,
  v1OrganizationRoleDelete,
  v1OrganizationRoleGet,
  v1OrganizationRoleMemberRemove,
  v1OrganizationRoleMembersAdd,
  v1OrganizationRoleMembersGet,
  v1OrganizationRolePermissionAdd,
  v1OrganizationRolePermissionRemove,
  v1OrganizationRolePermissionsGet,
  v1OrganizationRolesCreate,
  v1OrganizationRolesGet,
  v1OrganizationRoleUpdate,
  v1OrganizationsCreate,
  v1OrganizationsDocumentsCreate,
  v1OrganizationsDocumentsGet,
  v1OrganizationsFoldersCreate,
  v1OrganizationsFoldersGet,
  v1OrganizationsGet,
  v1OrganizationsNamespacesCreate,
  v1OrganizationsNamespacesGet,
  v1OrganizationUpdate,
  v1PermissionDelete,
  v1PermissionGet,
  v1PermissionHasRelations,
  v1PermissionHasSystemRole,
  v1PermissionResourceGet,
  v1PermissionsCreate,
  v1PermissionUpdate,
  v1ProjectDelete,
  v1ProjectGet,
  v1ProjectsDocumentsCreate,
  v1ProjectsDocumentsGet,
  v1ProjectsDocumentsRelate,
  v1ProjectsDocumentsUnrelate,
  v1ProjectsIssuesCreate,
  v1ProjectsIssuesGet,
  v1ProjectUpdate,
  v1SystemHealth,
  v1SystemHeartbeat,
  v1SystemLicense,
  v1SystemVersion,
  v1TodoDelete,
  v1TodoGet,
  v1TodosCreate,
  v1TodosGet,
  v1TodoUpdate,
  v1UserDelete,
  v1UserGet,
  v1UserRequestPasswordReset,
  v1UserResetPassword,
  v1UsersCreate,
  v1UsersGet,
  v1UsersIssuesGet,
  v1UserUpdate,
} from "../sdk.gen";
import type {
  V1DocumentDeleteData,
  V1DocumentDeleteError,
  V1DocumentDeleteResponse,
  V1DocumentGetData,
  V1DocumentGetError,
  V1DocumentGetResponse,
  V1DocumentUpdateData,
  V1DocumentUpdateError,
  V1DocumentUpdateResponse,
  V1FolderDeleteData,
  V1FolderDeleteError,
  V1FolderDeleteResponse,
  V1FolderGetData,
  V1FolderGetError,
  V1FolderGetResponse,
  V1FolderUpdateData,
  V1FolderUpdateError,
  V1FolderUpdateResponse,
  V1IssueDeleteData,
  V1IssueDeleteError,
  V1IssueDeleteResponse,
  V1IssueGetData,
  V1IssueGetError,
  V1IssueGetResponse,
  V1IssueRelationDeleteData,
  V1IssueRelationDeleteError,
  V1IssueRelationDeleteResponse,
  V1IssueRelationsCreateData,
  V1IssueRelationsCreateError,
  V1IssueRelationsCreateResponse,
  V1IssueRelationsGetData,
  V1IssueRelationsGetError,
  V1IssueRelationsGetResponse,
  V1IssueRelationUpdateData,
  V1IssueRelationUpdateError,
  V1IssueRelationUpdateResponse,
  V1IssuesDocumentsCreateData,
  V1IssuesDocumentsCreateError,
  V1IssuesDocumentsCreateResponse,
  V1IssuesDocumentsGetData,
  V1IssuesDocumentsGetError,
  V1IssuesDocumentsGetResponse,
  V1IssuesDocumentsRelateData,
  V1IssuesDocumentsRelateError,
  V1IssuesDocumentsRelateResponse,
  V1IssuesDocumentsUnrelateData,
  V1IssuesDocumentsUnrelateError,
  V1IssuesDocumentsUnrelateResponse,
  V1IssueUpdateData,
  V1IssueUpdateError,
  V1IssueUpdateResponse,
  V1LabelsGetData,
  V1LabelsGetError,
  V1LabelsGetResponse,
  V1NamespaceDeleteData,
  V1NamespaceDeleteError,
  V1NamespaceDeleteResponse,
  V1NamespaceGetData,
  V1NamespaceGetError,
  V1NamespaceGetResponse,
  V1NamespacesDocumentsCreateData,
  V1NamespacesDocumentsCreateError,
  V1NamespacesDocumentsCreateResponse,
  V1NamespacesDocumentsGetData,
  V1NamespacesDocumentsGetError,
  V1NamespacesDocumentsGetResponse,
  V1NamespacesFoldersCreateData,
  V1NamespacesFoldersCreateError,
  V1NamespacesFoldersCreateResponse,
  V1NamespacesFoldersGetData,
  V1NamespacesFoldersGetError,
  V1NamespacesFoldersGetResponse,
  V1NamespacesIssuesGetData,
  V1NamespacesIssuesGetError,
  V1NamespacesIssuesGetResponse,
  V1NamespacesIssuesKeyGetData,
  V1NamespacesIssuesKeyGetError,
  V1NamespacesIssuesKeyGetResponse,
  V1NamespacesProjectsCreateData,
  V1NamespacesProjectsCreateError,
  V1NamespacesProjectsCreateResponse,
  V1NamespacesProjectsGetData,
  V1NamespacesProjectsGetError,
  V1NamespacesProjectsGetResponse,
  V1NamespaceUpdateData,
  V1NamespaceUpdateError,
  V1NamespaceUpdateResponse,
  V1NotificationDeleteData,
  V1NotificationDeleteError,
  V1NotificationDeleteResponse,
  V1NotificationGetData,
  V1NotificationGetError,
  V1NotificationGetResponse,
  V1NotificationsGetData,
  V1NotificationsGetError,
  V1NotificationsGetResponse,
  V1NotificationUpdateData,
  V1NotificationUpdateError,
  V1NotificationUpdateResponse,
  V1OrganizationDeleteData,
  V1OrganizationDeleteError,
  V1OrganizationDeleteResponse,
  V1OrganizationGetData,
  V1OrganizationGetError,
  V1OrganizationGetResponse,
  V1OrganizationMemberInviteRevokeData,
  V1OrganizationMemberInviteRevokeError,
  V1OrganizationMemberInviteRevokeResponse,
  V1OrganizationMemberRemoveData,
  V1OrganizationMemberRemoveError,
  V1OrganizationMemberRemoveResponse,
  V1OrganizationMembersAcceptData,
  V1OrganizationMembersAcceptError,
  V1OrganizationMembersAcceptResponse,
  V1OrganizationMembersAddData,
  V1OrganizationMembersAddError,
  V1OrganizationMembersAddResponse,
  V1OrganizationMembersGetData,
  V1OrganizationMembersGetError,
  V1OrganizationMembersGetResponse,
  V1OrganizationMembersInviteData,
  V1OrganizationMembersInviteError,
  V1OrganizationMembersInviteResponse,
  V1OrganizationRoleDeleteData,
  V1OrganizationRoleDeleteError,
  V1OrganizationRoleDeleteResponse,
  V1OrganizationRoleGetData,
  V1OrganizationRoleGetError,
  V1OrganizationRoleGetResponse,
  V1OrganizationRoleMemberRemoveData,
  V1OrganizationRoleMemberRemoveError,
  V1OrganizationRoleMemberRemoveResponse,
  V1OrganizationRoleMembersAddData,
  V1OrganizationRoleMembersAddError,
  V1OrganizationRoleMembersAddResponse,
  V1OrganizationRoleMembersGetData,
  V1OrganizationRoleMembersGetError,
  V1OrganizationRoleMembersGetResponse,
  V1OrganizationRolePermissionAddData,
  V1OrganizationRolePermissionAddError,
  V1OrganizationRolePermissionAddResponse,
  V1OrganizationRolePermissionRemoveData,
  V1OrganizationRolePermissionRemoveError,
  V1OrganizationRolePermissionRemoveResponse,
  V1OrganizationRolePermissionsGetData,
  V1OrganizationRolePermissionsGetError,
  V1OrganizationRolePermissionsGetResponse,
  V1OrganizationRolesCreateData,
  V1OrganizationRolesCreateError,
  V1OrganizationRolesCreateResponse,
  V1OrganizationRolesGetData,
  V1OrganizationRolesGetError,
  V1OrganizationRolesGetResponse,
  V1OrganizationRoleUpdateData,
  V1OrganizationRoleUpdateError,
  V1OrganizationRoleUpdateResponse,
  V1OrganizationsCreateData,
  V1OrganizationsCreateError,
  V1OrganizationsCreateResponse,
  V1OrganizationsDocumentsCreateData,
  V1OrganizationsDocumentsCreateError,
  V1OrganizationsDocumentsCreateResponse,
  V1OrganizationsDocumentsGetData,
  V1OrganizationsDocumentsGetError,
  V1OrganizationsDocumentsGetResponse,
  V1OrganizationsFoldersCreateData,
  V1OrganizationsFoldersCreateError,
  V1OrganizationsFoldersCreateResponse,
  V1OrganizationsFoldersGetData,
  V1OrganizationsFoldersGetError,
  V1OrganizationsFoldersGetResponse,
  V1OrganizationsGetData,
  V1OrganizationsGetError,
  V1OrganizationsGetResponse,
  V1OrganizationsNamespacesCreateData,
  V1OrganizationsNamespacesCreateError,
  V1OrganizationsNamespacesCreateResponse,
  V1OrganizationsNamespacesGetData,
  V1OrganizationsNamespacesGetError,
  V1OrganizationsNamespacesGetResponse,
  V1OrganizationUpdateData,
  V1OrganizationUpdateError,
  V1OrganizationUpdateResponse,
  V1PermissionDeleteData,
  V1PermissionDeleteError,
  V1PermissionDeleteResponse,
  V1PermissionGetData,
  V1PermissionGetError,
  V1PermissionGetResponse,
  V1PermissionHasRelationsData,
  V1PermissionHasRelationsError,
  V1PermissionHasRelationsResponse,
  V1PermissionHasSystemRoleData,
  V1PermissionHasSystemRoleError,
  V1PermissionHasSystemRoleResponse,
  V1PermissionResourceGetData,
  V1PermissionResourceGetError,
  V1PermissionResourceGetResponse,
  V1PermissionsCreateData,
  V1PermissionsCreateError,
  V1PermissionsCreateResponse,
  V1PermissionUpdateData,
  V1PermissionUpdateError,
  V1PermissionUpdateResponse,
  V1ProjectDeleteData,
  V1ProjectDeleteError,
  V1ProjectDeleteResponse,
  V1ProjectGetData,
  V1ProjectGetError,
  V1ProjectGetResponse,
  V1ProjectsDocumentsCreateData,
  V1ProjectsDocumentsCreateError,
  V1ProjectsDocumentsCreateResponse,
  V1ProjectsDocumentsGetData,
  V1ProjectsDocumentsGetError,
  V1ProjectsDocumentsGetResponse,
  V1ProjectsDocumentsRelateData,
  V1ProjectsDocumentsRelateError,
  V1ProjectsDocumentsRelateResponse,
  V1ProjectsDocumentsUnrelateData,
  V1ProjectsDocumentsUnrelateError,
  V1ProjectsDocumentsUnrelateResponse,
  V1ProjectsIssuesCreateData,
  V1ProjectsIssuesCreateError,
  V1ProjectsIssuesCreateResponse,
  V1ProjectsIssuesGetData,
  V1ProjectsIssuesGetError,
  V1ProjectsIssuesGetResponse,
  V1ProjectUpdateData,
  V1ProjectUpdateError,
  V1ProjectUpdateResponse,
  V1SystemHealthData,
  V1SystemHealthError,
  V1SystemHealthResponse,
  V1SystemHeartbeatData,
  V1SystemHeartbeatError,
  V1SystemHeartbeatResponse,
  V1SystemLicenseData,
  V1SystemLicenseError,
  V1SystemLicenseResponse,
  V1SystemVersionData,
  V1SystemVersionError,
  V1SystemVersionResponse,
  V1TodoDeleteData,
  V1TodoDeleteError,
  V1TodoDeleteResponse,
  V1TodoGetData,
  V1TodoGetError,
  V1TodoGetResponse,
  V1TodosCreateData,
  V1TodosCreateError,
  V1TodosCreateResponse,
  V1TodosGetData,
  V1TodosGetError,
  V1TodosGetResponse,
  V1TodoUpdateData,
  V1TodoUpdateError,
  V1TodoUpdateResponse,
  V1UserDeleteData,
  V1UserDeleteError,
  V1UserDeleteResponse,
  V1UserGetData,
  V1UserGetError,
  V1UserGetResponse,
  V1UserRequestPasswordResetData,
  V1UserRequestPasswordResetError,
  V1UserResetPasswordData,
  V1UserResetPasswordError,
  V1UserResetPasswordResponse,
  V1UsersCreateData,
  V1UsersCreateError,
  V1UsersCreateResponse,
  V1UsersGetData,
  V1UsersGetError,
  V1UsersGetResponse,
  V1UsersIssuesGetData,
  V1UsersIssuesGetError,
  V1UsersIssuesGetResponse,
  V1UserUpdateData,
  V1UserUpdateError,
  V1UserUpdateResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const v1UsersGetQueryKey = (options?: Options<V1UsersGetData>) =>
  createQueryKey("v1UsersGet", options);

/**
 * Get all users
 *
 * Returns the paginated list of users
 */
export const v1UsersGetOptions = (options?: Options<V1UsersGetData>) =>
  queryOptions<
    V1UsersGetResponse,
    V1UsersGetError,
    V1UsersGetResponse,
    ReturnType<typeof v1UsersGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1UsersGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1UsersGetQueryKey(options),
  });

/**
 * Create new user
 *
 * Create a new user.
 */
export const v1UsersCreateMutation = (
  options?: Partial<Options<V1UsersCreateData>>
): UseMutationOptions<
  V1UsersCreateResponse,
  V1UsersCreateError,
  Options<V1UsersCreateData>
> => {
  const mutationOptions: UseMutationOptions<
    V1UsersCreateResponse,
    V1UsersCreateError,
    Options<V1UsersCreateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1UsersCreate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const v1UserRequestPasswordResetQueryKey = (
  options: Options<V1UserRequestPasswordResetData>
) => createQueryKey("v1UserRequestPasswordReset", options);

/**
 * Initiate password reset
 *
 * Initiate password reset flow.
 */
export const v1UserRequestPasswordResetOptions = (
  options: Options<V1UserRequestPasswordResetData>
) =>
  queryOptions<
    unknown,
    V1UserRequestPasswordResetError,
    unknown,
    ReturnType<typeof v1UserRequestPasswordResetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1UserRequestPasswordReset({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1UserRequestPasswordResetQueryKey(options),
  });

/**
 * Reset user password
 *
 * Reset the user password.
 */
export const v1UserResetPasswordMutation = (
  options?: Partial<Options<V1UserResetPasswordData>>
): UseMutationOptions<
  V1UserResetPasswordResponse,
  V1UserResetPasswordError,
  Options<V1UserResetPasswordData>
> => {
  const mutationOptions: UseMutationOptions<
    V1UserResetPasswordResponse,
    V1UserResetPasswordError,
    Options<V1UserResetPasswordData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1UserResetPassword({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete the user with the given ID.
 *
 * Delete a user by its ID. The user is not deleted irreversibly until the "force" parameter is set to true.
 */
export const v1UserDeleteMutation = (
  options?: Partial<Options<V1UserDeleteData>>
): UseMutationOptions<
  V1UserDeleteResponse,
  V1UserDeleteError,
  Options<V1UserDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    V1UserDeleteResponse,
    V1UserDeleteError,
    Options<V1UserDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1UserDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const v1UserGetQueryKey = (options: Options<V1UserGetData>) =>
  createQueryKey("v1UserGet", options);

/**
 * Get user
 *
 * Return the requested user by its ID.
 */
export const v1UserGetOptions = (options: Options<V1UserGetData>) =>
  queryOptions<
    V1UserGetResponse,
    V1UserGetError,
    V1UserGetResponse,
    ReturnType<typeof v1UserGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1UserGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1UserGetQueryKey(options),
  });

/**
 * Update user
 *
 * Update the given user.
 */
export const v1UserUpdateMutation = (
  options?: Partial<Options<V1UserUpdateData>>
): UseMutationOptions<
  V1UserUpdateResponse,
  V1UserUpdateError,
  Options<V1UserUpdateData>
> => {
  const mutationOptions: UseMutationOptions<
    V1UserUpdateResponse,
    V1UserUpdateError,
    Options<V1UserUpdateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1UserUpdate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const v1UsersIssuesGetQueryKey = (
  options: Options<V1UsersIssuesGetData>
) => createQueryKey("v1UsersIssuesGet", options);

/**
 * Get user issues
 *
 * Return a cursor-paginated page of issues assigned to the user.
 */
export const v1UsersIssuesGetOptions = (
  options: Options<V1UsersIssuesGetData>
) =>
  queryOptions<
    V1UsersIssuesGetResponse,
    V1UsersIssuesGetError,
    V1UsersIssuesGetResponse,
    ReturnType<typeof v1UsersIssuesGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1UsersIssuesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1UsersIssuesGetQueryKey(options),
  });

export const v1LabelsGetQueryKey = (options?: Options<V1LabelsGetData>) =>
  createQueryKey("v1LabelsGet", options);

/**
 * List labels
 *
 * Returns a cursor-paginated page of labels.
 */
export const v1LabelsGetOptions = (options?: Options<V1LabelsGetData>) =>
  queryOptions<
    V1LabelsGetResponse,
    V1LabelsGetError,
    V1LabelsGetResponse,
    ReturnType<typeof v1LabelsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1LabelsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1LabelsGetQueryKey(options),
  });

export const v1TodosGetQueryKey = (options?: Options<V1TodosGetData>) =>
  createQueryKey("v1TodosGet", options);

/**
 * Get todo item
 *
 * Returns all todo items belonging to the current user.
 */
export const v1TodosGetOptions = (options?: Options<V1TodosGetData>) =>
  queryOptions<
    V1TodosGetResponse,
    V1TodosGetError,
    V1TodosGetResponse,
    ReturnType<typeof v1TodosGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1TodosGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1TodosGetQueryKey(options),
  });

/**
 * Create todo item
 *
 * Create a new todo item.
 */
export const v1TodosCreateMutation = (
  options?: Partial<Options<V1TodosCreateData>>
): UseMutationOptions<
  V1TodosCreateResponse,
  V1TodosCreateError,
  Options<V1TodosCreateData>
> => {
  const mutationOptions: UseMutationOptions<
    V1TodosCreateResponse,
    V1TodosCreateError,
    Options<V1TodosCreateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1TodosCreate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete todo item
 *
 * Delete todo by its ID.
 */
export const v1TodoDeleteMutation = (
  options?: Partial<Options<V1TodoDeleteData>>
): UseMutationOptions<
  V1TodoDeleteResponse,
  V1TodoDeleteError,
  Options<V1TodoDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    V1TodoDeleteResponse,
    V1TodoDeleteError,
    Options<V1TodoDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1TodoDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const v1TodoGetQueryKey = (options: Options<V1TodoGetData>) =>
  createQueryKey("v1TodoGet", options);

/**
 * Get todo item
 *
 * Return a todo item based on the todo id belonging to the current user.
 */
export const v1TodoGetOptions = (options: Options<V1TodoGetData>) =>
  queryOptions<
    V1TodoGetResponse,
    V1TodoGetError,
    V1TodoGetResponse,
    ReturnType<typeof v1TodoGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1TodoGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1TodoGetQueryKey(options),
  });

/**
 * Update todo
 *
 * Update the given todo
 */
export const v1TodoUpdateMutation = (
  options?: Partial<Options<V1TodoUpdateData>>
): UseMutationOptions<
  V1TodoUpdateResponse,
  V1TodoUpdateError,
  Options<V1TodoUpdateData>
> => {
  const mutationOptions: UseMutationOptions<
    V1TodoUpdateResponse,
    V1TodoUpdateError,
    Options<V1TodoUpdateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1TodoUpdate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const v1NotificationsGetQueryKey = (
  options?: Options<V1NotificationsGetData>
) => createQueryKey("v1NotificationsGet", options);

/**
 * Get all in-app notification of the requesting user.
 *
 * Returns the paginated list of in-app notifications
 */
export const v1NotificationsGetOptions = (
  options?: Options<V1NotificationsGetData>
) =>
  queryOptions<
    V1NotificationsGetResponse,
    V1NotificationsGetError,
    V1NotificationsGetResponse,
    ReturnType<typeof v1NotificationsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1NotificationsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1NotificationsGetQueryKey(options),
  });

/**
 * Delete the notification with the given ID.
 *
 * Delete a notification by its ID.
 */
export const v1NotificationDeleteMutation = (
  options?: Partial<Options<V1NotificationDeleteData>>
): UseMutationOptions<
  V1NotificationDeleteResponse,
  V1NotificationDeleteError,
  Options<V1NotificationDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    V1NotificationDeleteResponse,
    V1NotificationDeleteError,
    Options<V1NotificationDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1NotificationDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const v1NotificationGetQueryKey = (
  options: Options<V1NotificationGetData>
) => createQueryKey("v1NotificationGet", options);

/**
 * Get an in-app notification
 *
 * Return the requested notification by its ID.
 */
export const v1NotificationGetOptions = (
  options: Options<V1NotificationGetData>
) =>
  queryOptions<
    V1NotificationGetResponse,
    V1NotificationGetError,
    V1NotificationGetResponse,
    ReturnType<typeof v1NotificationGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1NotificationGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1NotificationGetQueryKey(options),
  });

/**
 * Update an in-app notification
 *
 * Update the given user.
 */
export const v1NotificationUpdateMutation = (
  options?: Partial<Options<V1NotificationUpdateData>>
): UseMutationOptions<
  V1NotificationUpdateResponse,
  V1NotificationUpdateError,
  Options<V1NotificationUpdateData>
> => {
  const mutationOptions: UseMutationOptions<
    V1NotificationUpdateResponse,
    V1NotificationUpdateError,
    Options<V1NotificationUpdateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1NotificationUpdate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const v1OrganizationsGetQueryKey = (
  options?: Options<V1OrganizationsGetData>
) => createQueryKey("v1OrganizationsGet", options);

/**
 * Get organizations
 *
 * Returns the list of organizations in the system.
 */
export const v1OrganizationsGetOptions = (
  options?: Options<V1OrganizationsGetData>
) =>
  queryOptions<
    V1OrganizationsGetResponse,
    V1OrganizationsGetError,
    V1OrganizationsGetResponse,
    ReturnType<typeof v1OrganizationsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1OrganizationsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1OrganizationsGetQueryKey(options),
  });

/**
 * Create organization
 *
 * Create a new organization.
 */
export const v1OrganizationsCreateMutation = (
  options?: Partial<Options<V1OrganizationsCreateData>>
): UseMutationOptions<
  V1OrganizationsCreateResponse,
  V1OrganizationsCreateError,
  Options<V1OrganizationsCreateData>
> => {
  const mutationOptions: UseMutationOptions<
    V1OrganizationsCreateResponse,
    V1OrganizationsCreateError,
    Options<V1OrganizationsCreateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1OrganizationsCreate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete organization
 *
 * Delete the organization by its ID.
 */
export const v1OrganizationDeleteMutation = (
  options?: Partial<Options<V1OrganizationDeleteData>>
): UseMutationOptions<
  V1OrganizationDeleteResponse,
  V1OrganizationDeleteError,
  Options<V1OrganizationDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    V1OrganizationDeleteResponse,
    V1OrganizationDeleteError,
    Options<V1OrganizationDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1OrganizationDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const v1OrganizationGetQueryKey = (
  options: Options<V1OrganizationGetData>
) => createQueryKey("v1OrganizationGet", options);

/**
 * Get organization
 *
 * Returns the given organization by its ID.
 */
export const v1OrganizationGetOptions = (
  options: Options<V1OrganizationGetData>
) =>
  queryOptions<
    V1OrganizationGetResponse,
    V1OrganizationGetError,
    V1OrganizationGetResponse,
    ReturnType<typeof v1OrganizationGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1OrganizationGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1OrganizationGetQueryKey(options),
  });

/**
 * Update organization
 *
 * Update the organization by its ID.
 */
export const v1OrganizationUpdateMutation = (
  options?: Partial<Options<V1OrganizationUpdateData>>
): UseMutationOptions<
  V1OrganizationUpdateResponse,
  V1OrganizationUpdateError,
  Options<V1OrganizationUpdateData>
> => {
  const mutationOptions: UseMutationOptions<
    V1OrganizationUpdateResponse,
    V1OrganizationUpdateError,
    Options<V1OrganizationUpdateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1OrganizationUpdate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const v1OrganizationMembersGetQueryKey = (
  options: Options<V1OrganizationMembersGetData>
) => createQueryKey("v1OrganizationMembersGet", options);

/**
 * Get organization members
 *
 * Return a cursor-paginated page of users that are members of the organization.
 */
export const v1OrganizationMembersGetOptions = (
  options: Options<V1OrganizationMembersGetData>
) =>
  queryOptions<
    V1OrganizationMembersGetResponse,
    V1OrganizationMembersGetError,
    V1OrganizationMembersGetResponse,
    ReturnType<typeof v1OrganizationMembersGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1OrganizationMembersGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1OrganizationMembersGetQueryKey(options),
  });

/**
 * Add organization member
 *
 * Add an existing user to an organization.
 */
export const v1OrganizationMembersAddMutation = (
  options?: Partial<Options<V1OrganizationMembersAddData>>
): UseMutationOptions<
  V1OrganizationMembersAddResponse,
  V1OrganizationMembersAddError,
  Options<V1OrganizationMembersAddData>
> => {
  const mutationOptions: UseMutationOptions<
    V1OrganizationMembersAddResponse,
    V1OrganizationMembersAddError,
    Options<V1OrganizationMembersAddData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1OrganizationMembersAdd({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Invite member to organization
 *
 * Send an invitation email to a user to join the organization. If the user doesn't exist, a pending user will be created.
 */
export const v1OrganizationMembersInviteMutation = (
  options?: Partial<Options<V1OrganizationMembersInviteData>>
): UseMutationOptions<
  V1OrganizationMembersInviteResponse,
  V1OrganizationMembersInviteError,
  Options<V1OrganizationMembersInviteData>
> => {
  const mutationOptions: UseMutationOptions<
    V1OrganizationMembersInviteResponse,
    V1OrganizationMembersInviteError,
    Options<V1OrganizationMembersInviteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1OrganizationMembersInvite({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Remove organization member
 *
 * Removes a member from the organization
 */
export const v1OrganizationMemberRemoveMutation = (
  options?: Partial<Options<V1OrganizationMemberRemoveData>>
): UseMutationOptions<
  V1OrganizationMemberRemoveResponse,
  V1OrganizationMemberRemoveError,
  Options<V1OrganizationMemberRemoveData>
> => {
  const mutationOptions: UseMutationOptions<
    V1OrganizationMemberRemoveResponse,
    V1OrganizationMemberRemoveError,
    Options<V1OrganizationMemberRemoveData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1OrganizationMemberRemove({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Revoke invitation
 *
 * Revoke an invitation for a user to join the organization
 */
export const v1OrganizationMemberInviteRevokeMutation = (
  options?: Partial<Options<V1OrganizationMemberInviteRevokeData>>
): UseMutationOptions<
  V1OrganizationMemberInviteRevokeResponse,
  V1OrganizationMemberInviteRevokeError,
  Options<V1OrganizationMemberInviteRevokeData>
> => {
  const mutationOptions: UseMutationOptions<
    V1OrganizationMemberInviteRevokeResponse,
    V1OrganizationMemberInviteRevokeError,
    Options<V1OrganizationMemberInviteRevokeData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1OrganizationMemberInviteRevoke({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Accept organization invitation
 *
 * Accept an invitation to join an organization using an invitation token. If the user is pending, they will be activated.
 */
export const v1OrganizationMembersAcceptMutation = (
  options?: Partial<Options<V1OrganizationMembersAcceptData>>
): UseMutationOptions<
  V1OrganizationMembersAcceptResponse,
  V1OrganizationMembersAcceptError,
  Options<V1OrganizationMembersAcceptData>
> => {
  const mutationOptions: UseMutationOptions<
    V1OrganizationMembersAcceptResponse,
    V1OrganizationMembersAcceptError,
    Options<V1OrganizationMembersAcceptData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1OrganizationMembersAccept({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const v1OrganizationRolesGetQueryKey = (
  options: Options<V1OrganizationRolesGetData>
) => createQueryKey("v1OrganizationRolesGet", options);

/**
 * Get organization roles
 *
 * Return the roles that are assigned to the organization.
 */
export const v1OrganizationRolesGetOptions = (
  options: Options<V1OrganizationRolesGetData>
) =>
  queryOptions<
    V1OrganizationRolesGetResponse,
    V1OrganizationRolesGetError,
    V1OrganizationRolesGetResponse,
    ReturnType<typeof v1OrganizationRolesGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1OrganizationRolesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1OrganizationRolesGetQueryKey(options),
  });

/**
 * Create a new role in the organization
 *
 * Create a new role and assign it to the organization.
 */
export const v1OrganizationRolesCreateMutation = (
  options?: Partial<Options<V1OrganizationRolesCreateData>>
): UseMutationOptions<
  V1OrganizationRolesCreateResponse,
  V1OrganizationRolesCreateError,
  Options<V1OrganizationRolesCreateData>
> => {
  const mutationOptions: UseMutationOptions<
    V1OrganizationRolesCreateResponse,
    V1OrganizationRolesCreateError,
    Options<V1OrganizationRolesCreateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1OrganizationRolesCreate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete organization role
 *
 * Deletes a role that is assigned to the organization.
 */
export const v1OrganizationRoleDeleteMutation = (
  options?: Partial<Options<V1OrganizationRoleDeleteData>>
): UseMutationOptions<
  V1OrganizationRoleDeleteResponse,
  V1OrganizationRoleDeleteError,
  Options<V1OrganizationRoleDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    V1OrganizationRoleDeleteResponse,
    V1OrganizationRoleDeleteError,
    Options<V1OrganizationRoleDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1OrganizationRoleDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const v1OrganizationRoleGetQueryKey = (
  options: Options<V1OrganizationRoleGetData>
) => createQueryKey("v1OrganizationRoleGet", options);

/**
 * Get organization role
 *
 * Returns the given organization by its ID.
 */
export const v1OrganizationRoleGetOptions = (
  options: Options<V1OrganizationRoleGetData>
) =>
  queryOptions<
    V1OrganizationRoleGetResponse,
    V1OrganizationRoleGetError,
    V1OrganizationRoleGetResponse,
    ReturnType<typeof v1OrganizationRoleGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1OrganizationRoleGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1OrganizationRoleGetQueryKey(options),
  });

/**
 * Update organization role
 *
 * Update the organization role by its ID.
 */
export const v1OrganizationRoleUpdateMutation = (
  options?: Partial<Options<V1OrganizationRoleUpdateData>>
): UseMutationOptions<
  V1OrganizationRoleUpdateResponse,
  V1OrganizationRoleUpdateError,
  Options<V1OrganizationRoleUpdateData>
> => {
  const mutationOptions: UseMutationOptions<
    V1OrganizationRoleUpdateResponse,
    V1OrganizationRoleUpdateError,
    Options<V1OrganizationRoleUpdateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1OrganizationRoleUpdate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const v1OrganizationRoleMembersGetQueryKey = (
  options: Options<V1OrganizationRoleMembersGetData>
) => createQueryKey("v1OrganizationRoleMembersGet", options);

/**
 * Get organization role members
 *
 * Return a cursor-paginated page of users that are members of the organization's role.
 */
export const v1OrganizationRoleMembersGetOptions = (
  options: Options<V1OrganizationRoleMembersGetData>
) =>
  queryOptions<
    V1OrganizationRoleMembersGetResponse,
    V1OrganizationRoleMembersGetError,
    V1OrganizationRoleMembersGetResponse,
    ReturnType<typeof v1OrganizationRoleMembersGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1OrganizationRoleMembersGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1OrganizationRoleMembersGetQueryKey(options),
  });

/**
 * Add organization role member
 *
 * Add an existing user to an organization's role.
 */
export const v1OrganizationRoleMembersAddMutation = (
  options?: Partial<Options<V1OrganizationRoleMembersAddData>>
): UseMutationOptions<
  V1OrganizationRoleMembersAddResponse,
  V1OrganizationRoleMembersAddError,
  Options<V1OrganizationRoleMembersAddData>
> => {
  const mutationOptions: UseMutationOptions<
    V1OrganizationRoleMembersAddResponse,
    V1OrganizationRoleMembersAddError,
    Options<V1OrganizationRoleMembersAddData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1OrganizationRoleMembersAdd({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Remove organization role member
 *
 * Removes a member from the organization's role
 */
export const v1OrganizationRoleMemberRemoveMutation = (
  options?: Partial<Options<V1OrganizationRoleMemberRemoveData>>
): UseMutationOptions<
  V1OrganizationRoleMemberRemoveResponse,
  V1OrganizationRoleMemberRemoveError,
  Options<V1OrganizationRoleMemberRemoveData>
> => {
  const mutationOptions: UseMutationOptions<
    V1OrganizationRoleMemberRemoveResponse,
    V1OrganizationRoleMemberRemoveError,
    Options<V1OrganizationRoleMemberRemoveData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1OrganizationRoleMemberRemove({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const v1OrganizationRolePermissionsGetQueryKey = (
  options: Options<V1OrganizationRolePermissionsGetData>
) => createQueryKey("v1OrganizationRolePermissionsGet", options);

/**
 * Get organization role permissions
 *
 * Return the permissions assigned to the organization's role.
 */
export const v1OrganizationRolePermissionsGetOptions = (
  options: Options<V1OrganizationRolePermissionsGetData>
) =>
  queryOptions<
    V1OrganizationRolePermissionsGetResponse,
    V1OrganizationRolePermissionsGetError,
    V1OrganizationRolePermissionsGetResponse,
    ReturnType<typeof v1OrganizationRolePermissionsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1OrganizationRolePermissionsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1OrganizationRolePermissionsGetQueryKey(options),
  });

/**
 * Add permission to organization role
 *
 * Add a permission to an organization's role. Only organization-scoped resources (Organization, Namespace, Document, Project, Role) are allowed.
 */
export const v1OrganizationRolePermissionAddMutation = (
  options?: Partial<Options<V1OrganizationRolePermissionAddData>>
): UseMutationOptions<
  V1OrganizationRolePermissionAddResponse,
  V1OrganizationRolePermissionAddError,
  Options<V1OrganizationRolePermissionAddData>
> => {
  const mutationOptions: UseMutationOptions<
    V1OrganizationRolePermissionAddResponse,
    V1OrganizationRolePermissionAddError,
    Options<V1OrganizationRolePermissionAddData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1OrganizationRolePermissionAdd({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Remove permission from organization role
 *
 * Removes a permission from the organization's role.
 */
export const v1OrganizationRolePermissionRemoveMutation = (
  options?: Partial<Options<V1OrganizationRolePermissionRemoveData>>
): UseMutationOptions<
  V1OrganizationRolePermissionRemoveResponse,
  V1OrganizationRolePermissionRemoveError,
  Options<V1OrganizationRolePermissionRemoveData>
> => {
  const mutationOptions: UseMutationOptions<
    V1OrganizationRolePermissionRemoveResponse,
    V1OrganizationRolePermissionRemoveError,
    Options<V1OrganizationRolePermissionRemoveData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1OrganizationRolePermissionRemove({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const v1OrganizationsNamespacesGetQueryKey = (
  options: Options<V1OrganizationsNamespacesGetData>
) => createQueryKey("v1OrganizationsNamespacesGet", options);

/**
 * Get organization namespaces
 *
 * Return the namespaces that belong to the organization.
 */
export const v1OrganizationsNamespacesGetOptions = (
  options: Options<V1OrganizationsNamespacesGetData>
) =>
  queryOptions<
    V1OrganizationsNamespacesGetResponse,
    V1OrganizationsNamespacesGetError,
    V1OrganizationsNamespacesGetResponse,
    ReturnType<typeof v1OrganizationsNamespacesGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1OrganizationsNamespacesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1OrganizationsNamespacesGetQueryKey(options),
  });

/**
 * Create namespace in organization
 *
 * Create a new namespace in the organization.
 */
export const v1OrganizationsNamespacesCreateMutation = (
  options?: Partial<Options<V1OrganizationsNamespacesCreateData>>
): UseMutationOptions<
  V1OrganizationsNamespacesCreateResponse,
  V1OrganizationsNamespacesCreateError,
  Options<V1OrganizationsNamespacesCreateData>
> => {
  const mutationOptions: UseMutationOptions<
    V1OrganizationsNamespacesCreateResponse,
    V1OrganizationsNamespacesCreateError,
    Options<V1OrganizationsNamespacesCreateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1OrganizationsNamespacesCreate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const v1OrganizationsDocumentsGetQueryKey = (
  options: Options<V1OrganizationsDocumentsGetData>
) => createQueryKey("v1OrganizationsDocumentsGet", options);

/**
 * Get organization documents
 *
 * Return a cursor-paginated page of documents in the organization library.
 */
export const v1OrganizationsDocumentsGetOptions = (
  options: Options<V1OrganizationsDocumentsGetData>
) =>
  queryOptions<
    V1OrganizationsDocumentsGetResponse,
    V1OrganizationsDocumentsGetError,
    V1OrganizationsDocumentsGetResponse,
    ReturnType<typeof v1OrganizationsDocumentsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1OrganizationsDocumentsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1OrganizationsDocumentsGetQueryKey(options),
  });

/**
 * Create document in organization
 *
 * Create a new document in the organization library.
 */
export const v1OrganizationsDocumentsCreateMutation = (
  options?: Partial<Options<V1OrganizationsDocumentsCreateData>>
): UseMutationOptions<
  V1OrganizationsDocumentsCreateResponse,
  V1OrganizationsDocumentsCreateError,
  Options<V1OrganizationsDocumentsCreateData>
> => {
  const mutationOptions: UseMutationOptions<
    V1OrganizationsDocumentsCreateResponse,
    V1OrganizationsDocumentsCreateError,
    Options<V1OrganizationsDocumentsCreateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1OrganizationsDocumentsCreate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const v1OrganizationsFoldersGetQueryKey = (
  options: Options<V1OrganizationsFoldersGetData>
) => createQueryKey("v1OrganizationsFoldersGet", options);

/**
 * Get organization folders
 *
 * Return a cursor-paginated page of folders at a location in the organization library.
 */
export const v1OrganizationsFoldersGetOptions = (
  options: Options<V1OrganizationsFoldersGetData>
) =>
  queryOptions<
    V1OrganizationsFoldersGetResponse,
    V1OrganizationsFoldersGetError,
    V1OrganizationsFoldersGetResponse,
    ReturnType<typeof v1OrganizationsFoldersGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1OrganizationsFoldersGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1OrganizationsFoldersGetQueryKey(options),
  });

/**
 * Create folder in organization
 *
 * Create a new folder in the organization library.
 */
export const v1OrganizationsFoldersCreateMutation = (
  options?: Partial<Options<V1OrganizationsFoldersCreateData>>
): UseMutationOptions<
  V1OrganizationsFoldersCreateResponse,
  V1OrganizationsFoldersCreateError,
  Options<V1OrganizationsFoldersCreateData>
> => {
  const mutationOptions: UseMutationOptions<
    V1OrganizationsFoldersCreateResponse,
    V1OrganizationsFoldersCreateError,
    Options<V1OrganizationsFoldersCreateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1OrganizationsFoldersCreate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete namespace
 *
 * Delete the namespace by its ID.
 */
export const v1NamespaceDeleteMutation = (
  options?: Partial<Options<V1NamespaceDeleteData>>
): UseMutationOptions<
  V1NamespaceDeleteResponse,
  V1NamespaceDeleteError,
  Options<V1NamespaceDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    V1NamespaceDeleteResponse,
    V1NamespaceDeleteError,
    Options<V1NamespaceDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1NamespaceDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const v1NamespaceGetQueryKey = (options: Options<V1NamespaceGetData>) =>
  createQueryKey("v1NamespaceGet", options);

/**
 * Get namespace
 *
 * Return the requested namespace by its ID.
 */
export const v1NamespaceGetOptions = (options: Options<V1NamespaceGetData>) =>
  queryOptions<
    V1NamespaceGetResponse,
    V1NamespaceGetError,
    V1NamespaceGetResponse,
    ReturnType<typeof v1NamespaceGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1NamespaceGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1NamespaceGetQueryKey(options),
  });

/**
 * Update namespace
 *
 * Update the namespace by its ID.
 */
export const v1NamespaceUpdateMutation = (
  options?: Partial<Options<V1NamespaceUpdateData>>
): UseMutationOptions<
  V1NamespaceUpdateResponse,
  V1NamespaceUpdateError,
  Options<V1NamespaceUpdateData>
> => {
  const mutationOptions: UseMutationOptions<
    V1NamespaceUpdateResponse,
    V1NamespaceUpdateError,
    Options<V1NamespaceUpdateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1NamespaceUpdate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const v1NamespacesProjectsGetQueryKey = (
  options: Options<V1NamespacesProjectsGetData>
) => createQueryKey("v1NamespacesProjectsGet", options);

/**
 * Get namespace projects
 *
 * Return a cursor-paginated page of projects that belong to the namespace.
 */
export const v1NamespacesProjectsGetOptions = (
  options: Options<V1NamespacesProjectsGetData>
) =>
  queryOptions<
    V1NamespacesProjectsGetResponse,
    V1NamespacesProjectsGetError,
    V1NamespacesProjectsGetResponse,
    ReturnType<typeof v1NamespacesProjectsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1NamespacesProjectsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1NamespacesProjectsGetQueryKey(options),
  });

/**
 * Create project in namespace
 *
 * Create a new project in the namespace.
 */
export const v1NamespacesProjectsCreateMutation = (
  options?: Partial<Options<V1NamespacesProjectsCreateData>>
): UseMutationOptions<
  V1NamespacesProjectsCreateResponse,
  V1NamespacesProjectsCreateError,
  Options<V1NamespacesProjectsCreateData>
> => {
  const mutationOptions: UseMutationOptions<
    V1NamespacesProjectsCreateResponse,
    V1NamespacesProjectsCreateError,
    Options<V1NamespacesProjectsCreateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1NamespacesProjectsCreate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const v1NamespacesDocumentsGetQueryKey = (
  options: Options<V1NamespacesDocumentsGetData>
) => createQueryKey("v1NamespacesDocumentsGet", options);

/**
 * Get namespace documents
 *
 * Return a cursor-paginated page of documents in the namespace library.
 */
export const v1NamespacesDocumentsGetOptions = (
  options: Options<V1NamespacesDocumentsGetData>
) =>
  queryOptions<
    V1NamespacesDocumentsGetResponse,
    V1NamespacesDocumentsGetError,
    V1NamespacesDocumentsGetResponse,
    ReturnType<typeof v1NamespacesDocumentsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1NamespacesDocumentsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1NamespacesDocumentsGetQueryKey(options),
  });

/**
 * Create document in namespace
 *
 * Create a new document in the namespace library.
 */
export const v1NamespacesDocumentsCreateMutation = (
  options?: Partial<Options<V1NamespacesDocumentsCreateData>>
): UseMutationOptions<
  V1NamespacesDocumentsCreateResponse,
  V1NamespacesDocumentsCreateError,
  Options<V1NamespacesDocumentsCreateData>
> => {
  const mutationOptions: UseMutationOptions<
    V1NamespacesDocumentsCreateResponse,
    V1NamespacesDocumentsCreateError,
    Options<V1NamespacesDocumentsCreateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1NamespacesDocumentsCreate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const v1NamespacesFoldersGetQueryKey = (
  options: Options<V1NamespacesFoldersGetData>
) => createQueryKey("v1NamespacesFoldersGet", options);

/**
 * Get namespace folders
 *
 * Return a cursor-paginated page of folders at a location in the namespace library.
 */
export const v1NamespacesFoldersGetOptions = (
  options: Options<V1NamespacesFoldersGetData>
) =>
  queryOptions<
    V1NamespacesFoldersGetResponse,
    V1NamespacesFoldersGetError,
    V1NamespacesFoldersGetResponse,
    ReturnType<typeof v1NamespacesFoldersGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1NamespacesFoldersGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1NamespacesFoldersGetQueryKey(options),
  });

/**
 * Create folder in namespace
 *
 * Create a new folder in the namespace library.
 */
export const v1NamespacesFoldersCreateMutation = (
  options?: Partial<Options<V1NamespacesFoldersCreateData>>
): UseMutationOptions<
  V1NamespacesFoldersCreateResponse,
  V1NamespacesFoldersCreateError,
  Options<V1NamespacesFoldersCreateData>
> => {
  const mutationOptions: UseMutationOptions<
    V1NamespacesFoldersCreateResponse,
    V1NamespacesFoldersCreateError,
    Options<V1NamespacesFoldersCreateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1NamespacesFoldersCreate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const v1NamespacesIssuesGetQueryKey = (
  options: Options<V1NamespacesIssuesGetData>
) => createQueryKey("v1NamespacesIssuesGet", options);

/**
 * Get namespace issues
 *
 * Return a cursor-paginated page of issues that belong to projects in the namespace.
 */
export const v1NamespacesIssuesGetOptions = (
  options: Options<V1NamespacesIssuesGetData>
) =>
  queryOptions<
    V1NamespacesIssuesGetResponse,
    V1NamespacesIssuesGetError,
    V1NamespacesIssuesGetResponse,
    ReturnType<typeof v1NamespacesIssuesGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1NamespacesIssuesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1NamespacesIssuesGetQueryKey(options),
  });

export const v1NamespacesIssuesKeyGetQueryKey = (
  options: Options<V1NamespacesIssuesKeyGetData>
) => createQueryKey("v1NamespacesIssuesKeyGet", options);

/**
 * Get issue by key
 *
 * Return the issue identified by composite key within the given namespace.
 */
export const v1NamespacesIssuesKeyGetOptions = (
  options: Options<V1NamespacesIssuesKeyGetData>
) =>
  queryOptions<
    V1NamespacesIssuesKeyGetResponse,
    V1NamespacesIssuesKeyGetError,
    V1NamespacesIssuesKeyGetResponse,
    ReturnType<typeof v1NamespacesIssuesKeyGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1NamespacesIssuesKeyGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1NamespacesIssuesKeyGetQueryKey(options),
  });

/**
 * Delete project
 *
 * Delete the project by its ID.
 */
export const v1ProjectDeleteMutation = (
  options?: Partial<Options<V1ProjectDeleteData>>
): UseMutationOptions<
  V1ProjectDeleteResponse,
  V1ProjectDeleteError,
  Options<V1ProjectDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    V1ProjectDeleteResponse,
    V1ProjectDeleteError,
    Options<V1ProjectDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1ProjectDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const v1ProjectGetQueryKey = (options: Options<V1ProjectGetData>) =>
  createQueryKey("v1ProjectGet", options);

/**
 * Get project
 *
 * Return the requested project by its ID.
 */
export const v1ProjectGetOptions = (options: Options<V1ProjectGetData>) =>
  queryOptions<
    V1ProjectGetResponse,
    V1ProjectGetError,
    V1ProjectGetResponse,
    ReturnType<typeof v1ProjectGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1ProjectGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1ProjectGetQueryKey(options),
  });

/**
 * Update project
 *
 * Update the project by its ID.
 */
export const v1ProjectUpdateMutation = (
  options?: Partial<Options<V1ProjectUpdateData>>
): UseMutationOptions<
  V1ProjectUpdateResponse,
  V1ProjectUpdateError,
  Options<V1ProjectUpdateData>
> => {
  const mutationOptions: UseMutationOptions<
    V1ProjectUpdateResponse,
    V1ProjectUpdateError,
    Options<V1ProjectUpdateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1ProjectUpdate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const v1ProjectsIssuesGetQueryKey = (
  options: Options<V1ProjectsIssuesGetData>
) => createQueryKey("v1ProjectsIssuesGet", options);

/**
 * Get project issues
 *
 * Return a cursor-paginated page of issues that belong to the project.
 */
export const v1ProjectsIssuesGetOptions = (
  options: Options<V1ProjectsIssuesGetData>
) =>
  queryOptions<
    V1ProjectsIssuesGetResponse,
    V1ProjectsIssuesGetError,
    V1ProjectsIssuesGetResponse,
    ReturnType<typeof v1ProjectsIssuesGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1ProjectsIssuesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1ProjectsIssuesGetQueryKey(options),
  });

/**
 * Create issue in project
 *
 * Create a new issue in the project.
 */
export const v1ProjectsIssuesCreateMutation = (
  options?: Partial<Options<V1ProjectsIssuesCreateData>>
): UseMutationOptions<
  V1ProjectsIssuesCreateResponse,
  V1ProjectsIssuesCreateError,
  Options<V1ProjectsIssuesCreateData>
> => {
  const mutationOptions: UseMutationOptions<
    V1ProjectsIssuesCreateResponse,
    V1ProjectsIssuesCreateError,
    Options<V1ProjectsIssuesCreateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1ProjectsIssuesCreate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const v1ProjectsDocumentsGetQueryKey = (
  options: Options<V1ProjectsDocumentsGetData>
) => createQueryKey("v1ProjectsDocumentsGet", options);

/**
 * Get project documents
 *
 * Return a cursor-paginated page of documents related to the project.
 */
export const v1ProjectsDocumentsGetOptions = (
  options: Options<V1ProjectsDocumentsGetData>
) =>
  queryOptions<
    V1ProjectsDocumentsGetResponse,
    V1ProjectsDocumentsGetError,
    V1ProjectsDocumentsGetResponse,
    ReturnType<typeof v1ProjectsDocumentsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1ProjectsDocumentsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1ProjectsDocumentsGetQueryKey(options),
  });

/**
 * Create document in project
 *
 * Create a new document in the namespace library, related to the project.
 */
export const v1ProjectsDocumentsCreateMutation = (
  options?: Partial<Options<V1ProjectsDocumentsCreateData>>
): UseMutationOptions<
  V1ProjectsDocumentsCreateResponse,
  V1ProjectsDocumentsCreateError,
  Options<V1ProjectsDocumentsCreateData>
> => {
  const mutationOptions: UseMutationOptions<
    V1ProjectsDocumentsCreateResponse,
    V1ProjectsDocumentsCreateError,
    Options<V1ProjectsDocumentsCreateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1ProjectsDocumentsCreate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Unrelate document from project
 *
 * Remove the relation between the document and the project.
 */
export const v1ProjectsDocumentsUnrelateMutation = (
  options?: Partial<Options<V1ProjectsDocumentsUnrelateData>>
): UseMutationOptions<
  V1ProjectsDocumentsUnrelateResponse,
  V1ProjectsDocumentsUnrelateError,
  Options<V1ProjectsDocumentsUnrelateData>
> => {
  const mutationOptions: UseMutationOptions<
    V1ProjectsDocumentsUnrelateResponse,
    V1ProjectsDocumentsUnrelateError,
    Options<V1ProjectsDocumentsUnrelateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1ProjectsDocumentsUnrelate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Relate document to project
 *
 * Relate an existing document to the project.
 */
export const v1ProjectsDocumentsRelateMutation = (
  options?: Partial<Options<V1ProjectsDocumentsRelateData>>
): UseMutationOptions<
  V1ProjectsDocumentsRelateResponse,
  V1ProjectsDocumentsRelateError,
  Options<V1ProjectsDocumentsRelateData>
> => {
  const mutationOptions: UseMutationOptions<
    V1ProjectsDocumentsRelateResponse,
    V1ProjectsDocumentsRelateError,
    Options<V1ProjectsDocumentsRelateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1ProjectsDocumentsRelate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete document
 *
 * Delete the document by its ID.
 */
export const v1DocumentDeleteMutation = (
  options?: Partial<Options<V1DocumentDeleteData>>
): UseMutationOptions<
  V1DocumentDeleteResponse,
  V1DocumentDeleteError,
  Options<V1DocumentDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    V1DocumentDeleteResponse,
    V1DocumentDeleteError,
    Options<V1DocumentDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1DocumentDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const v1DocumentGetQueryKey = (options: Options<V1DocumentGetData>) =>
  createQueryKey("v1DocumentGet", options);

/**
 * Get document
 *
 * Return the requested document by its ID, including the stored body.
 */
export const v1DocumentGetOptions = (options: Options<V1DocumentGetData>) =>
  queryOptions<
    V1DocumentGetResponse,
    V1DocumentGetError,
    V1DocumentGetResponse,
    ReturnType<typeof v1DocumentGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1DocumentGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1DocumentGetQueryKey(options),
  });

/**
 * Update document
 *
 * Update the document by its ID. Optional library_id moves the document to another library and clears its folder. Optional folder_id moves it within the library; JSON null removes it from the folder.
 */
export const v1DocumentUpdateMutation = (
  options?: Partial<Options<V1DocumentUpdateData>>
): UseMutationOptions<
  V1DocumentUpdateResponse,
  V1DocumentUpdateError,
  Options<V1DocumentUpdateData>
> => {
  const mutationOptions: UseMutationOptions<
    V1DocumentUpdateResponse,
    V1DocumentUpdateError,
    Options<V1DocumentUpdateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1DocumentUpdate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete folder
 *
 * Delete the folder by its ID. Child folders and documents are reparented one level up.
 */
export const v1FolderDeleteMutation = (
  options?: Partial<Options<V1FolderDeleteData>>
): UseMutationOptions<
  V1FolderDeleteResponse,
  V1FolderDeleteError,
  Options<V1FolderDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    V1FolderDeleteResponse,
    V1FolderDeleteError,
    Options<V1FolderDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1FolderDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const v1FolderGetQueryKey = (options: Options<V1FolderGetData>) =>
  createQueryKey("v1FolderGet", options);

/**
 * Get folder
 *
 * Return the requested folder by its ID.
 */
export const v1FolderGetOptions = (options: Options<V1FolderGetData>) =>
  queryOptions<
    V1FolderGetResponse,
    V1FolderGetError,
    V1FolderGetResponse,
    ReturnType<typeof v1FolderGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1FolderGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1FolderGetQueryKey(options),
  });

/**
 * Update folder
 *
 * Update the folder by its ID. JSON null parent_id moves it to the library root.
 */
export const v1FolderUpdateMutation = (
  options?: Partial<Options<V1FolderUpdateData>>
): UseMutationOptions<
  V1FolderUpdateResponse,
  V1FolderUpdateError,
  Options<V1FolderUpdateData>
> => {
  const mutationOptions: UseMutationOptions<
    V1FolderUpdateResponse,
    V1FolderUpdateError,
    Options<V1FolderUpdateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1FolderUpdate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete issue
 *
 * Delete the issue by its ID.
 */
export const v1IssueDeleteMutation = (
  options?: Partial<Options<V1IssueDeleteData>>
): UseMutationOptions<
  V1IssueDeleteResponse,
  V1IssueDeleteError,
  Options<V1IssueDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    V1IssueDeleteResponse,
    V1IssueDeleteError,
    Options<V1IssueDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1IssueDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const v1IssueGetQueryKey = (options: Options<V1IssueGetData>) =>
  createQueryKey("v1IssueGet", options);

/**
 * Get issue
 *
 * Return the requested issue by its ID.
 */
export const v1IssueGetOptions = (options: Options<V1IssueGetData>) =>
  queryOptions<
    V1IssueGetResponse,
    V1IssueGetError,
    V1IssueGetResponse,
    ReturnType<typeof v1IssueGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1IssueGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1IssueGetQueryKey(options),
  });

/**
 * Update issue
 *
 * Update the issue by its ID.
 */
export const v1IssueUpdateMutation = (
  options?: Partial<Options<V1IssueUpdateData>>
): UseMutationOptions<
  V1IssueUpdateResponse,
  V1IssueUpdateError,
  Options<V1IssueUpdateData>
> => {
  const mutationOptions: UseMutationOptions<
    V1IssueUpdateResponse,
    V1IssueUpdateError,
    Options<V1IssueUpdateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1IssueUpdate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const v1IssuesDocumentsGetQueryKey = (
  options: Options<V1IssuesDocumentsGetData>
) => createQueryKey("v1IssuesDocumentsGet", options);

/**
 * Get issue documents
 *
 * Return a cursor-paginated page of documents related to the issue.
 */
export const v1IssuesDocumentsGetOptions = (
  options: Options<V1IssuesDocumentsGetData>
) =>
  queryOptions<
    V1IssuesDocumentsGetResponse,
    V1IssuesDocumentsGetError,
    V1IssuesDocumentsGetResponse,
    ReturnType<typeof v1IssuesDocumentsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1IssuesDocumentsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1IssuesDocumentsGetQueryKey(options),
  });

/**
 * Create document in issue
 *
 * Create a new document in the namespace library, related to the issue.
 */
export const v1IssuesDocumentsCreateMutation = (
  options?: Partial<Options<V1IssuesDocumentsCreateData>>
): UseMutationOptions<
  V1IssuesDocumentsCreateResponse,
  V1IssuesDocumentsCreateError,
  Options<V1IssuesDocumentsCreateData>
> => {
  const mutationOptions: UseMutationOptions<
    V1IssuesDocumentsCreateResponse,
    V1IssuesDocumentsCreateError,
    Options<V1IssuesDocumentsCreateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1IssuesDocumentsCreate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Unrelate document from issue
 *
 * Remove the relation between the document and the issue.
 */
export const v1IssuesDocumentsUnrelateMutation = (
  options?: Partial<Options<V1IssuesDocumentsUnrelateData>>
): UseMutationOptions<
  V1IssuesDocumentsUnrelateResponse,
  V1IssuesDocumentsUnrelateError,
  Options<V1IssuesDocumentsUnrelateData>
> => {
  const mutationOptions: UseMutationOptions<
    V1IssuesDocumentsUnrelateResponse,
    V1IssuesDocumentsUnrelateError,
    Options<V1IssuesDocumentsUnrelateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1IssuesDocumentsUnrelate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Relate document to issue
 *
 * Relate an existing document to the issue.
 */
export const v1IssuesDocumentsRelateMutation = (
  options?: Partial<Options<V1IssuesDocumentsRelateData>>
): UseMutationOptions<
  V1IssuesDocumentsRelateResponse,
  V1IssuesDocumentsRelateError,
  Options<V1IssuesDocumentsRelateData>
> => {
  const mutationOptions: UseMutationOptions<
    V1IssuesDocumentsRelateResponse,
    V1IssuesDocumentsRelateError,
    Options<V1IssuesDocumentsRelateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1IssuesDocumentsRelate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const v1IssueRelationsGetQueryKey = (
  options: Options<V1IssueRelationsGetData>
) => createQueryKey("v1IssueRelationsGet", options);

/**
 * Get issue relations
 *
 * Return a cursor-paginated page of relations for the issue, including incoming and outgoing edges.
 */
export const v1IssueRelationsGetOptions = (
  options: Options<V1IssueRelationsGetData>
) =>
  queryOptions<
    V1IssueRelationsGetResponse,
    V1IssueRelationsGetError,
    V1IssueRelationsGetResponse,
    ReturnType<typeof v1IssueRelationsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1IssueRelationsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1IssueRelationsGetQueryKey(options),
  });

/**
 * Add issue relation
 *
 * Create an outgoing relation from the issue in the URL to another issue. Self-relations and the reserved "subtask of" kind are rejected.
 */
export const v1IssueRelationsCreateMutation = (
  options?: Partial<Options<V1IssueRelationsCreateData>>
): UseMutationOptions<
  V1IssueRelationsCreateResponse,
  V1IssueRelationsCreateError,
  Options<V1IssueRelationsCreateData>
> => {
  const mutationOptions: UseMutationOptions<
    V1IssueRelationsCreateResponse,
    V1IssueRelationsCreateError,
    Options<V1IssueRelationsCreateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1IssueRelationsCreate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete issue relation
 *
 * Delete a relation of the issue by its relation ID.
 */
export const v1IssueRelationDeleteMutation = (
  options?: Partial<Options<V1IssueRelationDeleteData>>
): UseMutationOptions<
  V1IssueRelationDeleteResponse,
  V1IssueRelationDeleteError,
  Options<V1IssueRelationDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    V1IssueRelationDeleteResponse,
    V1IssueRelationDeleteError,
    Options<V1IssueRelationDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1IssueRelationDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update issue relation
 *
 * Change the relation kind from this issue's point of view by replacing the edge with a new outgoing relation. Self-relations and the reserved "subtask of" kind are rejected.
 */
export const v1IssueRelationUpdateMutation = (
  options?: Partial<Options<V1IssueRelationUpdateData>>
): UseMutationOptions<
  V1IssueRelationUpdateResponse,
  V1IssueRelationUpdateError,
  Options<V1IssueRelationUpdateData>
> => {
  const mutationOptions: UseMutationOptions<
    V1IssueRelationUpdateResponse,
    V1IssueRelationUpdateError,
    Options<V1IssueRelationUpdateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1IssueRelationUpdate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Create permission
 *
 * Create a new permission for a subject to the given target.
 */
export const v1PermissionsCreateMutation = (
  options?: Partial<Options<V1PermissionsCreateData>>
): UseMutationOptions<
  V1PermissionsCreateResponse,
  V1PermissionsCreateError,
  Options<V1PermissionsCreateData>
> => {
  const mutationOptions: UseMutationOptions<
    V1PermissionsCreateResponse,
    V1PermissionsCreateError,
    Options<V1PermissionsCreateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1PermissionsCreate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete permission
 *
 * Delete a permission by its ID.
 */
export const v1PermissionDeleteMutation = (
  options?: Partial<Options<V1PermissionDeleteData>>
): UseMutationOptions<
  V1PermissionDeleteResponse,
  V1PermissionDeleteError,
  Options<V1PermissionDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    V1PermissionDeleteResponse,
    V1PermissionDeleteError,
    Options<V1PermissionDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1PermissionDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const v1PermissionGetQueryKey = (
  options: Options<V1PermissionGetData>
) => createQueryKey("v1PermissionGet", options);

/**
 * Get permission
 *
 * Get a permission by its ID.
 */
export const v1PermissionGetOptions = (options: Options<V1PermissionGetData>) =>
  queryOptions<
    V1PermissionGetResponse,
    V1PermissionGetError,
    V1PermissionGetResponse,
    ReturnType<typeof v1PermissionGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1PermissionGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1PermissionGetQueryKey(options),
  });

/**
 * Update permission
 *
 * Update a permission.
 */
export const v1PermissionUpdateMutation = (
  options?: Partial<Options<V1PermissionUpdateData>>
): UseMutationOptions<
  V1PermissionUpdateResponse,
  V1PermissionUpdateError,
  Options<V1PermissionUpdateData>
> => {
  const mutationOptions: UseMutationOptions<
    V1PermissionUpdateResponse,
    V1PermissionUpdateError,
    Options<V1PermissionUpdateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1PermissionUpdate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const v1PermissionResourceGetQueryKey = (
  options: Options<V1PermissionResourceGetData>
) => createQueryKey("v1PermissionResourceGet", options);

/**
 * Get permissions for a resource
 *
 * Get all permissions the caller have for a given resource.
 */
export const v1PermissionResourceGetOptions = (
  options: Options<V1PermissionResourceGetData>
) =>
  queryOptions<
    V1PermissionResourceGetResponse,
    V1PermissionResourceGetError,
    V1PermissionResourceGetResponse,
    ReturnType<typeof v1PermissionResourceGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1PermissionResourceGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1PermissionResourceGetQueryKey(options),
  });

export const v1PermissionHasRelationsQueryKey = (
  options: Options<V1PermissionHasRelationsData>
) => createQueryKey("v1PermissionHasRelations", options);

/**
 * Check relations to resource
 *
 * Check if the caller has any relations to a given resource.
 */
export const v1PermissionHasRelationsOptions = (
  options: Options<V1PermissionHasRelationsData>
) =>
  queryOptions<
    V1PermissionHasRelationsResponse,
    V1PermissionHasRelationsError,
    V1PermissionHasRelationsResponse,
    ReturnType<typeof v1PermissionHasRelationsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1PermissionHasRelations({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1PermissionHasRelationsQueryKey(options),
  });

export const v1PermissionHasSystemRoleQueryKey = (
  options: Options<V1PermissionHasSystemRoleData>
) => createQueryKey("v1PermissionHasSystemRole", options);

/**
 * Check system role assignment
 *
 * Check if the user is member of one or more system roles.
 */
export const v1PermissionHasSystemRoleOptions = (
  options: Options<V1PermissionHasSystemRoleData>
) =>
  queryOptions<
    V1PermissionHasSystemRoleResponse,
    V1PermissionHasSystemRoleError,
    V1PermissionHasSystemRoleResponse,
    ReturnType<typeof v1PermissionHasSystemRoleQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1PermissionHasSystemRole({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1PermissionHasSystemRoleQueryKey(options),
  });

export const v1SystemHealthQueryKey = (options?: Options<V1SystemHealthData>) =>
  createQueryKey("v1SystemHealth", options);

/**
 * Get system health
 *
 * Returns the health of registered components.
 */
export const v1SystemHealthOptions = (options?: Options<V1SystemHealthData>) =>
  queryOptions<
    V1SystemHealthResponse,
    V1SystemHealthError,
    V1SystemHealthResponse,
    ReturnType<typeof v1SystemHealthQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1SystemHealth({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1SystemHealthQueryKey(options),
  });

export const v1SystemHeartbeatQueryKey = (
  options?: Options<V1SystemHeartbeatData>
) => createQueryKey("v1SystemHeartbeat", options);

/**
 * Get heartbeat
 *
 * Returns 200 OK if the service is reachable.
 */
export const v1SystemHeartbeatOptions = (
  options?: Options<V1SystemHeartbeatData>
) =>
  queryOptions<
    V1SystemHeartbeatResponse,
    V1SystemHeartbeatError,
    V1SystemHeartbeatResponse,
    ReturnType<typeof v1SystemHeartbeatQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1SystemHeartbeat({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1SystemHeartbeatQueryKey(options),
  });

export const v1SystemLicenseQueryKey = (
  options?: Options<V1SystemLicenseData>
) => createQueryKey("v1SystemLicense", options);

/**
 * Get license info
 *
 * Return the license information. The license information is only available to entitled users.
 */
export const v1SystemLicenseOptions = (
  options?: Options<V1SystemLicenseData>
) =>
  queryOptions<
    V1SystemLicenseResponse,
    V1SystemLicenseError,
    V1SystemLicenseResponse,
    ReturnType<typeof v1SystemLicenseQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1SystemLicense({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1SystemLicenseQueryKey(options),
  });

export const v1SystemVersionQueryKey = (
  options?: Options<V1SystemVersionData>
) => createQueryKey("v1SystemVersion", options);

/**
 * Get system version
 *
 * Returns the version information of the system.
 */
export const v1SystemVersionOptions = (
  options?: Options<V1SystemVersionData>
) =>
  queryOptions<
    V1SystemVersionResponse,
    V1SystemVersionError,
    V1SystemVersionResponse,
    ReturnType<typeof v1SystemVersionQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1SystemVersion({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1SystemVersionQueryKey(options),
  });
