// Code generated by MockGen. DO NOT EDIT.
// Source: notification.go
//
// Generated by this command:
//
//	mockgen -source=notification.go -destination=mock/mock_notification_gen.go -package=mockrepo
//

// Package mockrepo is a generated GoMock package.
package mockrepo

import (
	context "context"
	reflect "reflect"

	model "github.com/opcotech/elemo/internal/model"
	repository "github.com/opcotech/elemo/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationRepository is a mock of NotificationRepository interface.
type MockNotificationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationRepositoryMockRecorder
	isgomock struct{}
}

// MockNotificationRepositoryMockRecorder is the mock recorder for MockNotificationRepository.
type MockNotificationRepositoryMockRecorder struct {
	mock *MockNotificationRepository
}

// NewMockNotificationRepository creates a new mock instance.
func NewMockNotificationRepository(ctrl *gomock.Controller) *MockNotificationRepository {
	mock := &MockNotificationRepository{ctrl: ctrl}
	mock.recorder = &MockNotificationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationRepository) EXPECT() *MockNotificationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNotificationRepository) Create(ctx context.Context, opts repository.CreateNotificationOpts) (*repository.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, opts)
	ret0, _ := ret[0].(*repository.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockNotificationRepositoryMockRecorder) Create(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNotificationRepository)(nil).Create), ctx, opts)
}

// Delete mocks base method.
func (m *MockNotificationRepository) Delete(ctx context.Context, id, recipient model.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, recipient)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockNotificationRepositoryMockRecorder) Delete(ctx, id, recipient any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNotificationRepository)(nil).Delete), ctx, id, recipient)
}

// Get mocks base method.
func (m *MockNotificationRepository) Get(ctx context.Context, id, recipient model.ID, proj repository.NotificationProjection) (*repository.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id, recipient, proj)
	ret0, _ := ret[0].(*repository.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockNotificationRepositoryMockRecorder) Get(ctx, id, recipient, proj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockNotificationRepository)(nil).Get), ctx, id, recipient, proj)
}

// ListByRecipient mocks base method.
func (m *MockNotificationRepository) ListByRecipient(ctx context.Context, recipient model.ID, page repository.CursorPage, proj repository.NotificationProjection) (repository.Page[*repository.Notification], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByRecipient", ctx, recipient, page, proj)
	ret0, _ := ret[0].(repository.Page[*repository.Notification])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByRecipient indicates an expected call of ListByRecipient.
func (mr *MockNotificationRepositoryMockRecorder) ListByRecipient(ctx, recipient, page, proj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByRecipient", reflect.TypeOf((*MockNotificationRepository)(nil).ListByRecipient), ctx, recipient, page, proj)
}

// Update mocks base method.
func (m *MockNotificationRepository) Update(ctx context.Context, id, recipient model.ID, opts repository.UpdateNotificationOpts) (*repository.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, recipient, opts)
	ret0, _ := ret[0].(*repository.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockNotificationRepositoryMockRecorder) Update(ctx, id, recipient, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockNotificationRepository)(nil).Update), ctx, id, recipient, opts)
}
