// Code generated by MockGen. DO NOT EDIT.
// Source: team.go
//
// Generated by this command:
//
//	mockgen -source=team.go -destination=mock/mock_team_gen.go -package=mockrepo
//

// Package mockrepo is a generated GoMock package.
package mockrepo

import (
	context "context"
	reflect "reflect"

	model "github.com/opcotech/elemo/internal/model"
	repository "github.com/opcotech/elemo/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockTeamRepository is a mock of TeamRepository interface.
type MockTeamRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTeamRepositoryMockRecorder
	isgomock struct{}
}

// MockTeamRepositoryMockRecorder is the mock recorder for MockTeamRepository.
type MockTeamRepositoryMockRecorder struct {
	mock *MockTeamRepository
}

// NewMockTeamRepository creates a new mock instance.
func NewMockTeamRepository(ctrl *gomock.Controller) *MockTeamRepository {
	mock := &MockTeamRepository{ctrl: ctrl}
	mock.recorder = &MockTeamRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamRepository) EXPECT() *MockTeamRepositoryMockRecorder {
	return m.recorder
}

// AddMember mocks base method.
func (m *MockTeamRepository) AddMember(ctx context.Context, teamID, memberID, belongsToID model.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMember", ctx, teamID, memberID, belongsToID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMember indicates an expected call of AddMember.
func (mr *MockTeamRepositoryMockRecorder) AddMember(ctx, teamID, memberID, belongsToID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockTeamRepository)(nil).AddMember), ctx, teamID, memberID, belongsToID)
}

// Create mocks base method.
func (m *MockTeamRepository) Create(ctx context.Context, opts repository.CreateTeamOpts) (*repository.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, opts)
	ret0, _ := ret[0].(*repository.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTeamRepositoryMockRecorder) Create(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTeamRepository)(nil).Create), ctx, opts)
}

// Delete mocks base method.
func (m *MockTeamRepository) Delete(ctx context.Context, id, belongsTo model.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, belongsTo)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTeamRepositoryMockRecorder) Delete(ctx, id, belongsTo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTeamRepository)(nil).Delete), ctx, id, belongsTo)
}

// Get mocks base method.
func (m *MockTeamRepository) Get(ctx context.Context, id, belongsTo model.ID, proj repository.TeamProjection) (*repository.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id, belongsTo, proj)
	ret0, _ := ret[0].(*repository.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTeamRepositoryMockRecorder) Get(ctx, id, belongsTo, proj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTeamRepository)(nil).Get), ctx, id, belongsTo, proj)
}

// ListBelongsTo mocks base method.
func (m *MockTeamRepository) ListBelongsTo(ctx context.Context, belongsTo model.ID, page repository.CursorPage, proj repository.TeamProjection) (repository.Page[*repository.Team], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBelongsTo", ctx, belongsTo, page, proj)
	ret0, _ := ret[0].(repository.Page[*repository.Team])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBelongsTo indicates an expected call of ListBelongsTo.
func (mr *MockTeamRepositoryMockRecorder) ListBelongsTo(ctx, belongsTo, page, proj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBelongsTo", reflect.TypeOf((*MockTeamRepository)(nil).ListBelongsTo), ctx, belongsTo, page, proj)
}

// ListMembers mocks base method.
func (m *MockTeamRepository) ListMembers(ctx context.Context, teamID, belongsTo model.ID, page repository.CursorPage) (repository.Page[*repository.User], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMembers", ctx, teamID, belongsTo, page)
	ret0, _ := ret[0].(repository.Page[*repository.User])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMembers indicates an expected call of ListMembers.
func (mr *MockTeamRepositoryMockRecorder) ListMembers(ctx, teamID, belongsTo, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMembers", reflect.TypeOf((*MockTeamRepository)(nil).ListMembers), ctx, teamID, belongsTo, page)
}

// RemoveMember mocks base method.
func (m *MockTeamRepository) RemoveMember(ctx context.Context, teamID, memberID, belongsToID model.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", ctx, teamID, memberID, belongsToID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockTeamRepositoryMockRecorder) RemoveMember(ctx, teamID, memberID, belongsToID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockTeamRepository)(nil).RemoveMember), ctx, teamID, memberID, belongsToID)
}

// Update mocks base method.
func (m *MockTeamRepository) Update(ctx context.Context, id, belongsTo model.ID, opts repository.UpdateTeamOpts) (*repository.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, belongsTo, opts)
	ret0, _ := ret[0].(*repository.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTeamRepositoryMockRecorder) Update(ctx, id, belongsTo, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTeamRepository)(nil).Update), ctx, id, belongsTo, opts)
}
