// Code generated by MockGen. DO NOT EDIT.
// Source: extension.go
//
// Generated by this command:
//
//	mockgen -source=extension.go -destination=mock/mock_extension_gen.go -package=mockrepo
//

// Package mockrepo is a generated GoMock package.
package mockrepo

import (
	context "context"
	reflect "reflect"

	model "github.com/opcotech/elemo/internal/model"
	repository "github.com/opcotech/elemo/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockExtensionRepository is a mock of ExtensionRepository interface.
type MockExtensionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockExtensionRepositoryMockRecorder
	isgomock struct{}
}

// MockExtensionRepositoryMockRecorder is the mock recorder for MockExtensionRepository.
type MockExtensionRepositoryMockRecorder struct {
	mock *MockExtensionRepository
}

// NewMockExtensionRepository creates a new mock instance.
func NewMockExtensionRepository(ctrl *gomock.Controller) *MockExtensionRepository {
	mock := &MockExtensionRepository{ctrl: ctrl}
	mock.recorder = &MockExtensionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtensionRepository) EXPECT() *MockExtensionRepositoryMockRecorder {
	return m.recorder
}

// CountRelations mocks base method.
func (m *MockExtensionRepository) CountRelations(ctx context.Context, pluginID, kind string, from, to model.ID) (int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountRelations", ctx, pluginID, kind, from, to)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CountRelations indicates an expected call of CountRelations.
func (mr *MockExtensionRepositoryMockRecorder) CountRelations(ctx, pluginID, kind, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountRelations", reflect.TypeOf((*MockExtensionRepository)(nil).CountRelations), ctx, pluginID, kind, from, to)
}

// Create mocks base method.
func (m *MockExtensionRepository) Create(ctx context.Context, opts repository.CreateExtensionOpts) (*model.Extension, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, opts)
	ret0, _ := ret[0].(*model.Extension)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockExtensionRepositoryMockRecorder) Create(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockExtensionRepository)(nil).Create), ctx, opts)
}

// CreateRelation mocks base method.
func (m *MockExtensionRepository) CreateRelation(ctx context.Context, opts repository.CreateExtensionRelationOpts) (*model.ExtensionRelation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRelation", ctx, opts)
	ret0, _ := ret[0].(*model.ExtensionRelation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRelation indicates an expected call of CreateRelation.
func (mr *MockExtensionRepositoryMockRecorder) CreateRelation(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRelation", reflect.TypeOf((*MockExtensionRepository)(nil).CreateRelation), ctx, opts)
}

// Delete mocks base method.
func (m *MockExtensionRepository) Delete(ctx context.Context, pluginID string, id model.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, pluginID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockExtensionRepositoryMockRecorder) Delete(ctx, pluginID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockExtensionRepository)(nil).Delete), ctx, pluginID, id)
}

// DeleteByPlugin mocks base method.
func (m *MockExtensionRepository) DeleteByPlugin(ctx context.Context, pluginID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByPlugin", ctx, pluginID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByPlugin indicates an expected call of DeleteByPlugin.
func (mr *MockExtensionRepositoryMockRecorder) DeleteByPlugin(ctx, pluginID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByPlugin", reflect.TypeOf((*MockExtensionRepository)(nil).DeleteByPlugin), ctx, pluginID)
}

// DeleteRelation mocks base method.
func (m *MockExtensionRepository) DeleteRelation(ctx context.Context, pluginID, relID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRelation", ctx, pluginID, relID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRelation indicates an expected call of DeleteRelation.
func (mr *MockExtensionRepositoryMockRecorder) DeleteRelation(ctx, pluginID, relID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRelation", reflect.TypeOf((*MockExtensionRepository)(nil).DeleteRelation), ctx, pluginID, relID)
}

// Get mocks base method.
func (m *MockExtensionRepository) Get(ctx context.Context, pluginID string, id model.ID) (*model.Extension, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, pluginID, id)
	ret0, _ := ret[0].(*model.Extension)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockExtensionRepositoryMockRecorder) Get(ctx, pluginID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockExtensionRepository)(nil).Get), ctx, pluginID, id)
}

// List mocks base method.
func (m *MockExtensionRepository) List(ctx context.Context, filter repository.ListExtensionFilter) (repository.Page[*model.Extension], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].(repository.Page[*model.Extension])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockExtensionRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockExtensionRepository)(nil).List), ctx, filter)
}

// ListRelations mocks base method.
func (m *MockExtensionRepository) ListRelations(ctx context.Context, pluginID, kind string, node model.ID, direction model.PluginGraphRelationDirection, page repository.CursorPage) (repository.Page[*model.ExtensionRelation], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRelations", ctx, pluginID, kind, node, direction, page)
	ret0, _ := ret[0].(repository.Page[*model.ExtensionRelation])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRelations indicates an expected call of ListRelations.
func (mr *MockExtensionRepositoryMockRecorder) ListRelations(ctx, pluginID, kind, node, direction, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRelations", reflect.TypeOf((*MockExtensionRepository)(nil).ListRelations), ctx, pluginID, kind, node, direction, page)
}

// Move mocks base method.
func (m *MockExtensionRepository) Move(ctx context.Context, opts repository.MoveExtensionOpts) (*model.Extension, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Move", ctx, opts)
	ret0, _ := ret[0].(*model.Extension)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Move indicates an expected call of Move.
func (mr *MockExtensionRepositoryMockRecorder) Move(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Move", reflect.TypeOf((*MockExtensionRepository)(nil).Move), ctx, opts)
}

// Update mocks base method.
func (m *MockExtensionRepository) Update(ctx context.Context, pluginID string, id model.ID, opts repository.UpdateExtensionOpts) (*model.Extension, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, pluginID, id, opts)
	ret0, _ := ret[0].(*model.Extension)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockExtensionRepositoryMockRecorder) Update(ctx, pluginID, id, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockExtensionRepository)(nil).Update), ctx, pluginID, id, opts)
}
