// Code generated by "enumer -type=TaskType -transform=noop -linecomment -output=queue_task_type_gen.go"; DO NOT EDIT.

package queue

import (
	"fmt"
	"strings"
)

const _TaskTypeName = "system:health_checksystem:license_expirysearch:indexsearch:reindexsearch:reindex_batchcustom_field:reconcile"

var _TaskTypeIndex = [...]uint8{0, 19, 40, 52, 66, 86, 108}

const _TaskTypeLowerName = "system:health_checksystem:license_expirysearch:indexsearch:reindexsearch:reindex_batchcustom_field:reconcile"

func (i TaskType) String() string {
	i -= 1
	if i >= TaskType(len(_TaskTypeIndex)-1) {
		return fmt.Sprintf("TaskType(%d)", i+1)
	}
	return _TaskTypeName[_TaskTypeIndex[i]:_TaskTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TaskTypeNoOp() {
	var x [1]struct{}
	_ = x[TaskTypeSystemHealthCheck-(1)]
	_ = x[TaskTypeSystemLicenseExpiry-(2)]
	_ = x[TaskTypeSearchIndex-(3)]
	_ = x[TaskTypeSearchReindex-(4)]
	_ = x[TaskTypeSearchReindexBatch-(5)]
	_ = x[TaskTypeCustomFieldReconcile-(6)]
}

var _TaskTypeValues = []TaskType{TaskTypeSystemHealthCheck, TaskTypeSystemLicenseExpiry, TaskTypeSearchIndex, TaskTypeSearchReindex, TaskTypeSearchReindexBatch, TaskTypeCustomFieldReconcile}

var _TaskTypeNameToValueMap = map[string]TaskType{
	_TaskTypeName[0:19]:        TaskTypeSystemHealthCheck,
	_TaskTypeLowerName[0:19]:   TaskTypeSystemHealthCheck,
	_TaskTypeName[19:40]:       TaskTypeSystemLicenseExpiry,
	_TaskTypeLowerName[19:40]:  TaskTypeSystemLicenseExpiry,
	_TaskTypeName[40:52]:       TaskTypeSearchIndex,
	_TaskTypeLowerName[40:52]:  TaskTypeSearchIndex,
	_TaskTypeName[52:66]:       TaskTypeSearchReindex,
	_TaskTypeLowerName[52:66]:  TaskTypeSearchReindex,
	_TaskTypeName[66:86]:       TaskTypeSearchReindexBatch,
	_TaskTypeLowerName[66:86]:  TaskTypeSearchReindexBatch,
	_TaskTypeName[86:108]:      TaskTypeCustomFieldReconcile,
	_TaskTypeLowerName[86:108]: TaskTypeCustomFieldReconcile,
}

var _TaskTypeNames = []string{
	_TaskTypeName[0:19],
	_TaskTypeName[19:40],
	_TaskTypeName[40:52],
	_TaskTypeName[52:66],
	_TaskTypeName[66:86],
	_TaskTypeName[86:108],
}

// TaskTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TaskTypeString(s string) (TaskType, error) {
	if val, ok := _TaskTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TaskTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to TaskType values", s)
}

// TaskTypeValues returns all values of the enum
func TaskTypeValues() []TaskType {
	return _TaskTypeValues
}

// TaskTypeStrings returns a slice of all String values of the enum
func TaskTypeStrings() []string {
	strs := make([]string, len(_TaskTypeNames))
	copy(strs, _TaskTypeNames)
	return strs
}

// IsATaskType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TaskType) IsATaskType() bool {
	for _, v := range _TaskTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
