// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/opcotech/elemo/internal/service (interfaces: DocumentService)
//
// Generated by this command:
//
//	mockgen -destination=document_mock_gen.go -package=service -mock_names DocumentService=MockDocumentService . DocumentService
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	model "github.com/opcotech/elemo/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockDocumentService is a mock of DocumentService interface.
type MockDocumentService struct {
	ctrl     *gomock.Controller
	recorder *MockDocumentServiceMockRecorder
	isgomock struct{}
}

// MockDocumentServiceMockRecorder is the mock recorder for MockDocumentService.
type MockDocumentServiceMockRecorder struct {
	mock *MockDocumentService
}

// NewMockDocumentService creates a new mock instance.
func NewMockDocumentService(ctrl *gomock.Controller) *MockDocumentService {
	mock := &MockDocumentService{ctrl: ctrl}
	mock.recorder = &MockDocumentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDocumentService) EXPECT() *MockDocumentServiceMockRecorder {
	return m.recorder
}

// ListBelongsTo mocks base method.
func (m *MockDocumentService) ListBelongsTo(ctx context.Context, belongsTo model.ID, page CursorPage) (Page[*PartialDocument], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBelongsTo", ctx, belongsTo, page)
	ret0, _ := ret[0].(Page[*PartialDocument])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBelongsTo indicates an expected call of ListBelongsTo.
func (mr *MockDocumentServiceMockRecorder) ListBelongsTo(ctx, belongsTo, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBelongsTo", reflect.TypeOf((*MockDocumentService)(nil).ListBelongsTo), ctx, belongsTo, page)
}
