package service

import "errors"

var (
	ErrCustomFieldArchive      = errors.New("failed to archive custom field")      // failed to archive custom field
	ErrCustomFieldCreate       = errors.New("failed to create custom field")       // failed to create custom field
	ErrCustomFieldDelete       = errors.New("failed to delete custom field")       // failed to delete custom field
	ErrCustomFieldGet          = errors.New("failed to get custom field")          // failed to get custom field
	ErrCustomFieldList         = errors.New("failed to list custom fields")        // failed to list custom fields
	ErrCustomFieldReconcile    = errors.New("failed to reconcile custom fields")   // failed to reconcile custom fields
	ErrCustomFieldSearch       = errors.New("failed to search custom fields")      // failed to search custom fields
	ErrCustomFieldUpdate       = errors.New("failed to update custom field")       // failed to update custom field
	ErrCustomFieldValueDelete  = errors.New("failed to delete custom field value") // failed to delete custom field value
	ErrCustomFieldValueGet     = errors.New("failed to get custom field values")   // failed to get custom field values
	ErrCustomFieldValueSet     = errors.New("failed to set custom field value")    // failed to set custom field value
	ErrNoCustomFieldRepository = errors.New("no custom field repository provided") // no custom field repository provided
	ErrNoCustomFieldService    = errors.New("no custom field service provided")    // no custom field service provided

	ErrDocumentCreate   = errors.New("failed to create document")   // failed to create document
	ErrDocumentDelete   = errors.New("failed to delete document")   // failed to delete document
	ErrDocumentGet      = errors.New("failed to get document")      // failed to get document
	ErrDocumentList     = errors.New("failed to list documents")    // failed to list documents
	ErrDocumentMove     = errors.New("failed to move document")     // failed to move document
	ErrDocumentRelate   = errors.New("failed to relate document")   // failed to relate document
	ErrDocumentUnrelate = errors.New("failed to unrelate document") // failed to unrelate document
	ErrDocumentUpdate   = errors.New("failed to update document")   // failed to update document

	ErrFolderCreate = errors.New("failed to create folder") // failed to create folder
	ErrFolderDelete = errors.New("failed to delete folder") // failed to delete folder
	ErrFolderGet    = errors.New("failed to get folder")    // failed to get folder
	ErrFolderList   = errors.New("failed to list folders")  // failed to list folders
	ErrFolderUpdate = errors.New("failed to update folder") // failed to update folder

	ErrEmailSend                       = errors.New("failed to send email")                         // failed to send email
	ErrExpiredToken                    = errors.New("expired token")                                // expired token
	ErrInvalidEmail                    = errors.New("invalid email address")                        // invalid email address
	ErrInvalidPaginationParams         = errors.New("invalid pagination parameters")                // invalid pagination parameters
	ErrInvalidToken                    = errors.New("invalid token")                                // invalid token
	ErrIssueAddRelation                = errors.New("failed to add issue relation")                 // failed to add issue relation
	ErrIssueCreate                     = errors.New("failed to create issue")                       // failed to create issue
	ErrIssueDelete                     = errors.New("failed to delete issue")                       // failed to delete issue
	ErrIssueGet                        = errors.New("failed to get issue")                          // failed to get issue
	ErrIssueList                       = errors.New("failed to list issues")                        // failed to list issues
	ErrIssueGetRelations               = errors.New("failed to get issue relations")                // failed to get issue relations
	ErrIssueRemoveRelation             = errors.New("failed to remove issue relation")              // failed to remove issue relation
	ErrIssueReservedRelationKind       = errors.New("relation kind is reserved")                    // relation kind is reserved
	ErrIssueSelfRelation               = errors.New("issue cannot be related to itself")            // issue cannot be related to itself
	ErrIssueUpdate                     = errors.New("failed to update issue")                       // failed to update issue
	ErrIssueUpdateRelation             = errors.New("failed to update issue relation")              // failed to update issue relation
	ErrLabelList                       = errors.New("failed to list labels")                        // failed to list labels
	ErrLicenseGet                      = errors.New("failed to get license")                        // failed to get license
	ErrLicensePing                     = errors.New("failed to ping license")                       // failed to ping license
	ErrNamespaceCreate                 = errors.New("failed to create namespace")                   // failed to create namespace
	ErrNamespaceDelete                 = errors.New("failed to delete namespace")                   // failed to delete namespace
	ErrNamespaceGet                    = errors.New("failed to get namespace")                      // failed to get namespace
	ErrNamespaceList                   = errors.New("failed to list namespaces")                    // failed to list namespaces
	ErrNamespaceUpdate                 = errors.New("failed to update namespace")                   // failed to update namespace
	ErrNoAssignmentRepository          = errors.New("no assignment repository provided")            // no assignment repository provided
	ErrNoDocumentRepository            = errors.New("no document repository provided")              // no document repository provided
	ErrNoFolderRepository              = errors.New("no folder repository provided")                // no folder repository provided
	ErrNoEmailService                  = errors.New("no email service provided")                    // no email service provided
	ErrNoIssueRepository               = errors.New("no issue repository provided")                 // no issue repository provided
	ErrNoLabelRepository               = errors.New("no label repository provided")                 // no label repository provided
	ErrNoLabelService                  = errors.New("no label service provided")                    // no label service provided
	ErrNoLicenseService                = errors.New("no license service provided")                  // no license service provided
	ErrNoNamespaceRepository           = errors.New("no namespace repository provided")             // no namespace repository provided
	ErrNoNotificationRepository        = errors.New("no notification repository provided")          // no notification repository provided
	ErrNoNotificationService           = errors.New("no notification service provided")             // no notification service provided
	ErrNoOrganizationRepository        = errors.New("no organization repository provided")          // no organization repository provided
	ErrNoPermission                    = errors.New("no permission")                                // no permission
	ErrNoPermissionRepository          = errors.New("no permission repository provided")            // no permission repository provided
	ErrNoPermissionService             = errors.New("no permission service provided")               // no permission service provided
	ErrNoProjectRepository             = errors.New("no project repository provided")               // no project repository provided
	ErrNoResources                     = errors.New("no resources provided")                        // no resources provided
	ErrNoRoleRepository                = errors.New("no role repository provided")                  // no role repository provided
	ErrNoTeamRepository                = errors.New("no team repository provided")                  // no team repository provided
	ErrNoStaticFileRepository          = errors.New("no static file repository provided")           // no static file repository provided
	ErrNoStaticFileService             = errors.New("no static file service provided")              // no static file service provided
	ErrNoTodoRepository                = errors.New("no todo repository provided")                  // no todo repository provided
	ErrNoUser                          = errors.New("no user provided")                             // no user provided
	ErrNoUserRepository                = errors.New("no user repository provided")                  // no user repository provided
	ErrNoUserTokenRepository           = errors.New("no user token repository provided")            // no user token repository provided
	ErrNoSearchRepository              = errors.New("no search repository provided")                // no search repository provided
	ErrNoSearchService                 = errors.New("no search service provided")                   // no search service provided
	ErrNoSearchTaskEnqueuer            = errors.New("no search task enqueuer provided")             // no search task enqueuer provided
	ErrNoVersionInfo                   = errors.New("no version info provided")                     // no version info provided
	ErrNotificationCreate              = errors.New("failed to create notification")                // failed to create notification
	ErrNotificationDelete              = errors.New("failed to delete notification")                // failed to delete notification
	ErrNotificationGet                 = errors.New("failed to get notification")                   // failed to get notification
	ErrNotificationListByRecipient     = errors.New("failed to list notifications")                 // failed to list notifications
	ErrNotificationUpdate              = errors.New("failed to update notification")                // failed to update notification
	ErrOrganizationCreate              = errors.New("failed to create organization")                // failed to create organization
	ErrOrganizationDelete              = errors.New("failed to delete organization")                // failed to delete organization
	ErrOrganizationGet                 = errors.New("failed to get organization")                   // failed to get organization
	ErrOrganizationList                = errors.New("failed to list organizations")                 // failed to list organizations
	ErrOrganizationInviteAccept        = errors.New("failed to accept invitation")                  // failed to accept invitation
	ErrOrganizationInviteRevoke        = errors.New("failed to revoke invitation")                  // failed to revoke invitation
	ErrOrganizationMemberAdd           = errors.New("failed to add member to organization")         // failed to add member to organization
	ErrOrganizationMemberAlreadyExists = errors.New("user is already a member of the organization") // user is already a member of the organization
	ErrOrganizationMemberInvalidStatus = errors.New("user status is not valid for invitation")      // user status is not valid for invitation
	ErrOrganizationMemberInvite        = errors.New("failed to invite member to organization")      // failed to invite member to organization
	ErrOrganizationMemberRemove        = errors.New("failed to remove member from organization")    // failed to remove member from organization
	ErrOrganizationMembersGet          = errors.New("failed to get members of organization")        // failed to get members of organization
	ErrOrganizationUpdate              = errors.New("failed to update organization")                // failed to update organization
	ErrPermissionCreate                = errors.New("failed to create permission")                  // failed to create permission
	ErrPermissionDelete                = errors.New("failed to delete permission")                  // failed to delete permission
	ErrPermissionGet                   = errors.New("failed to get permission")                     // failed to get permission
	ErrPermissionGetBySubject          = errors.New("failed to get permission by subject")          // failed to get permission by subject
	ErrPermissionGetByTarget           = errors.New("failed to get permission by target")           // failed to get permission by target
	ErrPermissionHasPermission         = errors.New("failed to check if permission has permission") // failed to check if permission has permission
	ErrPermissionListGrantScopes       = errors.New("failed to list grant scopes")                  // failed to list grant scopes
	ErrPermissionListScopeAncestry     = errors.New("failed to list scope ancestry")                // failed to list scope ancestry
	ErrPermissionUpdate                = errors.New("failed to update permission")                  // failed to update permission
	ErrProjectCreate                   = errors.New("failed to create project")                     // failed to create project
	ErrProjectDelete                   = errors.New("failed to delete project")                     // failed to delete project
	ErrProjectGet                      = errors.New("failed to get project")                        // failed to get project
	ErrProjectList                     = errors.New("failed to list projects")                      // failed to list projects
	ErrProjectUpdate                   = errors.New("failed to update project")                     // failed to update project
	ErrFeatureDisabled                 = errors.New("feature is not enabled")                       // license feature is not enabled
	ErrQuotaExceeded                   = errors.New("quota exceeded")                               // quota exceeded
	ErrQuotaInvalid                    = errors.New("invalid quota")                                // invalid quota
	ErrQuotaUsageGet                   = errors.New("failed to get usage of quota")                 // failed to get usage of quota
	ErrRoleAddMember                   = errors.New("failed to add member to role")                 // failed to add member to role
	ErrRoleCreate                      = errors.New("failed to create role")                        // failed to create role
	ErrRoleDelete                      = errors.New("failed to delete role")                        // failed to delete role
	ErrRoleGet                         = errors.New("failed to get role")                           // failed to get role
	ErrRoleGetBelongsTo                = errors.New("failed to get roles that belongs to")          // failed to get roles that belongs to
	ErrRoleRemoveMember                = errors.New("failed to remove member from role")            // failed to remove member from role
	ErrRoleUpdate                      = errors.New("failed to update role")                        // failed to update role
	ErrTeamAddMember                   = errors.New("failed to add member to team")                 // failed to add member to team
	ErrTeamCreate                      = errors.New("failed to create team")                        // failed to create team
	ErrTeamDelete                      = errors.New("failed to delete team")                        // failed to delete team
	ErrTeamGet                         = errors.New("failed to get team")                           // failed to get team
	ErrTeamGetBelongsTo                = errors.New("failed to get teams that belongs to")          // failed to get teams that belongs to
	ErrTeamRemoveMember                = errors.New("failed to remove member from team")            // failed to remove member from team
	ErrTeamUpdate                      = errors.New("failed to update team")                        // failed to update team
	ErrStaticFileCreate                = errors.New("failed to create static file")                 // failed to create static file
	ErrStaticFileDelete                = errors.New("failed to delete static file")                 // failed to delete static file
	ErrStaticFileGet                   = errors.New("failed to get static file")                    // failed to get static file
	ErrStaticFileInvalidPath           = errors.New("invalid static file path is provided")         // invalid static file path was provided
	ErrStaticFileUpdate                = errors.New("failed to update static file")                 // failed to update static file
	ErrSearchDelete                    = errors.New("failed to delete search document")             // failed to delete search document
	ErrSearchGet                       = errors.New("failed to search")                             // failed to search
	ErrSearchIndex                     = errors.New("failed to index search document")              // failed to index search document
	ErrSearchReindex                   = errors.New("failed to reindex search documents")           // failed to reindex search documents
	ErrSystemHealthCheck               = errors.New("system health check failed")                   // system health check failed
	ErrTodoCreate                      = errors.New("failed to create todo")                        // failed to create todo
	ErrTodoDelete                      = errors.New("failed to delete todo")                        // failed to delete todo
	ErrTodoGet                         = errors.New("failed to get todo")                           // failed to get todo
	ErrTodoList                        = errors.New("failed to list todos")                         // failed to list todos
	ErrTodoUpdate                      = errors.New("failed to update todo")                        // failed to update todo
	ErrUserCreate                      = errors.New("failed to create user")                        // failed to create user
	ErrUserCreateUserToken             = errors.New("failed to create user token")                  // failed to create user token
	ErrUserDelete                      = errors.New("failed to delete user")                        // failed to delete user
	ErrUserDeleteUserToken             = errors.New("failed to delete user token")                  // failed to delete user token
	ErrUserGet                         = errors.New("failed to get user")                           // failed to get user
	ErrUserList                        = errors.New("failed to list users")                         // failed to list users
	ErrUserUpdate                      = errors.New("failed to update user")                        // failed to update user
	ErrUserVerifyToken                 = errors.New("failed to verify user token")                  // failed to verify user token
)
