package service

import "errors"

var (
	ErrEmailSend                       = errors.New("failed to send email")                           // failed to send email
	ErrExpiredToken                    = errors.New("expired token")                                  // expired token
	ErrInvalidEmail                    = errors.New("invalid email address")                          // invalid email address
	ErrInvalidPaginationParams         = errors.New("invalid pagination parameters")                  // invalid pagination parameters
	ErrInvalidToken                    = errors.New("invalid token")                                  // invalid token
	ErrLicenseGet                      = errors.New("failed to get license")                          // failed to get license
	ErrLicensePing                     = errors.New("failed to ping license")                         // failed to ping license
	ErrNoLicenseService                = errors.New("no license service provided")                    // no license service provided
	ErrNoNotificationRepository        = errors.New("no notification repository provided")            // no notification repository provided
	ErrNoNotificationService           = errors.New("no notification service provided")               // no notification service provided
	ErrNoNamespaceRepository           = errors.New("no namespace repository provided")               // no namespace repository provided
	ErrNoOrganizationRepository        = errors.New("no organization repository provided")            // no organization repository provided
	ErrNoPermission                    = errors.New("no permission")                                  // no permission
	ErrNoPermissionRepository          = errors.New("no permission repository provided")              // no permission repository provided
	ErrNoPermissionService             = errors.New("no permission service provided")                 // no permission service provided
	ErrNoResources                     = errors.New("no resources provided")                          // no resources provided
	ErrNoRoleRepository                = errors.New("no role repository provided")                    // no role repository provided
	ErrNotificationCreate              = errors.New("failed to create notification")                  // failed to create notification
	ErrNotificationDelete              = errors.New("failed to delete notification")                  // failed to delete notification
	ErrNotificationGet                 = errors.New("failed to get notification")                     // failed to get notification
	ErrNotificationGetAllByRecipient   = errors.New("failed to get notifications")                    // failed to get notifications
	ErrNotificationUpdate              = errors.New("failed to update notification")                  // failed to update notification
	ErrNamespaceCreate                 = errors.New("failed to create namespace")                     // failed to create namespace
	ErrNamespaceDelete                 = errors.New("failed to delete namespace")                     // failed to delete namespace
	ErrNamespaceGet                    = errors.New("failed to get namespace")                        // failed to get namespace
	ErrNamespaceGetAll                 = errors.New("failed to get namespaces")                       // failed to get namespaces
	ErrNamespaceUpdate                 = errors.New("failed to update namespace")                     // failed to update namespace
	ErrNoTodoRepository                = errors.New("no todo repository provided")                    // no todo repository provided
	ErrNoUser                          = errors.New("no user provided")                               // no user provided
	ErrNoUserRepository                = errors.New("no user repository provided")                    // no user repository provided
	ErrNoUserTokenRepository           = errors.New("no user token repository provided")              // no user token repository provided
	ErrNoEmailService                  = errors.New("no email service provided")                      // no email service provided
	ErrNoVersionInfo                   = errors.New("no version info provided")                       // no version info provided
	ErrOrganizationCreate              = errors.New("failed to create organization")                  // failed to create organization
	ErrOrganizationDelete              = errors.New("failed to delete organization")                  // failed to delete organization
	ErrOrganizationGet                 = errors.New("failed to get organization")                     // failed to get organization
	ErrOrganizationGetAll              = errors.New("failed to get organizations")                    // failed to get organizations
	ErrOrganizationMemberAdd           = errors.New("failed to add member to organization")           // failed to add member to organization
	ErrOrganizationMemberAlreadyExists = errors.New("user is already a member of the organization")   // user is already a member of the organization
	ErrOrganizationMemberInvite        = errors.New("failed to invite member to organization")        // failed to invite member to organization
	ErrOrganizationMemberInvalidStatus = errors.New("user status is not valid for invitation")        // user status is not valid for invitation
	ErrOrganizationMemberRemove        = errors.New("failed to remove member from organization")      // failed to remove member from organization
	ErrOrganizationInviteRevoke        = errors.New("failed to revoke invitation")                    // failed to revoke invitation
	ErrOrganizationInviteAccept        = errors.New("failed to accept invitation")                    // failed to accept invitation
	ErrOrganizationMembersGet          = errors.New("failed to get members of organization")          // failed to get members of organization
	ErrOrganizationUpdate              = errors.New("failed to update organization")                  // failed to update organization
	ErrPermissionCreate                = errors.New("failed to create permission")                    // failed to create permission
	ErrPermissionDelete                = errors.New("failed to delete permission")                    // failed to delete permission
	ErrPermissionGet                   = errors.New("failed to get permission")                       // failed to get permission
	ErrPermissionGetBySubject          = errors.New("failed to get permission by subject")            // failed to get permission by subject
	ErrPermissionGetBySubjectAndTarget = errors.New("failed to get permission by subject and target") // failed to get permission by subject and target
	ErrPermissionGetByTarget           = errors.New("failed to get permission by target")             // failed to get permission by target
	ErrPermissionHasAnyRelation        = errors.New("failed to check if permission has any relation") // failed to check if permission has any relation
	ErrPermissionHasPermission         = errors.New("failed to check if permission has permission")   // failed to check if permission has permission
	ErrPermissionHasSystemRole         = errors.New("failed to check if permission has system role")  // failed to check if permission has system role
	ErrPermissionUpdate                = errors.New("failed to update permission")                    // failed to update permission
	ErrQuotaExceeded                   = errors.New("quota exceeded")                                 // quota exceeded
	ErrQuotaInvalid                    = errors.New("invalid quota")                                  // invalid quota
	ErrQuotaUsageGet                   = errors.New("failed to get usage of quota")                   // failed to get usage of quota
	ErrRoleAddMember                   = errors.New("failed to add member to role")                   // failed to add member to role
	ErrRoleCreate                      = errors.New("failed to create role")                          // failed to create role
	ErrRoleDelete                      = errors.New("failed to delete role")                          // failed to delete role
	ErrRoleGet                         = errors.New("failed to get role")                             // failed to get role
	ErrRoleGetBelongsTo                = errors.New("failed to get roles that belongs to")            // failed to get roles that belongs to
	ErrRoleRemoveMember                = errors.New("failed to remove member from role")              // failed to remove member from role
	ErrRoleUpdate                      = errors.New("failed to update role")                          // failed to update role
	ErrRoleAddPermission               = errors.New("failed to add permission to role")               // failed to add permission to role
	ErrRoleRemovePermission            = errors.New("failed to remove permission from role")          // failed to remove permission from role
	ErrRoleGetPermissions              = errors.New("failed to get role permissions")                 // failed to get role permissions
	ErrSystemHealthCheck               = errors.New("system health check failed")                     // system health check failed
	ErrTodoCreate                      = errors.New("failed to create todo")                          // failed to create todo
	ErrTodoDelete                      = errors.New("failed to delete todo")                          // failed to delete todo
	ErrTodoGet                         = errors.New("failed to get todo")                             // failed to get todo
	ErrTodoGetAll                      = errors.New("failed to get todos")                            // failed to get todos
	ErrTodoUpdate                      = errors.New("failed to update todo")                          // failed to update todo
	ErrUserCreate                      = errors.New("failed to create user")                          // failed to create user
	ErrUserCreateUserToken             = errors.New("failed to create user token")                    // failed to create user token
	ErrUserDelete                      = errors.New("failed to delete user")                          // failed to delete user
	ErrUserDeleteUserToken             = errors.New("failed to delete user token")                    // failed to delete user token
	ErrUserGet                         = errors.New("failed to get user")                             // failed to get user
	ErrUserGetAll                      = errors.New("failed to get users")                            // failed to get users
	ErrUserUpdate                      = errors.New("failed to update user")                          // failed to update user
	ErrUserVerifyToken                 = errors.New("failed to verify user token")                    // failed to verify user token
)
