// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/opcotech/elemo/internal/service (interfaces: PermissionService)
//
// Generated by this command:
//
//	mockgen -destination=permission_mock_gen.go -package=service -mock_names PermissionService=MockPermissionService . PermissionService
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	model "github.com/opcotech/elemo/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockPermissionService is a mock of PermissionService interface.
type MockPermissionService struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionServiceMockRecorder
	isgomock struct{}
}

// MockPermissionServiceMockRecorder is the mock recorder for MockPermissionService.
type MockPermissionServiceMockRecorder struct {
	mock *MockPermissionService
}

// NewMockPermissionService creates a new mock instance.
func NewMockPermissionService(ctrl *gomock.Controller) *MockPermissionService {
	mock := &MockPermissionService{ctrl: ctrl}
	mock.recorder = &MockPermissionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionService) EXPECT() *MockPermissionServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPermissionService) Create(ctx context.Context, opts CreatePermissionOpts) (*Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, opts)
	ret0, _ := ret[0].(*Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPermissionServiceMockRecorder) Create(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPermissionService)(nil).Create), ctx, opts)
}

// CtxUserCreate mocks base method.
func (m *MockPermissionService) CtxUserCreate(ctx context.Context, opts CreatePermissionOpts) (*Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CtxUserCreate", ctx, opts)
	ret0, _ := ret[0].(*Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CtxUserCreate indicates an expected call of CtxUserCreate.
func (mr *MockPermissionServiceMockRecorder) CtxUserCreate(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CtxUserCreate", reflect.TypeOf((*MockPermissionService)(nil).CtxUserCreate), ctx, opts)
}

// CtxUserDelete mocks base method.
func (m *MockPermissionService) CtxUserDelete(ctx context.Context, id model.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CtxUserDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// CtxUserDelete indicates an expected call of CtxUserDelete.
func (mr *MockPermissionServiceMockRecorder) CtxUserDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CtxUserDelete", reflect.TypeOf((*MockPermissionService)(nil).CtxUserDelete), ctx, id)
}

// CtxUserHasAnyRelation mocks base method.
func (m *MockPermissionService) CtxUserHasAnyRelation(ctx context.Context, target model.ID) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CtxUserHasAnyRelation", ctx, target)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CtxUserHasAnyRelation indicates an expected call of CtxUserHasAnyRelation.
func (mr *MockPermissionServiceMockRecorder) CtxUserHasAnyRelation(ctx, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CtxUserHasAnyRelation", reflect.TypeOf((*MockPermissionService)(nil).CtxUserHasAnyRelation), ctx, target)
}

// CtxUserHasPermission mocks base method.
func (m *MockPermissionService) CtxUserHasPermission(ctx context.Context, target model.ID, permissions ...model.PermissionKind) bool {
	m.ctrl.T.Helper()
	varargs := []any{ctx, target}
	for _, a := range permissions {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CtxUserHasPermission", varargs...)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CtxUserHasPermission indicates an expected call of CtxUserHasPermission.
func (mr *MockPermissionServiceMockRecorder) CtxUserHasPermission(ctx, target any, permissions ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, target}, permissions...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CtxUserHasPermission", reflect.TypeOf((*MockPermissionService)(nil).CtxUserHasPermission), varargs...)
}

// CtxUserHasSystemRole mocks base method.
func (m *MockPermissionService) CtxUserHasSystemRole(ctx context.Context, roles ...model.SystemRole) bool {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range roles {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CtxUserHasSystemRole", varargs...)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CtxUserHasSystemRole indicates an expected call of CtxUserHasSystemRole.
func (mr *MockPermissionServiceMockRecorder) CtxUserHasSystemRole(ctx any, roles ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, roles...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CtxUserHasSystemRole", reflect.TypeOf((*MockPermissionService)(nil).CtxUserHasSystemRole), varargs...)
}

// CtxUserUpdate mocks base method.
func (m *MockPermissionService) CtxUserUpdate(ctx context.Context, id model.ID, kind model.PermissionKind) (*Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CtxUserUpdate", ctx, id, kind)
	ret0, _ := ret[0].(*Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CtxUserUpdate indicates an expected call of CtxUserUpdate.
func (mr *MockPermissionServiceMockRecorder) CtxUserUpdate(ctx, id, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CtxUserUpdate", reflect.TypeOf((*MockPermissionService)(nil).CtxUserUpdate), ctx, id, kind)
}

// Delete mocks base method.
func (m *MockPermissionService) Delete(ctx context.Context, id model.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPermissionServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPermissionService)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockPermissionService) Get(ctx context.Context, id model.ID) (*Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPermissionServiceMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPermissionService)(nil).Get), ctx, id)
}

// GetBySubject mocks base method.
func (m *MockPermissionService) GetBySubject(ctx context.Context, id model.ID) ([]*Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySubject", ctx, id)
	ret0, _ := ret[0].([]*Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySubject indicates an expected call of GetBySubject.
func (mr *MockPermissionServiceMockRecorder) GetBySubject(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySubject", reflect.TypeOf((*MockPermissionService)(nil).GetBySubject), ctx, id)
}

// GetBySubjectAndTarget mocks base method.
func (m *MockPermissionService) GetBySubjectAndTarget(ctx context.Context, source, target model.ID) ([]*Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySubjectAndTarget", ctx, source, target)
	ret0, _ := ret[0].([]*Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySubjectAndTarget indicates an expected call of GetBySubjectAndTarget.
func (mr *MockPermissionServiceMockRecorder) GetBySubjectAndTarget(ctx, source, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySubjectAndTarget", reflect.TypeOf((*MockPermissionService)(nil).GetBySubjectAndTarget), ctx, source, target)
}

// GetByTarget mocks base method.
func (m *MockPermissionService) GetByTarget(ctx context.Context, id model.ID) ([]*Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTarget", ctx, id)
	ret0, _ := ret[0].([]*Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTarget indicates an expected call of GetByTarget.
func (mr *MockPermissionServiceMockRecorder) GetByTarget(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTarget", reflect.TypeOf((*MockPermissionService)(nil).GetByTarget), ctx, id)
}

// HasAnyRelation mocks base method.
func (m *MockPermissionService) HasAnyRelation(ctx context.Context, source, target model.ID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasAnyRelation", ctx, source, target)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasAnyRelation indicates an expected call of HasAnyRelation.
func (mr *MockPermissionServiceMockRecorder) HasAnyRelation(ctx, source, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasAnyRelation", reflect.TypeOf((*MockPermissionService)(nil).HasAnyRelation), ctx, source, target)
}

// HasPermission mocks base method.
func (m *MockPermissionService) HasPermission(ctx context.Context, subject, target model.ID, kinds ...model.PermissionKind) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, subject, target}
	for _, a := range kinds {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HasPermission", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasPermission indicates an expected call of HasPermission.
func (mr *MockPermissionServiceMockRecorder) HasPermission(ctx, subject, target any, kinds ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, subject, target}, kinds...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasPermission", reflect.TypeOf((*MockPermissionService)(nil).HasPermission), varargs...)
}

// HasSystemRole mocks base method.
func (m *MockPermissionService) HasSystemRole(ctx context.Context, source model.ID, roles ...model.SystemRole) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, source}
	for _, a := range roles {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HasSystemRole", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasSystemRole indicates an expected call of HasSystemRole.
func (mr *MockPermissionServiceMockRecorder) HasSystemRole(ctx, source any, roles ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, source}, roles...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasSystemRole", reflect.TypeOf((*MockPermissionService)(nil).HasSystemRole), varargs...)
}

// Update mocks base method.
func (m *MockPermissionService) Update(ctx context.Context, id model.ID, kind model.PermissionKind) (*Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, kind)
	ret0, _ := ret[0].(*Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPermissionServiceMockRecorder) Update(ctx, id, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPermissionService)(nil).Update), ctx, id, kind)
}
