// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/opcotech/elemo/internal/service (interfaces: SearchService)
//
// Generated by this command:
//
//	mockgen -destination=search_mock_gen.go -package=service -mock_names SearchService=MockSearchService . SearchService
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	model "github.com/opcotech/elemo/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockSearchService is a mock of SearchService interface.
type MockSearchService struct {
	ctrl     *gomock.Controller
	recorder *MockSearchServiceMockRecorder
	isgomock struct{}
}

// MockSearchServiceMockRecorder is the mock recorder for MockSearchService.
type MockSearchServiceMockRecorder struct {
	mock *MockSearchService
}

// NewMockSearchService creates a new mock instance.
func NewMockSearchService(ctrl *gomock.Controller) *MockSearchService {
	mock := &MockSearchService{ctrl: ctrl}
	mock.recorder = &MockSearchServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchService) EXPECT() *MockSearchServiceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockSearchService) Delete(ctx context.Context, id model.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSearchServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSearchService)(nil).Delete), ctx, id)
}

// DeleteByScope mocks base method.
func (m *MockSearchService) DeleteByScope(ctx context.Context, scope model.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByScope", ctx, scope)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByScope indicates an expected call of DeleteByScope.
func (mr *MockSearchServiceMockRecorder) DeleteByScope(ctx, scope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByScope", reflect.TypeOf((*MockSearchService)(nil).DeleteByScope), ctx, scope)
}

// Index mocks base method.
func (m *MockSearchService) Index(ctx context.Context, input IndexInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Index", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Index indicates an expected call of Index.
func (mr *MockSearchServiceMockRecorder) Index(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Index", reflect.TypeOf((*MockSearchService)(nil).Index), ctx, input)
}

// Reindex mocks base method.
func (m *MockSearchService) Reindex(ctx context.Context, sources SearchReindexSources) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reindex", ctx, sources)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reindex indicates an expected call of Reindex.
func (mr *MockSearchServiceMockRecorder) Reindex(ctx, sources any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reindex", reflect.TypeOf((*MockSearchService)(nil).Reindex), ctx, sources)
}

// Search mocks base method.
func (m *MockSearchService) Search(ctx context.Context, q SearchQuery) (Page[*SearchResult], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, q)
	ret0, _ := ret[0].(Page[*SearchResult])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockSearchServiceMockRecorder) Search(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockSearchService)(nil).Search), ctx, q)
}
