import type {
  ActivityEntry,
  AttentionSignal,
  DocumentBody,
  GlobalSearchEntry,
  Person,
  Relation,
  SavedView,
  TimelineEntry,
} from "./types";

import type { WorkItem } from "@/lib/work/model";

export const mockPeople = [
  {
    dataSource: "mock",
    id: "person-ada",
    displayName: "Ada Lovelace",
    handle: "ada",
    email: "ada@example.test",
    avatarUrl: null,
    title: "Staff Product Engineer",
    team: "Product Platform",
  },
  {
    dataSource: "mock",
    id: "person-grace",
    displayName: "Grace Hopper",
    handle: "grace",
    email: "grace@example.test",
    avatarUrl: null,
    title: "Engineering Manager",
    team: "Product Platform",
  },
  {
    dataSource: "mock",
    id: "person-katherine",
    displayName: "Katherine Johnson",
    handle: "katherine",
    email: "katherine@example.test",
    avatarUrl: null,
    title: "Principal Reliability Engineer",
    team: "Infrastructure",
  },
  {
    dataSource: "mock",
    id: "person-margaret",
    displayName: "Margaret Hamilton",
    handle: "margaret",
    email: "margaret@example.test",
    avatarUrl: null,
    title: "Product Designer",
    team: "Product Design",
  },
] as const satisfies readonly Person[];

export const mockWorkItems = [
  {
    dataSource: "mock",
    id: "lmo-101",
    key: "LMO-101",
    title: "Preserve work context across projections",
    summary:
      "Keep filters and the selected inspector item stable while switching views.",
    namespaceId: "namespace-product",
    projectId: "project-web",
    status: "in progress",
    priority: "highest",
    assigneeIds: ["person-ada"],
    reviewerIds: [],
    assigneeId: "person-ada",
    creatorId: "person-grace",
    labelIds: ["frontend", "navigation"],
    startDate: null,
    rank: 10,
    dueDate: "2026-08-09T17:00:00.000Z",
    createdAt: "2026-07-28T09:00:00.000Z",
    updatedAt: "2026-08-10T07:30:00.000Z",
  },
  {
    dataSource: "mock",
    id: "lmo-102",
    key: "LMO-102",
    title: "Add keyboard-first quick create",
    summary: "Create work without losing the active namespace and project.",
    namespaceId: "namespace-product",
    projectId: "project-web",
    status: "in review",
    priority: "high",
    assigneeIds: ["person-grace"],
    reviewerIds: [],
    assigneeId: "person-grace",
    creatorId: "person-ada",
    labelIds: ["frontend", "accessibility"],
    startDate: null,
    rank: 20,
    dueDate: "2026-08-10T20:00:00.000Z",
    createdAt: "2026-08-01T11:00:00.000Z",
    updatedAt: "2026-08-09T16:10:00.000Z",
  },
  {
    dataSource: "mock",
    id: "lmo-103",
    key: "LMO-103",
    title: "Document saved-view query semantics",
    summary:
      "Describe portable filters, grouping, sorting, and display choices.",
    namespaceId: "namespace-product",
    projectId: "project-web",
    status: "backlog",
    priority: "normal",
    assigneeIds: [],
    reviewerIds: [],
    assigneeId: null,
    creatorId: "person-margaret",
    labelIds: ["documentation"],
    startDate: null,
    rank: 30,
    dueDate: null,
    createdAt: "2026-08-04T12:00:00.000Z",
    updatedAt: "2026-08-08T10:45:00.000Z",
  },
  {
    dataSource: "mock",
    id: "lmo-201",
    key: "LMO-201",
    title: "Normalize relationship traversal",
    summary: "Return incoming and outgoing edges with deterministic ordering.",
    namespaceId: "namespace-product",
    projectId: "project-api",
    status: "blocked",
    priority: "high",
    assigneeIds: ["person-ada"],
    reviewerIds: [],
    assigneeId: "person-ada",
    creatorId: "person-grace",
    labelIds: ["api", "relations"],
    startDate: null,
    rank: 10,
    dueDate: "2026-08-14T17:00:00.000Z",
    createdAt: "2026-07-22T14:00:00.000Z",
    updatedAt: "2026-08-10T08:20:00.000Z",
  },
  {
    dataSource: "mock",
    id: "ops-301",
    key: "OPS-301",
    title: "Review delayed notification deliveries",
    summary: "Correlate delivery latency with the most recent deployment.",
    namespaceId: "namespace-operations",
    projectId: "project-reliability",
    status: "in progress",
    priority: "highest",
    assigneeIds: ["person-katherine"],
    reviewerIds: [],
    assigneeId: "person-katherine",
    creatorId: "person-katherine",
    labelIds: ["reliability", "notifications"],
    startDate: null,
    rank: 10,
    dueDate: "2026-08-11T14:00:00.000Z",
    createdAt: "2026-08-08T06:30:00.000Z",
    updatedAt: "2026-08-10T09:05:00.000Z",
  },
  {
    dataSource: "mock",
    id: "ops-302",
    key: "OPS-302",
    title: "Publish incident follow-up",
    summary: "Capture owners and due dates for the incident action items.",
    namespaceId: "namespace-operations",
    projectId: null,
    status: "done",
    priority: "low",
    assigneeIds: ["person-katherine"],
    reviewerIds: [],
    assigneeId: "person-katherine",
    creatorId: "person-grace",
    labelIds: ["documentation", "incident"],
    startDate: null,
    rank: 20,
    dueDate: "2026-08-07T17:00:00.000Z",
    createdAt: "2026-08-05T08:00:00.000Z",
    updatedAt: "2026-08-07T15:00:00.000Z",
  },
] as const satisfies readonly WorkItem[];

export const mockSavedViews = [
  {
    dataSource: "mock",
    id: "view-my-urgent-work",
    name: "My urgent work",
    description: "Urgent, active work assigned to Ada.",
    ownerId: "person-ada",
    scope: { type: "global" },
    layout: "list",
    filters: {
      statuses: ["in review", "in progress", "blocked"],
      priorities: ["highest"],
      assigneeIds: ["person-ada"],
    },
    sort: [
      { field: "dueDate", direction: "asc" },
      { field: "priority", direction: "desc" },
    ],
    groupBy: "none",
    isFavorite: true,
  },
  {
    dataSource: "mock",
    id: "view-product-planning",
    name: "Product planning",
    description: "Planned and backlog work across the product namespace.",
    ownerId: "person-grace",
    scope: { type: "namespace", namespaceId: "namespace-product" },
    layout: "board",
    filters: { statuses: ["backlog", "in review"] },
    sort: [{ field: "rank", direction: "asc" }],
    groupBy: "status",
    isFavorite: true,
  },
  {
    dataSource: "mock",
    id: "view-web-delivery",
    name: "Web delivery",
    description: "Active delivery items for the Elemo web project.",
    ownerId: "person-ada",
    scope: {
      type: "project",
      namespaceId: "namespace-product",
      projectId: "project-web",
    },
    layout: "timeline",
    filters: { statuses: ["in review", "in progress", "blocked"] },
    sort: [{ field: "dueDate", direction: "asc" }],
    groupBy: "assignee",
    isFavorite: false,
  },
  {
    dataSource: "mock",
    id: "view-reliability-attention",
    name: "Reliability attention",
    description: "High-priority work in the reliability project.",
    ownerId: "person-katherine",
    scope: {
      type: "project",
      namespaceId: "namespace-operations",
      projectId: "project-reliability",
    },
    layout: "table",
    filters: { priorities: ["highest", "high"] },
    sort: [{ field: "updatedAt", direction: "desc" }],
    groupBy: "priority",
    isFavorite: true,
  },
] as const satisfies readonly SavedView[];

export const mockDocumentBodies = [
  {
    dataSource: "mock",
    documentId: "document-projection-model",
    title: "Work projection model",
    namespaceId: "namespace-product",
    projectId: "project-web",
    excerpt: "Board, list, table, and timeline are projections over one query.",
    blocks: [
      {
        id: "projection-heading",
        type: "heading",
        level: 1,
        text: "One entity set, many projections",
      },
      {
        id: "projection-intro",
        type: "paragraph",
        text: "Scope and filters choose entities. Layout changes only how those entities are presented.",
      },
      {
        id: "projection-rules",
        type: "checklist",
        items: [
          { text: "Keep scope in validated route search", checked: true },
          { text: "Preserve selection when changing layout", checked: true },
          {
            text: "Restore scroll after closing the inspector",
            checked: false,
          },
        ],
      },
      {
        id: "projection-warning",
        type: "callout",
        tone: "warning",
        text: "Work projections remain fixture-backed until a work API exists.",
      },
    ],
    updatedAt: "2026-08-09T18:00:00.000Z",
  },
  {
    dataSource: "mock",
    documentId: "document-incident-review",
    title: "Notification delivery incident review",
    namespaceId: "namespace-operations",
    projectId: "project-reliability",
    excerpt: "Review of delayed notification deliveries and follow-up work.",
    blocks: [
      {
        id: "incident-heading",
        type: "heading",
        level: 1,
        text: "Notification delivery incident",
      },
      {
        id: "incident-summary",
        type: "paragraph",
        text: "A deployment increased queue latency for a subset of notification deliveries.",
      },
      {
        id: "incident-code",
        type: "code",
        language: "text",
        code: "p95 delivery latency: 18m\nrecovery time: 42m",
      },
      {
        id: "incident-status",
        type: "callout",
        tone: "success",
        text: "Delivery latency has returned to its normal range.",
      },
    ],
    updatedAt: "2026-08-08T13:30:00.000Z",
  },
] as const satisfies readonly DocumentBody[];

const projectionWorkRef = {
  id: "lmo-101",
  type: "work-item",
  title: "LMO-101 Preserve work context across projections",
} as const;

const relationWorkRef = {
  id: "lmo-201",
  type: "work-item",
  title: "LMO-201 Normalize relationship traversal",
} as const;

const projectionDocumentRef = {
  id: "document-projection-model",
  type: "document",
  title: "Work projection model",
} as const;

const adaPersonRef = {
  id: "person-ada",
  type: "person",
  title: "Ada Lovelace",
} as const;

export const mockRelations = [
  {
    dataSource: "mock",
    id: "relation-projection-document",
    kind: "documents",
    from: projectionDocumentRef,
    to: projectionWorkRef,
    createdAt: "2026-08-02T10:00:00.000Z",
    createdBy: "person-margaret",
  },
  {
    dataSource: "mock",
    id: "relation-work-dependency",
    kind: "depends-on",
    from: projectionWorkRef,
    to: relationWorkRef,
    createdAt: "2026-08-06T12:15:00.000Z",
    createdBy: "person-ada",
  },
  {
    dataSource: "mock",
    id: "relation-work-owner",
    kind: "owned-by",
    from: projectionWorkRef,
    to: adaPersonRef,
    createdAt: "2026-08-07T09:45:00.000Z",
    createdBy: "person-grace",
  },
] as const satisfies readonly Relation[];

export const mockActivity = [
  {
    dataSource: "mock",
    id: "activity-lmo-101-created",
    entity: projectionWorkRef,
    actorId: "person-grace",
    action: "created",
    detail: "Created the work item.",
    occurredAt: "2026-07-28T09:00:00.000Z",
  },
  {
    dataSource: "mock",
    id: "activity-lmo-101-assigned",
    entity: projectionWorkRef,
    actorId: "person-grace",
    action: "assigned",
    detail: "Assigned the work item to Ada Lovelace.",
    occurredAt: "2026-08-04T15:20:00.000Z",
  },
  {
    dataSource: "mock",
    id: "activity-lmo-101-status",
    entity: projectionWorkRef,
    actorId: "person-ada",
    action: "status-changed",
    detail: "Moved the work item from Planned to In progress.",
    occurredAt: "2026-08-09T08:10:00.000Z",
  },
  {
    dataSource: "mock",
    id: "activity-document-comment",
    entity: projectionDocumentRef,
    actorId: "person-margaret",
    action: "commented",
    detail: "Added the inspector context acceptance criterion.",
    occurredAt: "2026-08-09T18:00:00.000Z",
  },
] as const satisfies readonly ActivityEntry[];

export const mockTimeline = [
  {
    dataSource: "mock",
    id: "timeline-lmo-101",
    workItemId: "lmo-101",
    namespaceId: "namespace-product",
    projectId: "project-web",
    title: "Preserve work context across projections",
    startAt: "2026-08-03T09:00:00.000Z",
    endAt: "2026-08-12T17:00:00.000Z",
    kind: "work",
  },
  {
    dataSource: "mock",
    id: "timeline-lmo-102",
    workItemId: "lmo-102",
    namespaceId: "namespace-product",
    projectId: "project-web",
    title: "Add keyboard-first quick create",
    startAt: "2026-08-10T09:00:00.000Z",
    endAt: "2026-08-17T17:00:00.000Z",
    kind: "work",
  },
  {
    dataSource: "mock",
    id: "timeline-lmo-201",
    workItemId: "lmo-201",
    namespaceId: "namespace-product",
    projectId: "project-api",
    title: "Relationship traversal ready",
    startAt: "2026-08-14T17:00:00.000Z",
    endAt: "2026-08-14T17:00:00.000Z",
    kind: "milestone",
  },
  {
    dataSource: "mock",
    id: "timeline-ops-301",
    workItemId: "ops-301",
    namespaceId: "namespace-operations",
    projectId: "project-reliability",
    title: "Review delayed notification deliveries",
    startAt: "2026-08-08T09:00:00.000Z",
    endAt: "2026-08-11T14:00:00.000Z",
    kind: "work",
  },
] as const satisfies readonly TimelineEntry[];

export const mockAttentionSignals = [
  {
    dataSource: "mock",
    id: "attention-lmo-101-overdue",
    workItemId: "lmo-101",
    namespaceId: "namespace-product",
    projectId: "project-web",
    personId: "person-ada",
    reason: "overdue",
    severity: "critical",
    summary: "LMO-101 is overdue.",
    createdAt: "2026-08-10T00:00:00.000Z",
    acknowledgedAt: null,
  },
  {
    dataSource: "mock",
    id: "attention-lmo-201-blocked",
    workItemId: "lmo-201",
    namespaceId: "namespace-product",
    projectId: "project-api",
    personId: "person-ada",
    reason: "blocked",
    severity: "warning",
    summary: "LMO-201 has been blocked for two days.",
    createdAt: "2026-08-10T08:20:00.000Z",
    acknowledgedAt: null,
  },
  {
    dataSource: "mock",
    id: "attention-ops-301-due",
    workItemId: "ops-301",
    namespaceId: "namespace-operations",
    projectId: "project-reliability",
    personId: "person-katherine",
    reason: "due-soon",
    severity: "info",
    summary: "OPS-301 is due tomorrow.",
    createdAt: "2026-08-10T09:05:00.000Z",
    acknowledgedAt: null,
  },
  {
    dataSource: "mock",
    id: "attention-lmo-102-mention",
    workItemId: "lmo-102",
    namespaceId: "namespace-product",
    projectId: "project-web",
    personId: "person-grace",
    reason: "mentioned",
    severity: "info",
    summary: "Ada mentioned you in LMO-102.",
    createdAt: "2026-08-09T16:10:00.000Z",
    acknowledgedAt: "2026-08-09T17:00:00.000Z",
  },
] as const satisfies readonly AttentionSignal[];

export const mockGlobalSearchEntries: readonly GlobalSearchEntry[] = [
  ...mockWorkItems.map((item) => ({
    dataSource: "mock" as const,
    id: item.id,
    kind: "work-item" as const,
    title: `${item.key} ${item.title}`,
    subtitle: item.summary,
    keywords: [item.key, item.status, item.priority, ...item.labelIds],
    namespaceId: item.namespaceId,
    projectId: item.projectId,
    personId: item.assigneeId,
    href: `/work/${item.namespaceId}/${item.key}`,
  })),
  ...mockDocumentBodies.map((document) => ({
    dataSource: "mock" as const,
    id: document.documentId,
    kind: "document" as const,
    title: document.title,
    subtitle: document.excerpt,
    keywords: document.blocks.flatMap((block) =>
      "text" in block ? [block.text] : []
    ),
    namespaceId: document.namespaceId,
    projectId: document.projectId,
    personId: null,
    href: `/documents/${document.documentId}`,
  })),
  ...mockSavedViews.map((view) => ({
    dataSource: "mock" as const,
    id: view.id,
    kind: "saved-view" as const,
    title: view.name,
    subtitle: view.description,
    keywords: [view.layout, view.groupBy],
    namespaceId:
      view.scope.type === "namespace" || view.scope.type === "project"
        ? (view.scope.namespaceId ?? null)
        : null,
    projectId: view.scope.type === "project" ? view.scope.projectId : null,
    personId: view.ownerId,
    href: `/work?view=${view.id}`,
  })),
  ...mockPeople.map((person) => ({
    dataSource: "mock" as const,
    id: person.id,
    kind: "person" as const,
    title: person.displayName,
    subtitle: `${person.title} · ${person.team}`,
    keywords: [person.handle, person.email, person.team],
    namespaceId: null,
    projectId: null,
    personId: person.id,
    href: `/search?person=${person.id}`,
  })),
];
