export {
  mockActivity,
  mockAttentionSignals,
  mockDocumentBodies,
  mockGlobalSearchEntries,
  mockPeople,
  mockRelations,
  mockSavedViews,
  mockTimeline,
  mockWorkItems,
} from "./fixtures";
export { resolveDemoPerson } from "./demo-person";
export {
  getDocumentBody,
  getPerson,
  getWorkItem,
  isInScope,
  queryWorkItems,
  searchGlobalFixtures,
  selectActivity,
  selectAttentionSignals,
  selectDocumentBodies,
  selectPeople,
  selectRelations,
  selectSavedViews,
  selectTimeline,
  selectWorkItems,
} from "./selectors";
export { API_BACKED_DOMAINS, MOCK_ONLY_DOMAINS } from "./types";

export type {
  ActivityAction,
  ActivityEntry,
  ActivityQuery,
  ApiBackedDomain,
  AttentionQuery,
  AttentionReason,
  AttentionSignal,
  DataSource,
  DocumentBlock,
  DocumentBody,
  DueDateFilter,
  EntityRef,
  EntityType,
  GlobalSearchEntry,
  GlobalSearchQuery,
  MockOnlyDomain,
  MockRecord,
  Person,
  PeopleQuery,
  Relation,
  RelationDirection,
  RelationKind,
  RelationQuery,
  SavedView,
  SavedViewQuery,
  Scope,
  SearchResultKind,
  TimelineEntry,
  TimelineQuery,
  WorkFilters,
  WorkItem,
  WorkItemQuery,
  WorkLayout,
  WorkNamespaceRef,
  WorkPerson,
  WorkPriority,
  WorkProjectRef,
  WorkSort,
  WorkSortField,
  WorkStatus,
} from "./types";
