export { resolveDemoPerson } from "./demo-person";
export {
  mockActivity,
  mockAttentionSignals,
  mockDocumentBodies,
  mockGlobalSearchEntries,
  mockPeople,
  mockRelations,
  mockSavedViews,
  mockTimeline,
  mockWorkItems,
} from "./fixtures";
export {
  getDocumentBody,
  getPerson,
  getWorkItem,
  searchGlobalFixtures,
  selectActivity,
  selectAttentionSignals,
  selectDocumentBodies,
  selectPeople,
  selectRelations,
  selectSavedViews,
  selectTimeline,
  selectWorkItems,
} from "./selectors";
export type {
  ActivityAction,
  ActivityEntry,
  ActivityQuery,
  ApiBackedDomain,
  AttentionQuery,
  AttentionReason,
  AttentionSignal,
  DocumentBlock,
  DocumentBody,
  EntityRef,
  EntityType,
  GlobalSearchEntry,
  GlobalSearchQuery,
  MockOnlyDomain,
  MockRecord,
  PeopleQuery,
  Person,
  Relation,
  RelationDirection,
  RelationKind,
  RelationQuery,
  SavedView,
  SavedViewQuery,
  SearchResultKind,
  TimelineEntry,
  TimelineQuery,
} from "./types";
export { API_BACKED_DOMAINS, MOCK_ONLY_DOMAINS } from "./types";
