/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated.inbox'
import { Route as AuthenticatedMyWorkRouteImport } from './routes/_authenticated.my-work'
import { Route as AuthenticatedNamespacesRouteImport } from './routes/_authenticated.namespaces'
import { Route as AuthenticatedOrganizationsRouteImport } from './routes/_authenticated.organizations'
import { Route as AuthenticatedPermissionDeniedRouteImport } from './routes/_authenticated.permission-denied'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated.search'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as OrganizationsJoinRouteImport } from './routes/organizations/join'
import { Route as AuthenticatedDocumentsDocumentIdRouteImport } from './routes/_authenticated.documents.$documentId'
import { Route as AuthenticatedNamespacesIndexRouteImport } from './routes/_authenticated.namespaces.index'
import { Route as AuthenticatedNamespacesNamespaceIdRouteImport } from './routes/_authenticated.namespaces.$namespaceId'
import { Route as AuthenticatedOrganizationsIndexRouteImport } from './routes/_authenticated.organizations.index'
import { Route as AuthenticatedOrganizationsOrganizationIdRouteImport } from './routes/_authenticated.organizations.$organizationId'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated.settings/index'
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated.settings/security'
import { Route as AuthenticatedWorkWorkIdRouteImport } from './routes/_authenticated.work.$workId'
import { Route as AuthenticatedNamespacesNamespaceIdIndexRouteImport } from './routes/_authenticated.namespaces.$namespaceId.index'
import { Route as AuthenticatedNamespacesNamespaceIdAdministrationRouteImport } from './routes/_authenticated.namespaces.$namespaceId.administration'
import { Route as AuthenticatedNamespacesNamespaceIdDocumentsRouteImport } from './routes/_authenticated.namespaces.$namespaceId.documents'
import { Route as AuthenticatedNamespacesNamespaceIdProjectsRouteImport } from './routes/_authenticated.namespaces.$namespaceId.projects'
import { Route as AuthenticatedNamespacesNamespaceIdWorkRouteImport } from './routes/_authenticated.namespaces.$namespaceId.work'
import { Route as AuthenticatedRelationsEntityTypeEntityIdRouteImport } from './routes/_authenticated.relations.$entityType.$entityId'
import { Route as AuthenticatedSettingsNamespacesIndexRouteImport } from './routes/_authenticated.settings/namespaces/index'
import { Route as AuthenticatedSettingsNamespacesNewRouteImport } from './routes/_authenticated.settings/namespaces/new'
import { Route as AuthenticatedSettingsOrganizationsIndexRouteImport } from './routes/_authenticated.settings/organizations/index'
import { Route as AuthenticatedSettingsOrganizationsNewRouteImport } from './routes/_authenticated.settings/organizations/new'
import { Route as AuthenticatedNamespacesNamespaceIdProjectsIndexRouteImport } from './routes/_authenticated.namespaces.$namespaceId.projects.index'
import { Route as AuthenticatedNamespacesNamespaceIdProjectsProjectIdRouteImport } from './routes/_authenticated.namespaces.$namespaceId.projects.$projectId'
import { Route as AuthenticatedSettingsOrganizationsOrganizationIdIndexRouteImport } from './routes/_authenticated.settings/organizations/$organizationId/index'
import { Route as AuthenticatedSettingsOrganizationsOrganizationIdEditRouteImport } from './routes/_authenticated.settings/organizations/$organizationId/edit'
import { Route as AuthenticatedNamespacesNamespaceIdProjectsProjectIdIndexRouteImport } from './routes/_authenticated.namespaces.$namespaceId.projects.$projectId.index'
import { Route as AuthenticatedNamespacesNamespaceIdProjectsProjectIdActivityRouteImport } from './routes/_authenticated.namespaces.$namespaceId.projects.$projectId.activity'
import { Route as AuthenticatedNamespacesNamespaceIdProjectsProjectIdDocumentsRouteImport } from './routes/_authenticated.namespaces.$namespaceId.projects.$projectId.documents'
import { Route as AuthenticatedNamespacesNamespaceIdProjectsProjectIdWorkRouteImport } from './routes/_authenticated.namespaces.$namespaceId.projects.$projectId.work'
import { Route as AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNewRouteImport } from './routes/_authenticated.settings/organizations/$organizationId/namespaces/new'
import { Route as AuthenticatedSettingsOrganizationsOrganizationIdRolesNewRouteImport } from './routes/_authenticated.settings/organizations/$organizationId/roles/new'
import { Route as AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdIndexRouteImport } from './routes/_authenticated.settings/organizations/$organizationId/namespaces/$namespaceId/index'
import { Route as AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdEditRouteImport } from './routes/_authenticated.settings/organizations/$organizationId/namespaces/$namespaceId/edit'
import { Route as AuthenticatedSettingsOrganizationsOrganizationIdRolesRoleIdEditRouteImport } from './routes/_authenticated.settings/organizations/$organizationId/roles/$roleId/edit'
import { Route as AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdProjectsNewRouteImport } from './routes/_authenticated.settings/organizations/$organizationId/namespaces/$namespaceId/projects/new'
import { Route as AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdProjectsProjectIdIndexRouteImport } from './routes/_authenticated.settings/organizations/$organizationId/namespaces/$namespaceId/projects/$projectId/index'
import { Route as AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdProjectsProjectIdEditRouteImport } from './routes/_authenticated.settings/organizations/$organizationId/namespaces/$namespaceId/projects/$projectId/edit'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyWorkRoute = AuthenticatedMyWorkRouteImport.update({
  id: '/my-work',
  path: '/my-work',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNamespacesRoute = AuthenticatedNamespacesRouteImport.update({
  id: '/namespaces',
  path: '/namespaces',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrganizationsRoute =
  AuthenticatedOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPermissionDeniedRoute =
  AuthenticatedPermissionDeniedRouteImport.update({
    id: '/permission-denied',
    path: '/permission-denied',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const OrganizationsJoinRoute = OrganizationsJoinRouteImport.update({
  id: '/organizations/join',
  path: '/organizations/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDocumentsDocumentIdRoute =
  AuthenticatedDocumentsDocumentIdRouteImport.update({
    id: '/documents/$documentId',
    path: '/documents/$documentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNamespacesIndexRoute =
  AuthenticatedNamespacesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedNamespacesRoute,
  } as any)
const AuthenticatedNamespacesNamespaceIdRoute =
  AuthenticatedNamespacesNamespaceIdRouteImport.update({
    id: '/$namespaceId',
    path: '/$namespaceId',
    getParentRoute: () => AuthenticatedNamespacesRoute,
  } as any)
const AuthenticatedOrganizationsIndexRoute =
  AuthenticatedOrganizationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrganizationsRoute,
  } as any)
const AuthenticatedOrganizationsOrganizationIdRoute =
  AuthenticatedOrganizationsOrganizationIdRouteImport.update({
    id: '/$organizationId',
    path: '/$organizationId',
    getParentRoute: () => AuthenticatedOrganizationsRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedWorkWorkIdRoute = AuthenticatedWorkWorkIdRouteImport.update({
  id: '/work/$workId',
  path: '/work/$workId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNamespacesNamespaceIdIndexRoute =
  AuthenticatedNamespacesNamespaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedNamespacesNamespaceIdRoute,
  } as any)
const AuthenticatedNamespacesNamespaceIdAdministrationRoute =
  AuthenticatedNamespacesNamespaceIdAdministrationRouteImport.update({
    id: '/administration',
    path: '/administration',
    getParentRoute: () => AuthenticatedNamespacesNamespaceIdRoute,
  } as any)
const AuthenticatedNamespacesNamespaceIdDocumentsRoute =
  AuthenticatedNamespacesNamespaceIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedNamespacesNamespaceIdRoute,
  } as any)
const AuthenticatedNamespacesNamespaceIdProjectsRoute =
  AuthenticatedNamespacesNamespaceIdProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedNamespacesNamespaceIdRoute,
  } as any)
const AuthenticatedNamespacesNamespaceIdWorkRoute =
  AuthenticatedNamespacesNamespaceIdWorkRouteImport.update({
    id: '/work',
    path: '/work',
    getParentRoute: () => AuthenticatedNamespacesNamespaceIdRoute,
  } as any)
const AuthenticatedRelationsEntityTypeEntityIdRoute =
  AuthenticatedRelationsEntityTypeEntityIdRouteImport.update({
    id: '/relations/$entityType/$entityId',
    path: '/relations/$entityType/$entityId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsNamespacesIndexRoute =
  AuthenticatedSettingsNamespacesIndexRouteImport.update({
    id: '/namespaces/',
    path: '/namespaces/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsNamespacesNewRoute =
  AuthenticatedSettingsNamespacesNewRouteImport.update({
    id: '/namespaces/new',
    path: '/namespaces/new',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsOrganizationsIndexRoute =
  AuthenticatedSettingsOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsOrganizationsNewRoute =
  AuthenticatedSettingsOrganizationsNewRouteImport.update({
    id: '/organizations/new',
    path: '/organizations/new',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedNamespacesNamespaceIdProjectsIndexRoute =
  AuthenticatedNamespacesNamespaceIdProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedNamespacesNamespaceIdProjectsRoute,
  } as any)
const AuthenticatedNamespacesNamespaceIdProjectsProjectIdRoute =
  AuthenticatedNamespacesNamespaceIdProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedNamespacesNamespaceIdProjectsRoute,
  } as any)
const AuthenticatedSettingsOrganizationsOrganizationIdIndexRoute =
  AuthenticatedSettingsOrganizationsOrganizationIdIndexRouteImport.update({
    id: '/organizations/$organizationId/',
    path: '/organizations/$organizationId/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsOrganizationsOrganizationIdEditRoute =
  AuthenticatedSettingsOrganizationsOrganizationIdEditRouteImport.update({
    id: '/organizations/$organizationId/edit',
    path: '/organizations/$organizationId/edit',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedNamespacesNamespaceIdProjectsProjectIdIndexRoute =
  AuthenticatedNamespacesNamespaceIdProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AuthenticatedNamespacesNamespaceIdProjectsProjectIdRoute,
  } as any)
const AuthenticatedNamespacesNamespaceIdProjectsProjectIdActivityRoute =
  AuthenticatedNamespacesNamespaceIdProjectsProjectIdActivityRouteImport.update(
    {
      id: '/activity',
      path: '/activity',
      getParentRoute: () =>
        AuthenticatedNamespacesNamespaceIdProjectsProjectIdRoute,
    } as any,
  )
const AuthenticatedNamespacesNamespaceIdProjectsProjectIdDocumentsRoute =
  AuthenticatedNamespacesNamespaceIdProjectsProjectIdDocumentsRouteImport.update(
    {
      id: '/documents',
      path: '/documents',
      getParentRoute: () =>
        AuthenticatedNamespacesNamespaceIdProjectsProjectIdRoute,
    } as any,
  )
const AuthenticatedNamespacesNamespaceIdProjectsProjectIdWorkRoute =
  AuthenticatedNamespacesNamespaceIdProjectsProjectIdWorkRouteImport.update({
    id: '/work',
    path: '/work',
    getParentRoute: () =>
      AuthenticatedNamespacesNamespaceIdProjectsProjectIdRoute,
  } as any)
const AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNewRoute =
  AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNewRouteImport.update(
    {
      id: '/organizations/$organizationId/namespaces/new',
      path: '/organizations/$organizationId/namespaces/new',
      getParentRoute: () => AuthenticatedSettingsRoute,
    } as any,
  )
const AuthenticatedSettingsOrganizationsOrganizationIdRolesNewRoute =
  AuthenticatedSettingsOrganizationsOrganizationIdRolesNewRouteImport.update({
    id: '/organizations/$organizationId/roles/new',
    path: '/organizations/$organizationId/roles/new',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdIndexRoute =
  AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdIndexRouteImport.update(
    {
      id: '/organizations/$organizationId/namespaces/$namespaceId/',
      path: '/organizations/$organizationId/namespaces/$namespaceId/',
      getParentRoute: () => AuthenticatedSettingsRoute,
    } as any,
  )
const AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdEditRoute =
  AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdEditRouteImport.update(
    {
      id: '/organizations/$organizationId/namespaces/$namespaceId/edit',
      path: '/organizations/$organizationId/namespaces/$namespaceId/edit',
      getParentRoute: () => AuthenticatedSettingsRoute,
    } as any,
  )
const AuthenticatedSettingsOrganizationsOrganizationIdRolesRoleIdEditRoute =
  AuthenticatedSettingsOrganizationsOrganizationIdRolesRoleIdEditRouteImport.update(
    {
      id: '/organizations/$organizationId/roles/$roleId/edit',
      path: '/organizations/$organizationId/roles/$roleId/edit',
      getParentRoute: () => AuthenticatedSettingsRoute,
    } as any,
  )
const AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdProjectsNewRoute =
  AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdProjectsNewRouteImport.update(
    {
      id: '/organizations/$organizationId/namespaces/$namespaceId/projects/new',
      path: '/organizations/$organizationId/namespaces/$namespaceId/projects/new',
      getParentRoute: () => AuthenticatedSettingsRoute,
    } as any,
  )
const AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdProjectsProjectIdIndexRoute =
  AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdProjectsProjectIdIndexRouteImport.update(
    {
      id: '/organizations/$organizationId/namespaces/$namespaceId/projects/$projectId/',
      path: '/organizations/$organizationId/namespaces/$namespaceId/projects/$projectId/',
      getParentRoute: () => AuthenticatedSettingsRoute,
    } as any,
  )
const AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdProjectsProjectIdEditRoute =
  AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdProjectsProjectIdEditRouteImport.update(
    {
      id: '/organizations/$organizationId/namespaces/$namespaceId/projects/$projectId/edit',
      path: '/organizations/$organizationId/namespaces/$namespaceId/projects/$projectId/edit',
      getParentRoute: () => AuthenticatedSettingsRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/my-work': typeof AuthenticatedMyWorkRoute
  '/namespaces': typeof AuthenticatedNamespacesRouteWithChildren
  '/organizations': typeof AuthenticatedOrganizationsRouteWithChildren
  '/permission-denied': typeof AuthenticatedPermissionDeniedRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/organizations/join': typeof OrganizationsJoinRoute
  '/documents/$documentId': typeof AuthenticatedDocumentsDocumentIdRoute
  '/namespaces/$namespaceId': typeof AuthenticatedNamespacesNamespaceIdRouteWithChildren
  '/organizations/$organizationId': typeof AuthenticatedOrganizationsOrganizationIdRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/work/$workId': typeof AuthenticatedWorkWorkIdRoute
  '/namespaces/': typeof AuthenticatedNamespacesIndexRoute
  '/organizations/': typeof AuthenticatedOrganizationsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/namespaces/$namespaceId/administration': typeof AuthenticatedNamespacesNamespaceIdAdministrationRoute
  '/namespaces/$namespaceId/documents': typeof AuthenticatedNamespacesNamespaceIdDocumentsRoute
  '/namespaces/$namespaceId/projects': typeof AuthenticatedNamespacesNamespaceIdProjectsRouteWithChildren
  '/namespaces/$namespaceId/work': typeof AuthenticatedNamespacesNamespaceIdWorkRoute
  '/relations/$entityType/$entityId': typeof AuthenticatedRelationsEntityTypeEntityIdRoute
  '/settings/namespaces/new': typeof AuthenticatedSettingsNamespacesNewRoute
  '/settings/organizations/new': typeof AuthenticatedSettingsOrganizationsNewRoute
  '/namespaces/$namespaceId/': typeof AuthenticatedNamespacesNamespaceIdIndexRoute
  '/settings/namespaces/': typeof AuthenticatedSettingsNamespacesIndexRoute
  '/settings/organizations/': typeof AuthenticatedSettingsOrganizationsIndexRoute
  '/namespaces/$namespaceId/projects/$projectId': typeof AuthenticatedNamespacesNamespaceIdProjectsProjectIdRouteWithChildren
  '/settings/organizations/$organizationId/edit': typeof AuthenticatedSettingsOrganizationsOrganizationIdEditRoute
  '/namespaces/$namespaceId/projects/': typeof AuthenticatedNamespacesNamespaceIdProjectsIndexRoute
  '/settings/organizations/$organizationId/': typeof AuthenticatedSettingsOrganizationsOrganizationIdIndexRoute
  '/namespaces/$namespaceId/projects/$projectId/activity': typeof AuthenticatedNamespacesNamespaceIdProjectsProjectIdActivityRoute
  '/namespaces/$namespaceId/projects/$projectId/documents': typeof AuthenticatedNamespacesNamespaceIdProjectsProjectIdDocumentsRoute
  '/namespaces/$namespaceId/projects/$projectId/work': typeof AuthenticatedNamespacesNamespaceIdProjectsProjectIdWorkRoute
  '/settings/organizations/$organizationId/namespaces/new': typeof AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNewRoute
  '/settings/organizations/$organizationId/roles/new': typeof AuthenticatedSettingsOrganizationsOrganizationIdRolesNewRoute
  '/namespaces/$namespaceId/projects/$projectId/': typeof AuthenticatedNamespacesNamespaceIdProjectsProjectIdIndexRoute
  '/settings/organizations/$organizationId/namespaces/$namespaceId/edit': typeof AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdEditRoute
  '/settings/organizations/$organizationId/roles/$roleId/edit': typeof AuthenticatedSettingsOrganizationsOrganizationIdRolesRoleIdEditRoute
  '/settings/organizations/$organizationId/namespaces/$namespaceId/': typeof AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdIndexRoute
  '/settings/organizations/$organizationId/namespaces/$namespaceId/projects/new': typeof AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdProjectsNewRoute
  '/settings/organizations/$organizationId/namespaces/$namespaceId/projects/$projectId/edit': typeof AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdProjectsProjectIdEditRoute
  '/settings/organizations/$organizationId/namespaces/$namespaceId/projects/$projectId/': typeof AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/my-work': typeof AuthenticatedMyWorkRoute
  '/permission-denied': typeof AuthenticatedPermissionDeniedRoute
  '/search': typeof AuthenticatedSearchRoute
  '/organizations/join': typeof OrganizationsJoinRoute
  '/': typeof AuthenticatedIndexRoute
  '/documents/$documentId': typeof AuthenticatedDocumentsDocumentIdRoute
  '/organizations/$organizationId': typeof AuthenticatedOrganizationsOrganizationIdRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/work/$workId': typeof AuthenticatedWorkWorkIdRoute
  '/namespaces': typeof AuthenticatedNamespacesIndexRoute
  '/organizations': typeof AuthenticatedOrganizationsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/namespaces/$namespaceId/administration': typeof AuthenticatedNamespacesNamespaceIdAdministrationRoute
  '/namespaces/$namespaceId/documents': typeof AuthenticatedNamespacesNamespaceIdDocumentsRoute
  '/namespaces/$namespaceId/work': typeof AuthenticatedNamespacesNamespaceIdWorkRoute
  '/relations/$entityType/$entityId': typeof AuthenticatedRelationsEntityTypeEntityIdRoute
  '/settings/namespaces/new': typeof AuthenticatedSettingsNamespacesNewRoute
  '/settings/organizations/new': typeof AuthenticatedSettingsOrganizationsNewRoute
  '/namespaces/$namespaceId': typeof AuthenticatedNamespacesNamespaceIdIndexRoute
  '/settings/namespaces': typeof AuthenticatedSettingsNamespacesIndexRoute
  '/settings/organizations': typeof AuthenticatedSettingsOrganizationsIndexRoute
  '/settings/organizations/$organizationId/edit': typeof AuthenticatedSettingsOrganizationsOrganizationIdEditRoute
  '/namespaces/$namespaceId/projects': typeof AuthenticatedNamespacesNamespaceIdProjectsIndexRoute
  '/settings/organizations/$organizationId': typeof AuthenticatedSettingsOrganizationsOrganizationIdIndexRoute
  '/namespaces/$namespaceId/projects/$projectId/activity': typeof AuthenticatedNamespacesNamespaceIdProjectsProjectIdActivityRoute
  '/namespaces/$namespaceId/projects/$projectId/documents': typeof AuthenticatedNamespacesNamespaceIdProjectsProjectIdDocumentsRoute
  '/namespaces/$namespaceId/projects/$projectId/work': typeof AuthenticatedNamespacesNamespaceIdProjectsProjectIdWorkRoute
  '/settings/organizations/$organizationId/namespaces/new': typeof AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNewRoute
  '/settings/organizations/$organizationId/roles/new': typeof AuthenticatedSettingsOrganizationsOrganizationIdRolesNewRoute
  '/namespaces/$namespaceId/projects/$projectId': typeof AuthenticatedNamespacesNamespaceIdProjectsProjectIdIndexRoute
  '/settings/organizations/$organizationId/namespaces/$namespaceId/edit': typeof AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdEditRoute
  '/settings/organizations/$organizationId/roles/$roleId/edit': typeof AuthenticatedSettingsOrganizationsOrganizationIdRolesRoleIdEditRoute
  '/settings/organizations/$organizationId/namespaces/$namespaceId': typeof AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdIndexRoute
  '/settings/organizations/$organizationId/namespaces/$namespaceId/projects/new': typeof AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdProjectsNewRoute
  '/settings/organizations/$organizationId/namespaces/$namespaceId/projects/$projectId/edit': typeof AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdProjectsProjectIdEditRoute
  '/settings/organizations/$organizationId/namespaces/$namespaceId/projects/$projectId': typeof AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/my-work': typeof AuthenticatedMyWorkRoute
  '/_authenticated/namespaces': typeof AuthenticatedNamespacesRouteWithChildren
  '/_authenticated/organizations': typeof AuthenticatedOrganizationsRouteWithChildren
  '/_authenticated/permission-denied': typeof AuthenticatedPermissionDeniedRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/organizations/join': typeof OrganizationsJoinRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/documents/$documentId': typeof AuthenticatedDocumentsDocumentIdRoute
  '/_authenticated/namespaces/$namespaceId': typeof AuthenticatedNamespacesNamespaceIdRouteWithChildren
  '/_authenticated/organizations/$organizationId': typeof AuthenticatedOrganizationsOrganizationIdRoute
  '/_authenticated/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/_authenticated/work/$workId': typeof AuthenticatedWorkWorkIdRoute
  '/_authenticated/namespaces/': typeof AuthenticatedNamespacesIndexRoute
  '/_authenticated/organizations/': typeof AuthenticatedOrganizationsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/namespaces/$namespaceId/administration': typeof AuthenticatedNamespacesNamespaceIdAdministrationRoute
  '/_authenticated/namespaces/$namespaceId/documents': typeof AuthenticatedNamespacesNamespaceIdDocumentsRoute
  '/_authenticated/namespaces/$namespaceId/projects': typeof AuthenticatedNamespacesNamespaceIdProjectsRouteWithChildren
  '/_authenticated/namespaces/$namespaceId/work': typeof AuthenticatedNamespacesNamespaceIdWorkRoute
  '/_authenticated/relations/$entityType/$entityId': typeof AuthenticatedRelationsEntityTypeEntityIdRoute
  '/_authenticated/settings/namespaces/new': typeof AuthenticatedSettingsNamespacesNewRoute
  '/_authenticated/settings/organizations/new': typeof AuthenticatedSettingsOrganizationsNewRoute
  '/_authenticated/namespaces/$namespaceId/': typeof AuthenticatedNamespacesNamespaceIdIndexRoute
  '/_authenticated/settings/namespaces/': typeof AuthenticatedSettingsNamespacesIndexRoute
  '/_authenticated/settings/organizations/': typeof AuthenticatedSettingsOrganizationsIndexRoute
  '/_authenticated/namespaces/$namespaceId/projects/$projectId': typeof AuthenticatedNamespacesNamespaceIdProjectsProjectIdRouteWithChildren
  '/_authenticated/settings/organizations/$organizationId/edit': typeof AuthenticatedSettingsOrganizationsOrganizationIdEditRoute
  '/_authenticated/namespaces/$namespaceId/projects/': typeof AuthenticatedNamespacesNamespaceIdProjectsIndexRoute
  '/_authenticated/settings/organizations/$organizationId/': typeof AuthenticatedSettingsOrganizationsOrganizationIdIndexRoute
  '/_authenticated/namespaces/$namespaceId/projects/$projectId/activity': typeof AuthenticatedNamespacesNamespaceIdProjectsProjectIdActivityRoute
  '/_authenticated/namespaces/$namespaceId/projects/$projectId/documents': typeof AuthenticatedNamespacesNamespaceIdProjectsProjectIdDocumentsRoute
  '/_authenticated/namespaces/$namespaceId/projects/$projectId/work': typeof AuthenticatedNamespacesNamespaceIdProjectsProjectIdWorkRoute
  '/_authenticated/settings/organizations/$organizationId/namespaces/new': typeof AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNewRoute
  '/_authenticated/settings/organizations/$organizationId/roles/new': typeof AuthenticatedSettingsOrganizationsOrganizationIdRolesNewRoute
  '/_authenticated/namespaces/$namespaceId/projects/$projectId/': typeof AuthenticatedNamespacesNamespaceIdProjectsProjectIdIndexRoute
  '/_authenticated/settings/organizations/$organizationId/namespaces/$namespaceId/edit': typeof AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdEditRoute
  '/_authenticated/settings/organizations/$organizationId/roles/$roleId/edit': typeof AuthenticatedSettingsOrganizationsOrganizationIdRolesRoleIdEditRoute
  '/_authenticated/settings/organizations/$organizationId/namespaces/$namespaceId/': typeof AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdIndexRoute
  '/_authenticated/settings/organizations/$organizationId/namespaces/$namespaceId/projects/new': typeof AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdProjectsNewRoute
  '/_authenticated/settings/organizations/$organizationId/namespaces/$namespaceId/projects/$projectId/edit': typeof AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdProjectsProjectIdEditRoute
  '/_authenticated/settings/organizations/$organizationId/namespaces/$namespaceId/projects/$projectId/': typeof AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/dashboard'
    | '/inbox'
    | '/my-work'
    | '/namespaces'
    | '/organizations'
    | '/permission-denied'
    | '/search'
    | '/settings'
    | '/organizations/join'
    | '/documents/$documentId'
    | '/namespaces/$namespaceId'
    | '/organizations/$organizationId'
    | '/settings/security'
    | '/work/$workId'
    | '/namespaces/'
    | '/organizations/'
    | '/settings/'
    | '/namespaces/$namespaceId/administration'
    | '/namespaces/$namespaceId/documents'
    | '/namespaces/$namespaceId/projects'
    | '/namespaces/$namespaceId/work'
    | '/relations/$entityType/$entityId'
    | '/settings/namespaces/new'
    | '/settings/organizations/new'
    | '/namespaces/$namespaceId/'
    | '/settings/namespaces/'
    | '/settings/organizations/'
    | '/namespaces/$namespaceId/projects/$projectId'
    | '/settings/organizations/$organizationId/edit'
    | '/namespaces/$namespaceId/projects/'
    | '/settings/organizations/$organizationId/'
    | '/namespaces/$namespaceId/projects/$projectId/activity'
    | '/namespaces/$namespaceId/projects/$projectId/documents'
    | '/namespaces/$namespaceId/projects/$projectId/work'
    | '/settings/organizations/$organizationId/namespaces/new'
    | '/settings/organizations/$organizationId/roles/new'
    | '/namespaces/$namespaceId/projects/$projectId/'
    | '/settings/organizations/$organizationId/namespaces/$namespaceId/edit'
    | '/settings/organizations/$organizationId/roles/$roleId/edit'
    | '/settings/organizations/$organizationId/namespaces/$namespaceId/'
    | '/settings/organizations/$organizationId/namespaces/$namespaceId/projects/new'
    | '/settings/organizations/$organizationId/namespaces/$namespaceId/projects/$projectId/edit'
    | '/settings/organizations/$organizationId/namespaces/$namespaceId/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/dashboard'
    | '/inbox'
    | '/my-work'
    | '/permission-denied'
    | '/search'
    | '/organizations/join'
    | '/'
    | '/documents/$documentId'
    | '/organizations/$organizationId'
    | '/settings/security'
    | '/work/$workId'
    | '/namespaces'
    | '/organizations'
    | '/settings'
    | '/namespaces/$namespaceId/administration'
    | '/namespaces/$namespaceId/documents'
    | '/namespaces/$namespaceId/work'
    | '/relations/$entityType/$entityId'
    | '/settings/namespaces/new'
    | '/settings/organizations/new'
    | '/namespaces/$namespaceId'
    | '/settings/namespaces'
    | '/settings/organizations'
    | '/settings/organizations/$organizationId/edit'
    | '/namespaces/$namespaceId/projects'
    | '/settings/organizations/$organizationId'
    | '/namespaces/$namespaceId/projects/$projectId/activity'
    | '/namespaces/$namespaceId/projects/$projectId/documents'
    | '/namespaces/$namespaceId/projects/$projectId/work'
    | '/settings/organizations/$organizationId/namespaces/new'
    | '/settings/organizations/$organizationId/roles/new'
    | '/namespaces/$namespaceId/projects/$projectId'
    | '/settings/organizations/$organizationId/namespaces/$namespaceId/edit'
    | '/settings/organizations/$organizationId/roles/$roleId/edit'
    | '/settings/organizations/$organizationId/namespaces/$namespaceId'
    | '/settings/organizations/$organizationId/namespaces/$namespaceId/projects/new'
    | '/settings/organizations/$organizationId/namespaces/$namespaceId/projects/$projectId/edit'
    | '/settings/organizations/$organizationId/namespaces/$namespaceId/projects/$projectId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/inbox'
    | '/_authenticated/my-work'
    | '/_authenticated/namespaces'
    | '/_authenticated/organizations'
    | '/_authenticated/permission-denied'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/organizations/join'
    | '/_authenticated/'
    | '/_authenticated/documents/$documentId'
    | '/_authenticated/namespaces/$namespaceId'
    | '/_authenticated/organizations/$organizationId'
    | '/_authenticated/settings/security'
    | '/_authenticated/work/$workId'
    | '/_authenticated/namespaces/'
    | '/_authenticated/organizations/'
    | '/_authenticated/settings/'
    | '/_authenticated/namespaces/$namespaceId/administration'
    | '/_authenticated/namespaces/$namespaceId/documents'
    | '/_authenticated/namespaces/$namespaceId/projects'
    | '/_authenticated/namespaces/$namespaceId/work'
    | '/_authenticated/relations/$entityType/$entityId'
    | '/_authenticated/settings/namespaces/new'
    | '/_authenticated/settings/organizations/new'
    | '/_authenticated/namespaces/$namespaceId/'
    | '/_authenticated/settings/namespaces/'
    | '/_authenticated/settings/organizations/'
    | '/_authenticated/namespaces/$namespaceId/projects/$projectId'
    | '/_authenticated/settings/organizations/$organizationId/edit'
    | '/_authenticated/namespaces/$namespaceId/projects/'
    | '/_authenticated/settings/organizations/$organizationId/'
    | '/_authenticated/namespaces/$namespaceId/projects/$projectId/activity'
    | '/_authenticated/namespaces/$namespaceId/projects/$projectId/documents'
    | '/_authenticated/namespaces/$namespaceId/projects/$projectId/work'
    | '/_authenticated/settings/organizations/$organizationId/namespaces/new'
    | '/_authenticated/settings/organizations/$organizationId/roles/new'
    | '/_authenticated/namespaces/$namespaceId/projects/$projectId/'
    | '/_authenticated/settings/organizations/$organizationId/namespaces/$namespaceId/edit'
    | '/_authenticated/settings/organizations/$organizationId/roles/$roleId/edit'
    | '/_authenticated/settings/organizations/$organizationId/namespaces/$namespaceId/'
    | '/_authenticated/settings/organizations/$organizationId/namespaces/$namespaceId/projects/new'
    | '/_authenticated/settings/organizations/$organizationId/namespaces/$namespaceId/projects/$projectId/edit'
    | '/_authenticated/settings/organizations/$organizationId/namespaces/$namespaceId/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  OrganizationsJoinRoute: typeof OrganizationsJoinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-work': {
      id: '/_authenticated/my-work'
      path: '/my-work'
      fullPath: '/my-work'
      preLoaderRoute: typeof AuthenticatedMyWorkRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/namespaces': {
      id: '/_authenticated/namespaces'
      path: '/namespaces'
      fullPath: '/namespaces'
      preLoaderRoute: typeof AuthenticatedNamespacesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/organizations': {
      id: '/_authenticated/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AuthenticatedOrganizationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/permission-denied': {
      id: '/_authenticated/permission-denied'
      path: '/permission-denied'
      fullPath: '/permission-denied'
      preLoaderRoute: typeof AuthenticatedPermissionDeniedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/organizations/join': {
      id: '/organizations/join'
      path: '/organizations/join'
      fullPath: '/organizations/join'
      preLoaderRoute: typeof OrganizationsJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/documents/$documentId': {
      id: '/_authenticated/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof AuthenticatedDocumentsDocumentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/namespaces/': {
      id: '/_authenticated/namespaces/'
      path: '/'
      fullPath: '/namespaces/'
      preLoaderRoute: typeof AuthenticatedNamespacesIndexRouteImport
      parentRoute: typeof AuthenticatedNamespacesRoute
    }
    '/_authenticated/namespaces/$namespaceId': {
      id: '/_authenticated/namespaces/$namespaceId'
      path: '/$namespaceId'
      fullPath: '/namespaces/$namespaceId'
      preLoaderRoute: typeof AuthenticatedNamespacesNamespaceIdRouteImport
      parentRoute: typeof AuthenticatedNamespacesRoute
    }
    '/_authenticated/organizations/': {
      id: '/_authenticated/organizations/'
      path: '/'
      fullPath: '/organizations/'
      preLoaderRoute: typeof AuthenticatedOrganizationsIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizationsRoute
    }
    '/_authenticated/organizations/$organizationId': {
      id: '/_authenticated/organizations/$organizationId'
      path: '/$organizationId'
      fullPath: '/organizations/$organizationId'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrganizationIdRouteImport
      parentRoute: typeof AuthenticatedOrganizationsRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/security': {
      id: '/_authenticated/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/work/$workId': {
      id: '/_authenticated/work/$workId'
      path: '/work/$workId'
      fullPath: '/work/$workId'
      preLoaderRoute: typeof AuthenticatedWorkWorkIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/namespaces/$namespaceId/': {
      id: '/_authenticated/namespaces/$namespaceId/'
      path: '/'
      fullPath: '/namespaces/$namespaceId/'
      preLoaderRoute: typeof AuthenticatedNamespacesNamespaceIdIndexRouteImport
      parentRoute: typeof AuthenticatedNamespacesNamespaceIdRoute
    }
    '/_authenticated/namespaces/$namespaceId/administration': {
      id: '/_authenticated/namespaces/$namespaceId/administration'
      path: '/administration'
      fullPath: '/namespaces/$namespaceId/administration'
      preLoaderRoute: typeof AuthenticatedNamespacesNamespaceIdAdministrationRouteImport
      parentRoute: typeof AuthenticatedNamespacesNamespaceIdRoute
    }
    '/_authenticated/namespaces/$namespaceId/documents': {
      id: '/_authenticated/namespaces/$namespaceId/documents'
      path: '/documents'
      fullPath: '/namespaces/$namespaceId/documents'
      preLoaderRoute: typeof AuthenticatedNamespacesNamespaceIdDocumentsRouteImport
      parentRoute: typeof AuthenticatedNamespacesNamespaceIdRoute
    }
    '/_authenticated/namespaces/$namespaceId/projects': {
      id: '/_authenticated/namespaces/$namespaceId/projects'
      path: '/projects'
      fullPath: '/namespaces/$namespaceId/projects'
      preLoaderRoute: typeof AuthenticatedNamespacesNamespaceIdProjectsRouteImport
      parentRoute: typeof AuthenticatedNamespacesNamespaceIdRoute
    }
    '/_authenticated/namespaces/$namespaceId/work': {
      id: '/_authenticated/namespaces/$namespaceId/work'
      path: '/work'
      fullPath: '/namespaces/$namespaceId/work'
      preLoaderRoute: typeof AuthenticatedNamespacesNamespaceIdWorkRouteImport
      parentRoute: typeof AuthenticatedNamespacesNamespaceIdRoute
    }
    '/_authenticated/relations/$entityType/$entityId': {
      id: '/_authenticated/relations/$entityType/$entityId'
      path: '/relations/$entityType/$entityId'
      fullPath: '/relations/$entityType/$entityId'
      preLoaderRoute: typeof AuthenticatedRelationsEntityTypeEntityIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/namespaces/': {
      id: '/_authenticated/settings/namespaces/'
      path: '/namespaces'
      fullPath: '/settings/namespaces/'
      preLoaderRoute: typeof AuthenticatedSettingsNamespacesIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/namespaces/new': {
      id: '/_authenticated/settings/namespaces/new'
      path: '/namespaces/new'
      fullPath: '/settings/namespaces/new'
      preLoaderRoute: typeof AuthenticatedSettingsNamespacesNewRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/organizations/': {
      id: '/_authenticated/settings/organizations/'
      path: '/organizations'
      fullPath: '/settings/organizations/'
      preLoaderRoute: typeof AuthenticatedSettingsOrganizationsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/organizations/new': {
      id: '/_authenticated/settings/organizations/new'
      path: '/organizations/new'
      fullPath: '/settings/organizations/new'
      preLoaderRoute: typeof AuthenticatedSettingsOrganizationsNewRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/namespaces/$namespaceId/projects/': {
      id: '/_authenticated/namespaces/$namespaceId/projects/'
      path: '/'
      fullPath: '/namespaces/$namespaceId/projects/'
      preLoaderRoute: typeof AuthenticatedNamespacesNamespaceIdProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedNamespacesNamespaceIdProjectsRoute
    }
    '/_authenticated/namespaces/$namespaceId/projects/$projectId': {
      id: '/_authenticated/namespaces/$namespaceId/projects/$projectId'
      path: '/$projectId'
      fullPath: '/namespaces/$namespaceId/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedNamespacesNamespaceIdProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedNamespacesNamespaceIdProjectsRoute
    }
    '/_authenticated/settings/organizations/$organizationId/': {
      id: '/_authenticated/settings/organizations/$organizationId/'
      path: '/organizations/$organizationId'
      fullPath: '/settings/organizations/$organizationId/'
      preLoaderRoute: typeof AuthenticatedSettingsOrganizationsOrganizationIdIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/organizations/$organizationId/edit': {
      id: '/_authenticated/settings/organizations/$organizationId/edit'
      path: '/organizations/$organizationId/edit'
      fullPath: '/settings/organizations/$organizationId/edit'
      preLoaderRoute: typeof AuthenticatedSettingsOrganizationsOrganizationIdEditRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/namespaces/$namespaceId/projects/$projectId/': {
      id: '/_authenticated/namespaces/$namespaceId/projects/$projectId/'
      path: '/'
      fullPath: '/namespaces/$namespaceId/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedNamespacesNamespaceIdProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedNamespacesNamespaceIdProjectsProjectIdRoute
    }
    '/_authenticated/namespaces/$namespaceId/projects/$projectId/activity': {
      id: '/_authenticated/namespaces/$namespaceId/projects/$projectId/activity'
      path: '/activity'
      fullPath: '/namespaces/$namespaceId/projects/$projectId/activity'
      preLoaderRoute: typeof AuthenticatedNamespacesNamespaceIdProjectsProjectIdActivityRouteImport
      parentRoute: typeof AuthenticatedNamespacesNamespaceIdProjectsProjectIdRoute
    }
    '/_authenticated/namespaces/$namespaceId/projects/$projectId/documents': {
      id: '/_authenticated/namespaces/$namespaceId/projects/$projectId/documents'
      path: '/documents'
      fullPath: '/namespaces/$namespaceId/projects/$projectId/documents'
      preLoaderRoute: typeof AuthenticatedNamespacesNamespaceIdProjectsProjectIdDocumentsRouteImport
      parentRoute: typeof AuthenticatedNamespacesNamespaceIdProjectsProjectIdRoute
    }
    '/_authenticated/namespaces/$namespaceId/projects/$projectId/work': {
      id: '/_authenticated/namespaces/$namespaceId/projects/$projectId/work'
      path: '/work'
      fullPath: '/namespaces/$namespaceId/projects/$projectId/work'
      preLoaderRoute: typeof AuthenticatedNamespacesNamespaceIdProjectsProjectIdWorkRouteImport
      parentRoute: typeof AuthenticatedNamespacesNamespaceIdProjectsProjectIdRoute
    }
    '/_authenticated/settings/organizations/$organizationId/namespaces/new': {
      id: '/_authenticated/settings/organizations/$organizationId/namespaces/new'
      path: '/organizations/$organizationId/namespaces/new'
      fullPath: '/settings/organizations/$organizationId/namespaces/new'
      preLoaderRoute: typeof AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNewRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/organizations/$organizationId/roles/new': {
      id: '/_authenticated/settings/organizations/$organizationId/roles/new'
      path: '/organizations/$organizationId/roles/new'
      fullPath: '/settings/organizations/$organizationId/roles/new'
      preLoaderRoute: typeof AuthenticatedSettingsOrganizationsOrganizationIdRolesNewRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/organizations/$organizationId/namespaces/$namespaceId/': {
      id: '/_authenticated/settings/organizations/$organizationId/namespaces/$namespaceId/'
      path: '/organizations/$organizationId/namespaces/$namespaceId'
      fullPath: '/settings/organizations/$organizationId/namespaces/$namespaceId/'
      preLoaderRoute: typeof AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/organizations/$organizationId/namespaces/$namespaceId/edit': {
      id: '/_authenticated/settings/organizations/$organizationId/namespaces/$namespaceId/edit'
      path: '/organizations/$organizationId/namespaces/$namespaceId/edit'
      fullPath: '/settings/organizations/$organizationId/namespaces/$namespaceId/edit'
      preLoaderRoute: typeof AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdEditRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/organizations/$organizationId/roles/$roleId/edit': {
      id: '/_authenticated/settings/organizations/$organizationId/roles/$roleId/edit'
      path: '/organizations/$organizationId/roles/$roleId/edit'
      fullPath: '/settings/organizations/$organizationId/roles/$roleId/edit'
      preLoaderRoute: typeof AuthenticatedSettingsOrganizationsOrganizationIdRolesRoleIdEditRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/organizations/$organizationId/namespaces/$namespaceId/projects/new': {
      id: '/_authenticated/settings/organizations/$organizationId/namespaces/$namespaceId/projects/new'
      path: '/organizations/$organizationId/namespaces/$namespaceId/projects/new'
      fullPath: '/settings/organizations/$organizationId/namespaces/$namespaceId/projects/new'
      preLoaderRoute: typeof AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdProjectsNewRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/organizations/$organizationId/namespaces/$namespaceId/projects/$projectId/': {
      id: '/_authenticated/settings/organizations/$organizationId/namespaces/$namespaceId/projects/$projectId/'
      path: '/organizations/$organizationId/namespaces/$namespaceId/projects/$projectId'
      fullPath: '/settings/organizations/$organizationId/namespaces/$namespaceId/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/organizations/$organizationId/namespaces/$namespaceId/projects/$projectId/edit': {
      id: '/_authenticated/settings/organizations/$organizationId/namespaces/$namespaceId/projects/$projectId/edit'
      path: '/organizations/$organizationId/namespaces/$namespaceId/projects/$projectId/edit'
      fullPath: '/settings/organizations/$organizationId/namespaces/$namespaceId/projects/$projectId/edit'
      preLoaderRoute: typeof AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdProjectsProjectIdEditRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
  }
}

interface AuthenticatedNamespacesNamespaceIdProjectsProjectIdRouteChildren {
  AuthenticatedNamespacesNamespaceIdProjectsProjectIdActivityRoute: typeof AuthenticatedNamespacesNamespaceIdProjectsProjectIdActivityRoute
  AuthenticatedNamespacesNamespaceIdProjectsProjectIdDocumentsRoute: typeof AuthenticatedNamespacesNamespaceIdProjectsProjectIdDocumentsRoute
  AuthenticatedNamespacesNamespaceIdProjectsProjectIdWorkRoute: typeof AuthenticatedNamespacesNamespaceIdProjectsProjectIdWorkRoute
  AuthenticatedNamespacesNamespaceIdProjectsProjectIdIndexRoute: typeof AuthenticatedNamespacesNamespaceIdProjectsProjectIdIndexRoute
}

const AuthenticatedNamespacesNamespaceIdProjectsProjectIdRouteChildren: AuthenticatedNamespacesNamespaceIdProjectsProjectIdRouteChildren =
  {
    AuthenticatedNamespacesNamespaceIdProjectsProjectIdActivityRoute:
      AuthenticatedNamespacesNamespaceIdProjectsProjectIdActivityRoute,
    AuthenticatedNamespacesNamespaceIdProjectsProjectIdDocumentsRoute:
      AuthenticatedNamespacesNamespaceIdProjectsProjectIdDocumentsRoute,
    AuthenticatedNamespacesNamespaceIdProjectsProjectIdWorkRoute:
      AuthenticatedNamespacesNamespaceIdProjectsProjectIdWorkRoute,
    AuthenticatedNamespacesNamespaceIdProjectsProjectIdIndexRoute:
      AuthenticatedNamespacesNamespaceIdProjectsProjectIdIndexRoute,
  }

const AuthenticatedNamespacesNamespaceIdProjectsProjectIdRouteWithChildren =
  AuthenticatedNamespacesNamespaceIdProjectsProjectIdRoute._addFileChildren(
    AuthenticatedNamespacesNamespaceIdProjectsProjectIdRouteChildren,
  )

interface AuthenticatedNamespacesNamespaceIdProjectsRouteChildren {
  AuthenticatedNamespacesNamespaceIdProjectsProjectIdRoute: typeof AuthenticatedNamespacesNamespaceIdProjectsProjectIdRouteWithChildren
  AuthenticatedNamespacesNamespaceIdProjectsIndexRoute: typeof AuthenticatedNamespacesNamespaceIdProjectsIndexRoute
}

const AuthenticatedNamespacesNamespaceIdProjectsRouteChildren: AuthenticatedNamespacesNamespaceIdProjectsRouteChildren =
  {
    AuthenticatedNamespacesNamespaceIdProjectsProjectIdRoute:
      AuthenticatedNamespacesNamespaceIdProjectsProjectIdRouteWithChildren,
    AuthenticatedNamespacesNamespaceIdProjectsIndexRoute:
      AuthenticatedNamespacesNamespaceIdProjectsIndexRoute,
  }

const AuthenticatedNamespacesNamespaceIdProjectsRouteWithChildren =
  AuthenticatedNamespacesNamespaceIdProjectsRoute._addFileChildren(
    AuthenticatedNamespacesNamespaceIdProjectsRouteChildren,
  )

interface AuthenticatedNamespacesNamespaceIdRouteChildren {
  AuthenticatedNamespacesNamespaceIdAdministrationRoute: typeof AuthenticatedNamespacesNamespaceIdAdministrationRoute
  AuthenticatedNamespacesNamespaceIdDocumentsRoute: typeof AuthenticatedNamespacesNamespaceIdDocumentsRoute
  AuthenticatedNamespacesNamespaceIdProjectsRoute: typeof AuthenticatedNamespacesNamespaceIdProjectsRouteWithChildren
  AuthenticatedNamespacesNamespaceIdWorkRoute: typeof AuthenticatedNamespacesNamespaceIdWorkRoute
  AuthenticatedNamespacesNamespaceIdIndexRoute: typeof AuthenticatedNamespacesNamespaceIdIndexRoute
}

const AuthenticatedNamespacesNamespaceIdRouteChildren: AuthenticatedNamespacesNamespaceIdRouteChildren =
  {
    AuthenticatedNamespacesNamespaceIdAdministrationRoute:
      AuthenticatedNamespacesNamespaceIdAdministrationRoute,
    AuthenticatedNamespacesNamespaceIdDocumentsRoute:
      AuthenticatedNamespacesNamespaceIdDocumentsRoute,
    AuthenticatedNamespacesNamespaceIdProjectsRoute:
      AuthenticatedNamespacesNamespaceIdProjectsRouteWithChildren,
    AuthenticatedNamespacesNamespaceIdWorkRoute:
      AuthenticatedNamespacesNamespaceIdWorkRoute,
    AuthenticatedNamespacesNamespaceIdIndexRoute:
      AuthenticatedNamespacesNamespaceIdIndexRoute,
  }

const AuthenticatedNamespacesNamespaceIdRouteWithChildren =
  AuthenticatedNamespacesNamespaceIdRoute._addFileChildren(
    AuthenticatedNamespacesNamespaceIdRouteChildren,
  )

interface AuthenticatedNamespacesRouteChildren {
  AuthenticatedNamespacesNamespaceIdRoute: typeof AuthenticatedNamespacesNamespaceIdRouteWithChildren
  AuthenticatedNamespacesIndexRoute: typeof AuthenticatedNamespacesIndexRoute
}

const AuthenticatedNamespacesRouteChildren: AuthenticatedNamespacesRouteChildren =
  {
    AuthenticatedNamespacesNamespaceIdRoute:
      AuthenticatedNamespacesNamespaceIdRouteWithChildren,
    AuthenticatedNamespacesIndexRoute: AuthenticatedNamespacesIndexRoute,
  }

const AuthenticatedNamespacesRouteWithChildren =
  AuthenticatedNamespacesRoute._addFileChildren(
    AuthenticatedNamespacesRouteChildren,
  )

interface AuthenticatedOrganizationsRouteChildren {
  AuthenticatedOrganizationsOrganizationIdRoute: typeof AuthenticatedOrganizationsOrganizationIdRoute
  AuthenticatedOrganizationsIndexRoute: typeof AuthenticatedOrganizationsIndexRoute
}

const AuthenticatedOrganizationsRouteChildren: AuthenticatedOrganizationsRouteChildren =
  {
    AuthenticatedOrganizationsOrganizationIdRoute:
      AuthenticatedOrganizationsOrganizationIdRoute,
    AuthenticatedOrganizationsIndexRoute: AuthenticatedOrganizationsIndexRoute,
  }

const AuthenticatedOrganizationsRouteWithChildren =
  AuthenticatedOrganizationsRoute._addFileChildren(
    AuthenticatedOrganizationsRouteChildren,
  )

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedSettingsNamespacesNewRoute: typeof AuthenticatedSettingsNamespacesNewRoute
  AuthenticatedSettingsOrganizationsNewRoute: typeof AuthenticatedSettingsOrganizationsNewRoute
  AuthenticatedSettingsNamespacesIndexRoute: typeof AuthenticatedSettingsNamespacesIndexRoute
  AuthenticatedSettingsOrganizationsIndexRoute: typeof AuthenticatedSettingsOrganizationsIndexRoute
  AuthenticatedSettingsOrganizationsOrganizationIdEditRoute: typeof AuthenticatedSettingsOrganizationsOrganizationIdEditRoute
  AuthenticatedSettingsOrganizationsOrganizationIdIndexRoute: typeof AuthenticatedSettingsOrganizationsOrganizationIdIndexRoute
  AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNewRoute: typeof AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNewRoute
  AuthenticatedSettingsOrganizationsOrganizationIdRolesNewRoute: typeof AuthenticatedSettingsOrganizationsOrganizationIdRolesNewRoute
  AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdEditRoute: typeof AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdEditRoute
  AuthenticatedSettingsOrganizationsOrganizationIdRolesRoleIdEditRoute: typeof AuthenticatedSettingsOrganizationsOrganizationIdRolesRoleIdEditRoute
  AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdIndexRoute: typeof AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdIndexRoute
  AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdProjectsNewRoute: typeof AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdProjectsNewRoute
  AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdProjectsProjectIdEditRoute: typeof AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdProjectsProjectIdEditRoute
  AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdProjectsProjectIdIndexRoute: typeof AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdProjectsProjectIdIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsSecurityRoute: AuthenticatedSettingsSecurityRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedSettingsNamespacesNewRoute:
    AuthenticatedSettingsNamespacesNewRoute,
  AuthenticatedSettingsOrganizationsNewRoute:
    AuthenticatedSettingsOrganizationsNewRoute,
  AuthenticatedSettingsNamespacesIndexRoute:
    AuthenticatedSettingsNamespacesIndexRoute,
  AuthenticatedSettingsOrganizationsIndexRoute:
    AuthenticatedSettingsOrganizationsIndexRoute,
  AuthenticatedSettingsOrganizationsOrganizationIdEditRoute:
    AuthenticatedSettingsOrganizationsOrganizationIdEditRoute,
  AuthenticatedSettingsOrganizationsOrganizationIdIndexRoute:
    AuthenticatedSettingsOrganizationsOrganizationIdIndexRoute,
  AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNewRoute:
    AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNewRoute,
  AuthenticatedSettingsOrganizationsOrganizationIdRolesNewRoute:
    AuthenticatedSettingsOrganizationsOrganizationIdRolesNewRoute,
  AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdEditRoute:
    AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdEditRoute,
  AuthenticatedSettingsOrganizationsOrganizationIdRolesRoleIdEditRoute:
    AuthenticatedSettingsOrganizationsOrganizationIdRolesRoleIdEditRoute,
  AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdIndexRoute:
    AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdIndexRoute,
  AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdProjectsNewRoute:
    AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdProjectsNewRoute,
  AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdProjectsProjectIdEditRoute:
    AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdProjectsProjectIdEditRoute,
  AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdProjectsProjectIdIndexRoute:
    AuthenticatedSettingsOrganizationsOrganizationIdNamespacesNamespaceIdProjectsProjectIdIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedMyWorkRoute: typeof AuthenticatedMyWorkRoute
  AuthenticatedNamespacesRoute: typeof AuthenticatedNamespacesRouteWithChildren
  AuthenticatedOrganizationsRoute: typeof AuthenticatedOrganizationsRouteWithChildren
  AuthenticatedPermissionDeniedRoute: typeof AuthenticatedPermissionDeniedRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDocumentsDocumentIdRoute: typeof AuthenticatedDocumentsDocumentIdRoute
  AuthenticatedWorkWorkIdRoute: typeof AuthenticatedWorkWorkIdRoute
  AuthenticatedRelationsEntityTypeEntityIdRoute: typeof AuthenticatedRelationsEntityTypeEntityIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedMyWorkRoute: AuthenticatedMyWorkRoute,
  AuthenticatedNamespacesRoute: AuthenticatedNamespacesRouteWithChildren,
  AuthenticatedOrganizationsRoute: AuthenticatedOrganizationsRouteWithChildren,
  AuthenticatedPermissionDeniedRoute: AuthenticatedPermissionDeniedRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDocumentsDocumentIdRoute: AuthenticatedDocumentsDocumentIdRoute,
  AuthenticatedWorkWorkIdRoute: AuthenticatedWorkWorkIdRoute,
  AuthenticatedRelationsEntityTypeEntityIdRoute:
    AuthenticatedRelationsEntityTypeEntityIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  OrganizationsJoinRoute: OrganizationsJoinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
