name: DCO

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: dco-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check DCO
    if: |
      !startsWith(github.head_ref, 'release-please--') &&
      github.actor != 'dependabot[bot]' &&
      github.actor != 'renovate[bot]' &&
      github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Check Signed-off-by
        uses: christophebedard/dco-check@ec8bfc43106afe98b323ace9133650df10497e12 # 0.5.1
        with:
          python-version: "3.12"
          args: --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
