name: Deploy Website to Vercel

on:
  push:
    branches:
      - main
    paths:
      - 'website/**'
      - '.github/workflows/deploy-website.yml'

jobs:
  check-website-changes:
    name: Check Website Changes
    runs-on: ubuntu-latest
    outputs:
      should-deploy: ${{ steps.check-changes.outputs.should-deploy }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Check if website directory has changes
        id: check-changes
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -q "^website/"; then
            echo "should-deploy=true" >> $GITHUB_OUTPUT
            echo "Website directory has changes, will deploy"
          else
            echo "should-deploy=false" >> $GITHUB_OUTPUT
            echo "No changes in website directory, skipping deployment"
          fi

  deploy-website:
    name: Deploy Website to Vercel
    runs-on: ubuntu-latest
    needs: check-website-changes
    if: needs.check-website-changes.outputs.should-deploy == 'true'
    environment:
      name: production
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: 'npm'
      
      - name: Install pnpm
        run: npm install -g pnpm
      
      - name: Install dependencies
        run: |
          cd website
          pnpm install --frozen-lockfile
      
      - name: Build Astro website
        run: |
          cd website
          pnpm run build
      
      - name: Deploy Website to Vercel
        id: deploy
        uses: amondnet/vercel-action@v25
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_WEBSITE_PROJECT_ID }}
          working-directory: ./website
          vercel-args: '--prod'