name: Deploy API Docs to Vercel

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
      - 'api/openapi/redocly.yaml'
      - '.github/workflows/deploy-api-docs.yml'

permissions:
  contents: read

jobs:
  deploy-docs:
    name: Deploy API Docs to Vercel
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: ./.github/actions/setup-mise

      - name: Install Vercel CLI
        run: |
          # renovate: datasource=npm depName=vercel
          npm install -g vercel@59.11.2

      - name: Deploy API Docs to Vercel
        id: deploy
        working-directory: ./api/openapi
        run: |
          vercel link --token ${{ secrets.VERCEL_TOKEN }} --scope ${{ secrets.VERCEL_ORG_ID }} --project ${{ secrets.VERCEL_DOCS_PROJECT_ID }} --yes
          vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --yes
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_DOCS_PROJECT_ID }}
