name: Deploy API Docs to Vercel

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
      - 'redocly.yaml'
      - '.github/workflows/deploy-api-docs.yml'

permissions:
  contents: read

jobs:
  deploy-docs:
    name: Deploy API Docs to Vercel
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "20.x"

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Deploy API Docs to Vercel
        id: deploy
        working-directory: ./api/openapi
        run: |
          vercel link --token ${{ secrets.VERCEL_TOKEN }} --scope ${{ secrets.VERCEL_ORG_ID }} --project ${{ secrets.VERCEL_DOCS_PROJECT_ID }} --yes
          vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --yes
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_DOCS_PROJECT_ID }}
