name: License Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-licenses:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Feluda
        run: |
          curl -LO https://github.com/anistark/feluda/releases/download/v1.10.2/feluda-v1.10.2-x86_64.deb
          dpkg -i feluda-v1.10.2-x86_64.deb

      - name: Check licenses
        run: |
            feluda \
                --language go \
                --project-license AGPL-3.0 \
                --ci-format github \
                --fail-on-restrictive
                # TODO: Enable `--fail-on-incompatible` once Feluda supports license
                #   exclusion and fixes compatibility matrix issues.
