packages:
  - .
onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - esbuild
  - unrs-resolver
catalog:
  "@hey-api/openapi-ts": ^0.80.1
  "@hookform/resolvers": ^5.2.0
  "@playwright/test": ^1.54.1
  "@radix-ui/react-alert-dialog": ^1.1.14
  "@radix-ui/react-avatar": ^1.1.10
  "@radix-ui/react-checkbox": ^1.3.2
  "@radix-ui/react-dialog": ^1.1.14
  "@radix-ui/react-dropdown-menu": ^2.1.15
  "@radix-ui/react-label": ^2.1.7
  "@radix-ui/react-popover": ^1.1.14
  "@radix-ui/react-progress": ^1.1.7
  "@radix-ui/react-scroll-area": ^1.2.9
  "@radix-ui/react-select": ^2.2.5
  "@radix-ui/react-separator": ^1.1.7
  "@radix-ui/react-slot": ^1.2.3
  "@radix-ui/react-switch": ^1.2.5
  "@radix-ui/react-tabs": ^1.1.12
  "@radix-ui/react-tooltip": ^1.2.7
  "@storybook/addon-a11y": ^9.0.18
  "@storybook/addon-docs": ^9.0.18
  "@storybook/addon-themes": ^9.0.18
  "@storybook/react-vite": ^9.0.18
  "@storybook/test-runner": ^0.23.0
  "@tailwindcss/postcss": ^4.1.11
  "@tanstack/eslint-config": ^0.3.0
  "@tanstack/react-query": ^5.83.0
  "@tanstack/react-query-devtools": ^5.83.0
  "@tanstack/react-router": ^1.130.1
  "@tanstack/react-start": ^1.130.1
  "@types/js-cookie": ^3.0.6
  "@types/node": ^24.1.0
  "@types/react": ^19.1.8
  "@types/react-dom": ^19.1.6
  "@typescript-eslint/eslint-plugin": ^8.38.0
  "@typescript-eslint/parser": ^8.38.0
  "@vitejs/plugin-react": ^4.7.0
  "@vitest/browser": ^3.2.4
  "@vitest/coverage-v8": ^3.2.4
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  cmdk: ^1.1.1
  date-fns: ^4.1.0
  dotenv: ^17.2.1
  eslint: ^9.32.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-import: ^2.32.0
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-prettier: ^5.5.3
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-storybook: ^9.0.18
  framer-motion: ^12.23.9
  globals: ^16.3.0
  jose: ^6.0.12
  js-cookie: ^3.0.5
  lucide-react: ^0.526.0
  neo4j-driver: ^5.28.1
  next-themes: ^0.4.6
  playwright: ^1.54.1
  postcss: ^8.5.6
  prettier: ^3.6.2
  prettier-plugin-tailwindcss: ^0.6.14
  react: ^19.1.0
  react-day-picker: ^9.8.1
  react-dom: ^19.1.0
  react-hook-form: ^7.61.1
  recharts: 2.15.4
  sonner: ^2.0.6
  storybook: ^9.0.18
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.11
  tw-animate-css: ^1.3.6
  typescript: ^5.8.3
  vite: ^7.0.6
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.2.4
  zod: ^4.0.10
